sudo: required
language: cpp
services:
  - docker
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  allow_failures:
  - env: TARGET=py3
script:
    - travis_wait 30 docker build . -t ska-sa/meqtrees-timba:${TARGET} -f .travis/${TARGET}.docker
