#!/bin/bash
#% $Id$ 
# simple shell script for mass-replace operations
#
# Copyright (C) 2002-2007
# The MeqTree Foundation & 
# ASTRON (Netherlands Foundation for Research in Astronomy)
# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>,
# or write to the Free Software Foundation, Inc., 
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

find="$1"
rep="$2"
shift
shift
files="$*"

if [ "$files" == "" ]; then
  echo "$0: mass-replaces patterns in a collection of files";
  echo "Usage: $0 <find> <replace> <filenames>"
  exit 1
fi

echo Replacing /$find/ by /$rep/ in $files

for file in $files; do
  if sed "s/$find/$rep/g" <$file >$file.rep; then
    if ! diff $file $file.rep >/dev/null; then
      mv $file $file.orig
      mv $file.rep $file
      echo Replaced in $file
    fi
  fi
done
