      #ifndef AID_MeqNodes_h
      #define AID_MeqNodes_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MeqNodes ();

#ifndef _defined_id_AidBit
#define _defined_id_AidBit 1
const AtomicID AidBit(-1428);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/FlagCompare.h:30
const int AidBit_int = -1428;
#endif
#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const AtomicID AidCells(-1247);                   // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Result.h:35
const int AidCells_int = -1247;
#endif
#ifndef _defined_id_AidDFT
#define _defined_id_AidDFT 1
const AtomicID AidDFT(-1475);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:31
const int AidDFT_int = -1475;
#endif
#ifndef _defined_id_AidDec
#define _defined_id_AidDec 1
const AtomicID AidDec(-1379);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:30
const int AidDec_int = -1379;
#endif
#ifndef _defined_id_AidDensity
#define _defined_id_AidDensity 1
const AtomicID AidDensity(-1440);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Resampler.h:31
const int AidDensity_int = -1440;
#endif
#ifndef _defined_id_AidEQ
#define _defined_id_AidEQ 1
const AtomicID AidEQ(-1434);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidEQ_int = -1434;
#endif
#ifndef _defined_id_AidFactor
#define _defined_id_AidFactor 1
const AtomicID AidFactor(-1448);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ModRes.h:32
const int AidFactor_int = -1448;
#endif
#ifndef _defined_id_AidFlag
#define _defined_id_AidFlag 1
const AtomicID AidFlag(-1135);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidFlag_int = -1135;
#endif
#ifndef _defined_id_AidGE
#define _defined_id_AidGE 1
const AtomicID AidGE(-1431);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidGE_int = -1431;
#endif
#ifndef _defined_id_AidGT
#define _defined_id_AidGT 1
const AtomicID AidGT(-1432);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidGT_int = -1432;
#endif
#ifndef _defined_id_AidIntegrate
#define _defined_id_AidIntegrate 1
const AtomicID AidIntegrate(-1172);               // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidIntegrate_int = -1172;
#endif
#ifndef _defined_id_AidLE
#define _defined_id_AidLE 1
const AtomicID AidLE(-1430);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidLE_int = -1430;
#endif
#ifndef _defined_id_AidLMN
#define _defined_id_AidLMN 1
const AtomicID AidLMN(-1476);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/StatPointSourceDFT.h:31
const int AidLMN_int = -1476;
#endif
#ifndef _defined_id_AidLT
#define _defined_id_AidLT 1
const AtomicID AidLT(-1436);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidLT_int = -1436;
#endif
#ifndef _defined_id_AidMask
#define _defined_id_AidMask 1
const AtomicID AidMask(-1287);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgentVocabulary.h:35
const int AidMask_int = -1287;
#endif
#ifndef _defined_id_AidMeqAdd
#define _defined_id_AidMeqAdd 1
const AtomicID AidMeqAdd(-1236);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Add.h:29
const int AidMeqAdd_int = -1236;
#endif
#ifndef _defined_id_AidMeqComposer
#define _defined_id_AidMeqComposer 1
const AtomicID AidMeqComposer(-1241);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Composer.h:29
const int AidMeqComposer_int = -1241;
#endif
#ifndef _defined_id_AidMeqCondeq
#define _defined_id_AidMeqCondeq 1
const AtomicID AidMeqCondeq(-1365);               // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Condeq.h:29
const int AidMeqCondeq_int = -1365;
#endif
#ifndef _defined_id_AidMeqConj
#define _defined_id_AidMeqConj 1
const AtomicID AidMeqConj(-1212);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Conj.h:29
const int AidMeqConj_int = -1212;
#endif
#ifndef _defined_id_AidMeqConstant
#define _defined_id_AidMeqConstant 1
const AtomicID AidMeqConstant(-1387);             // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Constant.h:32
const int AidMeqConstant_int = -1387;
#endif
#ifndef _defined_id_AidMeqCos
#define _defined_id_AidMeqCos 1
const AtomicID AidMeqCos(-1243);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Cos.h:29
const int AidMeqCos_int = -1243;
#endif
#ifndef _defined_id_AidMeqDivide
#define _defined_id_AidMeqDivide 1
const AtomicID AidMeqDivide(-1223);               // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Divide.h:29
const int AidMeqDivide_int = -1223;
#endif
#ifndef _defined_id_AidMeqExp
#define _defined_id_AidMeqExp 1
const AtomicID AidMeqExp(-1240);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Exp.h:29
const int AidMeqExp_int = -1240;
#endif
#ifndef _defined_id_AidMeqFreq
#define _defined_id_AidMeqFreq 1
const AtomicID AidMeqFreq(-1219);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Freq.h:29
const int AidMeqFreq_int = -1219;
#endif
#ifndef _defined_id_AidMeqLMN
#define _defined_id_AidMeqLMN 1
const AtomicID AidMeqLMN(-1467);                  // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/LMN.h:29
const int AidMeqLMN_int = -1467;
#endif
#ifndef _defined_id_AidMeqMergeFlags
#define _defined_id_AidMeqMergeFlags 1
const AtomicID AidMeqMergeFlags(-1437);           // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/MergeFlags.h:30
const int AidMeqMergeFlags_int = -1437;
#endif
#ifndef _defined_id_AidMeqModRes
#define _defined_id_AidMeqModRes 1
const AtomicID AidMeqModRes(-1447);               // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ModRes.h:31
const int AidMeqModRes_int = -1447;
#endif
#ifndef _defined_id_AidMeqMultiply
#define _defined_id_AidMeqMultiply 1
const AtomicID AidMeqMultiply(-1227);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Multiply.h:29
const int AidMeqMultiply_int = -1227;
#endif
#ifndef _defined_id_AidMeqParm
#define _defined_id_AidMeqParm 1
const AtomicID AidMeqParm(-1244);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Parm.h:35
const int AidMeqParm_int = -1244;
#endif
#ifndef _defined_id_AidMeqPointSourceDFT
#define _defined_id_AidMeqPointSourceDFT 1
const AtomicID AidMeqPointSourceDFT(-1469);       // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:30
const int AidMeqPointSourceDFT_int = -1469;
#endif
#ifndef _defined_id_AidMeqPolc
#define _defined_id_AidMeqPolc 1
const AtomicID AidMeqPolc(-1407);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Polc.h:32
const int AidMeqPolc_int = -1407;
#endif
#ifndef _defined_id_AidMeqPow
#define _defined_id_AidMeqPow 1
const AtomicID AidMeqPow(-1214);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Pow.h:29
const int AidMeqPow_int = -1214;
#endif
#ifndef _defined_id_AidMeqReqSeq
#define _defined_id_AidMeqReqSeq 1
const AtomicID AidMeqReqSeq(-1478);               // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ReqSeq.h:30
const int AidMeqReqSeq_int = -1478;
#endif
#ifndef _defined_id_AidMeqResampler
#define _defined_id_AidMeqResampler 1
const AtomicID AidMeqResampler(-1439);            // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Resampler.h:30
const int AidMeqResampler_int = -1439;
#endif
#ifndef _defined_id_AidMeqSelector
#define _defined_id_AidMeqSelector 1
const AtomicID AidMeqSelector(-1255);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Selector.h:29
const int AidMeqSelector_int = -1255;
#endif
#ifndef _defined_id_AidMeqSin
#define _defined_id_AidMeqSin 1
const AtomicID AidMeqSin(-1224);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sin.h:29
const int AidMeqSin_int = -1224;
#endif
#ifndef _defined_id_AidMeqSolver
#define _defined_id_AidMeqSolver 1
const AtomicID AidMeqSolver(-1367);               // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Solver.h:31
const int AidMeqSolver_int = -1367;
#endif
#ifndef _defined_id_AidMeqSqr
#define _defined_id_AidMeqSqr 1
const AtomicID AidMeqSqr(-1249);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sqr.h:29
const int AidMeqSqr_int = -1249;
#endif
#ifndef _defined_id_AidMeqSqrt
#define _defined_id_AidMeqSqrt 1
const AtomicID AidMeqSqrt(-1251);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sqrt.h:29
const int AidMeqSqrt_int = -1251;
#endif
#ifndef _defined_id_AidMeqStatPointSourceDFT
#define _defined_id_AidMeqStatPointSourceDFT 1
const AtomicID AidMeqStatPointSourceDFT(-1468);   // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/StatPointSourceDFT.h:30
const int AidMeqStatPointSourceDFT_int = -1468;
#endif
#ifndef _defined_id_AidMeqSubtract
#define _defined_id_AidMeqSubtract 1
const AtomicID AidMeqSubtract(-1232);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Subtract.h:29
const int AidMeqSubtract_int = -1232;
#endif
#ifndef _defined_id_AidMeqTime
#define _defined_id_AidMeqTime 1
const AtomicID AidMeqTime(-1225);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Time.h:29
const int AidMeqTime_int = -1225;
#endif
#ifndef _defined_id_AidMeqToComplex
#define _defined_id_AidMeqToComplex 1
const AtomicID AidMeqToComplex(-1217);            // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ToComplex.h:29
const int AidMeqToComplex_int = -1217;
#endif
#ifndef _defined_id_AidMeqUVW
#define _defined_id_AidMeqUVW 1
const AtomicID AidMeqUVW(-1239);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:29
const int AidMeqUVW_int = -1239;
#endif
#ifndef _defined_id_AidMeqZeroFlagger
#define _defined_id_AidMeqZeroFlagger 1
const AtomicID AidMeqZeroFlagger(-1433);          // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:29
const int AidMeqZeroFlagger_int = -1433;
#endif
#ifndef _defined_id_AidN
#define _defined_id_AidN 1
const AtomicID AidN(-1020);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidN_int = -1020;
#endif
#ifndef _defined_id_AidNE
#define _defined_id_AidNE 1
const AtomicID AidNE(-1429);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidNE_int = -1429;
#endif
#ifndef _defined_id_AidNum
#define _defined_id_AidNum 1
const AtomicID AidNum(-1177);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidNum_int = -1177;
#endif
#ifndef _defined_id_AidOnly
#define _defined_id_AidOnly 1
const AtomicID AidOnly(-1477);                    // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ReqSeq.h:31
const int AidOnly_int = -1477;
#endif
#ifndef _defined_id_AidOper
#define _defined_id_AidOper 1
const AtomicID AidOper(-1435);                    // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ZeroFlagger.h:30
const int AidOper_int = -1435;
#endif
#ifndef _defined_id_AidRA
#define _defined_id_AidRA 1
const AtomicID AidRA(-1380);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:30
const int AidRA_int = -1380;
#endif
#ifndef _defined_id_AidSt
#define _defined_id_AidSt 1
const AtomicID AidSt(-1474);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:31
const int AidSt_int = -1474;
#endif
#ifndef _defined_id_AidUVW
#define _defined_id_AidUVW 1
const AtomicID AidUVW(-1158);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidUVW_int = -1158;
#endif
#ifndef _defined_id_AidX
#define _defined_id_AidX 1
const AtomicID AidX(-1030);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidX_int = -1030;
#endif
#ifndef _defined_id_AidY
#define _defined_id_AidY 1
const AtomicID AidY(-1031);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidY_int = -1031;
#endif
#ifndef _defined_id_AidZ
#define _defined_id_AidZ 1
const AtomicID AidZ(-1032);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidZ_int = -1032;
#endif


#endif
