      #ifndef AID_MeqNodes_h
      #define AID_MeqNodes_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/noordam/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MeqNodes ();

#ifndef _defined_id_AidAttrib
#define _defined_id_AidAttrib 1
const AtomicID AidAttrib(-1551);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidAttrib_int = -1551;
#endif
#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const AtomicID AidCells(-1247);                   // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Result.h:35
const int AidCells_int = -1247;
#endif
#ifndef _defined_id_AidColor
#define _defined_id_AidColor 1
const AtomicID AidColor(-1555);                   // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidColor_int = -1555;
#endif
#ifndef _defined_id_AidDFT
#define _defined_id_AidDFT 1
const AtomicID AidDFT(-1475);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:31
const int AidDFT_int = -1475;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1116);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/test/EchoWP.h:13
const int AidData_int = -1116;
#endif
#ifndef _defined_id_AidDec
#define _defined_id_AidDec 1
const AtomicID AidDec(-1379);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:30
const int AidDec_int = -1379;
#endif
#ifndef _defined_id_AidFlag
#define _defined_id_AidFlag 1
const AtomicID AidFlag(-1135);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidFlag_int = -1135;
#endif
#ifndef _defined_id_AidGroup
#define _defined_id_AidGroup 1
const AtomicID AidGroup(-1122);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidGroup_int = -1122;
#endif
#ifndef _defined_id_AidItem
#define _defined_id_AidItem 1
const AtomicID AidItem(-1560);                    // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidItem_int = -1560;
#endif
#ifndef _defined_id_AidLMN
#define _defined_id_AidLMN 1
const AtomicID AidLMN(-1476);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/StatPointSourceDFT.h:31
const int AidLMN_int = -1476;
#endif
#ifndef _defined_id_AidLabel
#define _defined_id_AidLabel 1
const AtomicID AidLabel(-1545);                   // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/VisTest.h:29
const int AidLabel_int = -1545;
#endif
#ifndef _defined_id_AidMask
#define _defined_id_AidMask 1
const AtomicID AidMask(-1287);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgentVocabulary.h:35
const int AidMask_int = -1287;
#endif
#ifndef _defined_id_AidMeqAbs
#define _defined_id_AidMeqAbs 1
const AtomicID AidMeqAbs(-1524);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Abs.h:29
const int AidMeqAbs_int = -1524;
#endif
#ifndef _defined_id_AidMeqAcos
#define _defined_id_AidMeqAcos 1
const AtomicID AidMeqAcos(-1506);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/ACos.h:29
const int AidMeqAcos_int = -1506;
#endif
#ifndef _defined_id_AidMeqAdd
#define _defined_id_AidMeqAdd 1
const AtomicID AidMeqAdd(-1236);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Add.h:29
const int AidMeqAdd_int = -1236;
#endif
#ifndef _defined_id_AidMeqArg
#define _defined_id_AidMeqArg 1
const AtomicID AidMeqArg(-1526);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Arg.h:29
const int AidMeqArg_int = -1526;
#endif
#ifndef _defined_id_AidMeqAsin
#define _defined_id_AidMeqAsin 1
const AtomicID AidMeqAsin(-1505);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/ASin.h:29
const int AidMeqAsin_int = -1505;
#endif
#ifndef _defined_id_AidMeqAtan
#define _defined_id_AidMeqAtan 1
const AtomicID AidMeqAtan(-1512);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/ATan.h:29
const int AidMeqAtan_int = -1512;
#endif
#ifndef _defined_id_AidMeqCeil
#define _defined_id_AidMeqCeil 1
const AtomicID AidMeqCeil(-1520);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Ceil.h:30
const int AidMeqCeil_int = -1520;
#endif
#ifndef _defined_id_AidMeqComposer
#define _defined_id_AidMeqComposer 1
const AtomicID AidMeqComposer(-1241);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Composer.h:29
const int AidMeqComposer_int = -1241;
#endif
#ifndef _defined_id_AidMeqCondeq
#define _defined_id_AidMeqCondeq 1
const AtomicID AidMeqCondeq(-1365);               // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Condeq.h:29
const int AidMeqCondeq_int = -1365;
#endif
#ifndef _defined_id_AidMeqConj
#define _defined_id_AidMeqConj 1
const AtomicID AidMeqConj(-1212);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Conj.h:29
const int AidMeqConj_int = -1212;
#endif
#ifndef _defined_id_AidMeqConstant
#define _defined_id_AidMeqConstant 1
const AtomicID AidMeqConstant(-1387);             // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Constant.h:32
const int AidMeqConstant_int = -1387;
#endif
#ifndef _defined_id_AidMeqCos
#define _defined_id_AidMeqCos 1
const AtomicID AidMeqCos(-1243);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Cos.h:29
const int AidMeqCos_int = -1243;
#endif
#ifndef _defined_id_AidMeqCosh
#define _defined_id_AidMeqCosh 1
const AtomicID AidMeqCosh(-1510);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Cosh.h:29
const int AidMeqCosh_int = -1510;
#endif
#ifndef _defined_id_AidMeqDataCollect
#define _defined_id_AidMeqDataCollect 1
const AtomicID AidMeqDataCollect(-1550);          // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:29
const int AidMeqDataCollect_int = -1550;
#endif
#ifndef _defined_id_AidMeqDataConcat
#define _defined_id_AidMeqDataConcat 1
const AtomicID AidMeqDataConcat(-1553);           // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataConcat.h:29
const int AidMeqDataConcat_int = -1553;
#endif
#ifndef _defined_id_AidMeqDivide
#define _defined_id_AidMeqDivide 1
const AtomicID AidMeqDivide(-1223);               // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Divide.h:29
const int AidMeqDivide_int = -1223;
#endif
#ifndef _defined_id_AidMeqExp
#define _defined_id_AidMeqExp 1
const AtomicID AidMeqExp(-1240);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Exp.h:29
const int AidMeqExp_int = -1240;
#endif
#ifndef _defined_id_AidMeqFabs
#define _defined_id_AidMeqFabs 1
const AtomicID AidMeqFabs(-1525);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Fabs.h:29
const int AidMeqFabs_int = -1525;
#endif
#ifndef _defined_id_AidMeqFloor
#define _defined_id_AidMeqFloor 1
const AtomicID AidMeqFloor(-1521);                // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Floor.h:30
const int AidMeqFloor_int = -1521;
#endif
#ifndef _defined_id_AidMeqFreq
#define _defined_id_AidMeqFreq 1
const AtomicID AidMeqFreq(-1219);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Freq.h:29
const int AidMeqFreq_int = -1219;
#endif
#ifndef _defined_id_AidMeqImag
#define _defined_id_AidMeqImag 1
const AtomicID AidMeqImag(-1523);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Imag.h:29
const int AidMeqImag_int = -1523;
#endif
#ifndef _defined_id_AidMeqLMN
#define _defined_id_AidMeqLMN 1
const AtomicID AidMeqLMN(-1467);                  // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/LMN.h:29
const int AidMeqLMN_int = -1467;
#endif
#ifndef _defined_id_AidMeqLog
#define _defined_id_AidMeqLog 1
const AtomicID AidMeqLog(-1507);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Log.h:29
const int AidMeqLog_int = -1507;
#endif
#ifndef _defined_id_AidMeqMax
#define _defined_id_AidMeqMax 1
const AtomicID AidMeqMax(-1530);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Max.h:29
const int AidMeqMax_int = -1530;
#endif
#ifndef _defined_id_AidMeqMean
#define _defined_id_AidMeqMean 1
const AtomicID AidMeqMean(-1528);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Mean.h:29
const int AidMeqMean_int = -1528;
#endif
#ifndef _defined_id_AidMeqMergeFlags
#define _defined_id_AidMeqMergeFlags 1
const AtomicID AidMeqMergeFlags(-1437);           // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/MergeFlags.h:30
const int AidMeqMergeFlags_int = -1437;
#endif
#ifndef _defined_id_AidMeqMin
#define _defined_id_AidMeqMin 1
const AtomicID AidMeqMin(-1532);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Min.h:29
const int AidMeqMin_int = -1532;
#endif
#ifndef _defined_id_AidMeqMultiply
#define _defined_id_AidMeqMultiply 1
const AtomicID AidMeqMultiply(-1227);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Multiply.h:29
const int AidMeqMultiply_int = -1227;
#endif
#ifndef _defined_id_AidMeqNorm
#define _defined_id_AidMeqNorm 1
const AtomicID AidMeqNorm(-1527);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Norm.h:29
const int AidMeqNorm_int = -1527;
#endif
#ifndef _defined_id_AidMeqParm
#define _defined_id_AidMeqParm 1
const AtomicID AidMeqParm(-1244);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Parm.h:35
const int AidMeqParm_int = -1244;
#endif
#ifndef _defined_id_AidMeqPointSourceDFT
#define _defined_id_AidMeqPointSourceDFT 1
const AtomicID AidMeqPointSourceDFT(-1469);       // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:30
const int AidMeqPointSourceDFT_int = -1469;
#endif
#ifndef _defined_id_AidMeqPolar
#define _defined_id_AidMeqPolar 1
const AtomicID AidMeqPolar(-1503);                // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Polar.h:30
const int AidMeqPolar_int = -1503;
#endif
#ifndef _defined_id_AidMeqPow
#define _defined_id_AidMeqPow 1
const AtomicID AidMeqPow(-1214);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Pow.h:29
const int AidMeqPow_int = -1214;
#endif
#ifndef _defined_id_AidMeqPow2
#define _defined_id_AidMeqPow2 1
const AtomicID AidMeqPow2(-1513);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow2.h:29
const int AidMeqPow2_int = -1513;
#endif
#ifndef _defined_id_AidMeqPow3
#define _defined_id_AidMeqPow3 1
const AtomicID AidMeqPow3(-1514);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow3.h:29
const int AidMeqPow3_int = -1514;
#endif
#ifndef _defined_id_AidMeqPow4
#define _defined_id_AidMeqPow4 1
const AtomicID AidMeqPow4(-1515);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow4.h:29
const int AidMeqPow4_int = -1515;
#endif
#ifndef _defined_id_AidMeqPow5
#define _defined_id_AidMeqPow5 1
const AtomicID AidMeqPow5(-1516);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow5.h:29
const int AidMeqPow5_int = -1516;
#endif
#ifndef _defined_id_AidMeqPow6
#define _defined_id_AidMeqPow6 1
const AtomicID AidMeqPow6(-1517);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow6.h:29
const int AidMeqPow6_int = -1517;
#endif
#ifndef _defined_id_AidMeqPow7
#define _defined_id_AidMeqPow7 1
const AtomicID AidMeqPow7(-1518);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow7.h:29
const int AidMeqPow7_int = -1518;
#endif
#ifndef _defined_id_AidMeqPow8
#define _defined_id_AidMeqPow8 1
const AtomicID AidMeqPow8(-1519);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Pow8.h:29
const int AidMeqPow8_int = -1519;
#endif
#ifndef _defined_id_AidMeqReal
#define _defined_id_AidMeqReal 1
const AtomicID AidMeqReal(-1522);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Real.h:29
const int AidMeqReal_int = -1522;
#endif
#ifndef _defined_id_AidMeqReqSeq
#define _defined_id_AidMeqReqSeq 1
const AtomicID AidMeqReqSeq(-1478);               // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ReqSeq.h:30
const int AidMeqReqSeq_int = -1478;
#endif
#ifndef _defined_id_AidMeqSelector
#define _defined_id_AidMeqSelector 1
const AtomicID AidMeqSelector(-1255);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Selector.h:29
const int AidMeqSelector_int = -1255;
#endif
#ifndef _defined_id_AidMeqSin
#define _defined_id_AidMeqSin 1
const AtomicID AidMeqSin(-1224);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sin.h:29
const int AidMeqSin_int = -1224;
#endif
#ifndef _defined_id_AidMeqSinh
#define _defined_id_AidMeqSinh 1
const AtomicID AidMeqSinh(-1508);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Sinh.h:29
const int AidMeqSinh_int = -1508;
#endif
#ifndef _defined_id_AidMeqSolver
#define _defined_id_AidMeqSolver 1
const AtomicID AidMeqSolver(-1367);               // from /home/gvd/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/Solver.h:31
const int AidMeqSolver_int = -1367;
#endif
#ifndef _defined_id_AidMeqSqr
#define _defined_id_AidMeqSqr 1
const AtomicID AidMeqSqr(-1249);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sqr.h:29
const int AidMeqSqr_int = -1249;
#endif
#ifndef _defined_id_AidMeqSqrt
#define _defined_id_AidMeqSqrt 1
const AtomicID AidMeqSqrt(-1251);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Sqrt.h:29
const int AidMeqSqrt_int = -1251;
#endif
#ifndef _defined_id_AidMeqStatPointSourceDFT
#define _defined_id_AidMeqStatPointSourceDFT 1
const AtomicID AidMeqStatPointSourceDFT(-1468);   // from /home/diepen/sim/LOFAR/CEP/CPA/PSS4/MEQ/src/StatPointSourceDFT.h:30
const int AidMeqStatPointSourceDFT_int = -1468;
#endif
#ifndef _defined_id_AidMeqStripper
#define _defined_id_AidMeqStripper 1
const AtomicID AidMeqStripper(-1547);             // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Stripper.h:29
const int AidMeqStripper_int = -1547;
#endif
#ifndef _defined_id_AidMeqSubtract
#define _defined_id_AidMeqSubtract 1
const AtomicID AidMeqSubtract(-1232);             // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Subtract.h:29
const int AidMeqSubtract_int = -1232;
#endif
#ifndef _defined_id_AidMeqTan
#define _defined_id_AidMeqTan 1
const AtomicID AidMeqTan(-1511);                  // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Tan.h:29
const int AidMeqTan_int = -1511;
#endif
#ifndef _defined_id_AidMeqTanh
#define _defined_id_AidMeqTanh 1
const AtomicID AidMeqTanh(-1509);                 // from /home/assendorp/LOFAR/CEP/CPA/PSS4/MeqNodes/src/Tanh.h:29
const int AidMeqTanh_int = -1509;
#endif
#ifndef _defined_id_AidMeqTime
#define _defined_id_AidMeqTime 1
const AtomicID AidMeqTime(-1225);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/Time.h:29
const int AidMeqTime_int = -1225;
#endif
#ifndef _defined_id_AidMeqToComplex
#define _defined_id_AidMeqToComplex 1
const AtomicID AidMeqToComplex(-1217);            // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ToComplex.h:29
const int AidMeqToComplex_int = -1217;
#endif
#ifndef _defined_id_AidMeqUVW
#define _defined_id_AidMeqUVW 1
const AtomicID AidMeqUVW(-1239);                  // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:29
const int AidMeqUVW_int = -1239;
#endif
#ifndef _defined_id_AidN
#define _defined_id_AidN 1
const AtomicID AidN(-1020);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidN_int = -1020;
#endif
#ifndef _defined_id_AidOnly
#define _defined_id_AidOnly 1
const AtomicID AidOnly(-1477);                    // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/ReqSeq.h:31
const int AidOnly_int = -1477;
#endif
#ifndef _defined_id_AidPlot
#define _defined_id_AidPlot 1
const AtomicID AidPlot(-1552);                    // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidPlot_int = -1552;
#endif
#ifndef _defined_id_AidProfile
#define _defined_id_AidProfile 1
const AtomicID AidProfile(-1561);                 // from /home/noordam/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidProfile_int = -1561;
#endif
#ifndef _defined_id_AidRA
#define _defined_id_AidRA 1
const AtomicID AidRA(-1380);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/UVW.h:30
const int AidRA_int = -1380;
#endif
#ifndef _defined_id_AidSize
#define _defined_id_AidSize 1
const AtomicID AidSize(-1292);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/MSVisAgent/src/MSVisAgentVocabulary.h:34
const int AidSize_int = -1292;
#endif
#ifndef _defined_id_AidSkeleton
#define _defined_id_AidSkeleton 1
const AtomicID AidSkeleton(-1557);                // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataConcat.h:30
const int AidSkeleton_int = -1557;
#endif
#ifndef _defined_id_AidSt
#define _defined_id_AidSt 1
const AtomicID AidSt(-1474);                      // from /home/oms/LOFAR/CEP/CPA/PSS4/MEQ/src/PointSourceDFT.h:31
const int AidSt_int = -1474;
#endif
#ifndef _defined_id_AidStyle
#define _defined_id_AidStyle 1
const AtomicID AidStyle(-1554);                   // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidStyle_int = -1554;
#endif
#ifndef _defined_id_AidTop
#define _defined_id_AidTop 1
const AtomicID AidTop(-1548);                     // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidTop_int = -1548;
#endif
#ifndef _defined_id_AidUVW
#define _defined_id_AidUVW 1
const AtomicID AidUVW(-1158);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidUVW_int = -1158;
#endif
#ifndef _defined_id_AidVisu
#define _defined_id_AidVisu 1
const AtomicID AidVisu(-1559);                    // from /home/twillis/LOFAR/CEP/CPA/PSS4/MeqNodes/src/DataCollect.h:30
const int AidVisu_int = -1559;
#endif
#ifndef _defined_id_AidX
#define _defined_id_AidX 1
const AtomicID AidX(-1030);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidX_int = -1030;
#endif
#ifndef _defined_id_AidXX
#define _defined_id_AidXX 1
const AtomicID AidXX(-1161);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidXX_int = -1161;
#endif
#ifndef _defined_id_AidXY
#define _defined_id_AidXY 1
const AtomicID AidXY(-1162);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidXY_int = -1162;
#endif
#ifndef _defined_id_AidY
#define _defined_id_AidY 1
const AtomicID AidY(-1031);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidY_int = -1031;
#endif
#ifndef _defined_id_AidYX
#define _defined_id_AidYX 1
const AtomicID AidYX(-1182);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidYX_int = -1182;
#endif
#ifndef _defined_id_AidYY
#define _defined_id_AidYY 1
const AtomicID AidYY(-1183);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidYY_int = -1183;
#endif
#ifndef _defined_id_AidZ
#define _defined_id_AidZ 1
const AtomicID AidZ(-1032);                       // from /home/oms/LOFAR/DMI/src/AtomicID.h:34
const int AidZ_int = -1032;
#endif


#endif
