      #ifndef AID_MeqNodes_h
      #define AID_MeqNodes_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_MeqNodes ();

#ifndef _defined_id_AidAdditional
#define _defined_id_AidAdditional 1
const DMI::AtomicID AidAdditional(-1524);         // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidAdditional_int = -1524;
#endif
#ifndef _defined_id_AidAttrib
#define _defined_id_AidAttrib 1
const DMI::AtomicID AidAttrib(-1382);             // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidAttrib_int = -1382;
#endif
#ifndef _defined_id_AidBit
#define _defined_id_AidBit 1
const DMI::AtomicID AidBit(-1293);                // from /home/oms/LOFAR/Timba/MEQ/src/MeqVocabulary.h:40
const int AidBit_int = -1293;
#endif
#ifndef _defined_id_AidCells
#define _defined_id_AidCells 1
const DMI::AtomicID AidCells(-1291);              // from /home/oms/LOFAR/Timba/MEQ/src/MeqVocabulary.h:33
const int AidCells_int = -1291;
#endif
#ifndef _defined_id_AidColor
#define _defined_id_AidColor 1
const DMI::AtomicID AidColor(-1426);              // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidColor_int = -1426;
#endif
#ifndef _defined_id_AidConj
#define _defined_id_AidConj 1
const DMI::AtomicID AidConj(-1520);               // from /home/oms/LOFAR/Timba/MeqNodes/src/Transpose.h:33
const int AidConj_int = -1520;
#endif
#ifndef _defined_id_AidCount
#define _defined_id_AidCount 1
const DMI::AtomicID AidCount(-1099);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/test/EchoWP.h:11
const int AidCount_int = -1099;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const DMI::AtomicID AidData(-1103);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/test/EchoWP.h:11
const int AidData_int = -1103;
#endif
#ifndef _defined_id_AidDec
#define _defined_id_AidDec 1
const DMI::AtomicID AidDec(-1446);                // from /home/oms/LOFAR/Timba/MeqNodes/src/UVW.h:32
const int AidDec_int = -1446;
#endif
#ifndef _defined_id_AidEQ
#define _defined_id_AidEQ 1
const DMI::AtomicID AidEQ(-1444);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidEQ_int = -1444;
#endif
#ifndef _defined_id_AidFlag
#define _defined_id_AidFlag 1
const DMI::AtomicID AidFlag(-1134);               // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:27
const int AidFlag_int = -1134;
#endif
#ifndef _defined_id_AidForce
#define _defined_id_AidForce 1
const DMI::AtomicID AidForce(-1498);              // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidForce_int = -1498;
#endif
#ifndef _defined_id_AidGE
#define _defined_id_AidGE 1
const DMI::AtomicID AidGE(-1424);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidGE_int = -1424;
#endif
#ifndef _defined_id_AidGT
#define _defined_id_AidGT 1
const DMI::AtomicID AidGT(-1431);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidGT_int = -1431;
#endif
#ifndef _defined_id_AidIncremental
#define _defined_id_AidIncremental 1
const DMI::AtomicID AidIncremental(-1515);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Solver.h:32
const int AidIncremental_int = -1515;
#endif
#ifndef _defined_id_AidInfo
#define _defined_id_AidInfo 1
const DMI::AtomicID AidInfo(-1494);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:31
const int AidInfo_int = -1494;
#endif
#ifndef _defined_id_AidLE
#define _defined_id_AidLE 1
const DMI::AtomicID AidLE(-1414);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidLE_int = -1414;
#endif
#ifndef _defined_id_AidLMN
#define _defined_id_AidLMN 1
const DMI::AtomicID AidLMN(-1402);                // from /home/oms/LOFAR/Timba/MeqNodes/src/StatPointSourceDFT.h:32
const int AidLMN_int = -1402;
#endif
#ifndef _defined_id_AidLT
#define _defined_id_AidLT 1
const DMI::AtomicID AidLT(-1455);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidLT_int = -1455;
#endif
#ifndef _defined_id_AidLabel
#define _defined_id_AidLabel 1
const DMI::AtomicID AidLabel(-1456);              // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidLabel_int = -1456;
#endif
#ifndef _defined_id_AidMap
#define _defined_id_AidMap 1
const DMI::AtomicID AidMap(-1216);                // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidMap_int = -1216;
#endif
#ifndef _defined_id_AidMask
#define _defined_id_AidMask 1
const DMI::AtomicID AidMask(-1263);               // from /home/oms/LOFAR/Timba/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:35
const int AidMask_int = -1263;
#endif
#ifndef _defined_id_AidMeqAbs
#define _defined_id_AidMeqAbs 1
const DMI::AtomicID AidMeqAbs(-1460);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Abs.h:29
const int AidMeqAbs_int = -1460;
#endif
#ifndef _defined_id_AidMeqAcos
#define _defined_id_AidMeqAcos 1
const DMI::AtomicID AidMeqAcos(-1411);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Acos.h:29
const int AidMeqAcos_int = -1411;
#endif
#ifndef _defined_id_AidMeqAdd
#define _defined_id_AidMeqAdd 1
const DMI::AtomicID AidMeqAdd(-1418);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Add.h:30
const int AidMeqAdd_int = -1418;
#endif
#ifndef _defined_id_AidMeqArg
#define _defined_id_AidMeqArg 1
const DMI::AtomicID AidMeqArg(-1457);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Arg.h:29
const int AidMeqArg_int = -1457;
#endif
#ifndef _defined_id_AidMeqAsin
#define _defined_id_AidMeqAsin 1
const DMI::AtomicID AidMeqAsin(-1399);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Asin.h:29
const int AidMeqAsin_int = -1399;
#endif
#ifndef _defined_id_AidMeqAtan
#define _defined_id_AidMeqAtan 1
const DMI::AtomicID AidMeqAtan(-1428);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Atan.h:29
const int AidMeqAtan_int = -1428;
#endif
#ifndef _defined_id_AidMeqAzEl
#define _defined_id_AidMeqAzEl 1
const DMI::AtomicID AidMeqAzEl(-1551);            // from /home/twillis/LOFAR/Timba/MeqNodes/src/AzEl.h:31
const int AidMeqAzEl_int = -1551;
#endif
#ifndef _defined_id_AidMeqCeil
#define _defined_id_AidMeqCeil 1
const DMI::AtomicID AidMeqCeil(-1437);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Ceil.h:30
const int AidMeqCeil_int = -1437;
#endif
#ifndef _defined_id_AidMeqComposer
#define _defined_id_AidMeqComposer 1
const DMI::AtomicID AidMeqComposer(-1442);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Composer.h:30
const int AidMeqComposer_int = -1442;
#endif
#ifndef _defined_id_AidMeqCondeq
#define _defined_id_AidMeqCondeq 1
const DMI::AtomicID AidMeqCondeq(-1443);          // from /home/oms/LOFAR/Timba/MeqNodes/src/Condeq.h:31
const int AidMeqCondeq_int = -1443;
#endif
#ifndef _defined_id_AidMeqConj
#define _defined_id_AidMeqConj 1
const DMI::AtomicID AidMeqConj(-1394);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Conj.h:30
const int AidMeqConj_int = -1394;
#endif
#ifndef _defined_id_AidMeqConstant
#define _defined_id_AidMeqConstant 1
const DMI::AtomicID AidMeqConstant(-1438);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Constant.h:34
const int AidMeqConstant_int = -1438;
#endif
#ifndef _defined_id_AidMeqCos
#define _defined_id_AidMeqCos 1
const DMI::AtomicID AidMeqCos(-1398);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Cos.h:30
const int AidMeqCos_int = -1398;
#endif
#ifndef _defined_id_AidMeqCosh
#define _defined_id_AidMeqCosh 1
const DMI::AtomicID AidMeqCosh(-1415);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Cosh.h:29
const int AidMeqCosh_int = -1415;
#endif
#ifndef _defined_id_AidMeqDataCollect
#define _defined_id_AidMeqDataCollect 1
const DMI::AtomicID AidMeqDataCollect(-1388);     // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:29
const int AidMeqDataCollect_int = -1388;
#endif
#ifndef _defined_id_AidMeqDataConcat
#define _defined_id_AidMeqDataConcat 1
const DMI::AtomicID AidMeqDataConcat(-1448);      // from /home/oms/LOFAR/Timba/MeqNodes/src/DataConcat.h:30
const int AidMeqDataConcat_int = -1448;
#endif
#ifndef _defined_id_AidMeqDivide
#define _defined_id_AidMeqDivide 1
const DMI::AtomicID AidMeqDivide(-1385);          // from /home/oms/LOFAR/Timba/MeqNodes/src/Divide.h:30
const int AidMeqDivide_int = -1385;
#endif
#ifndef _defined_id_AidMeqExp
#define _defined_id_AidMeqExp 1
const DMI::AtomicID AidMeqExp(-1393);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Exp.h:30
const int AidMeqExp_int = -1393;
#endif
#ifndef _defined_id_AidMeqFabs
#define _defined_id_AidMeqFabs 1
const DMI::AtomicID AidMeqFabs(-1429);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Fabs.h:29
const int AidMeqFabs_int = -1429;
#endif
#ifndef _defined_id_AidMeqFloor
#define _defined_id_AidMeqFloor 1
const DMI::AtomicID AidMeqFloor(-1436);           // from /home/oms/LOFAR/Timba/MeqNodes/src/Floor.h:30
const int AidMeqFloor_int = -1436;
#endif
#ifndef _defined_id_AidMeqFreq
#define _defined_id_AidMeqFreq 1
const DMI::AtomicID AidMeqFreq(-1420);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Freq.h:30
const int AidMeqFreq_int = -1420;
#endif
#ifndef _defined_id_AidMeqGaussNoise
#define _defined_id_AidMeqGaussNoise 1
const DMI::AtomicID AidMeqGaussNoise(-1449);      // from /home/oms/LOFAR/Timba/MeqNodes/src/GaussNoise.h:31
const int AidMeqGaussNoise_int = -1449;
#endif
#ifndef _defined_id_AidMeqImag
#define _defined_id_AidMeqImag 1
const DMI::AtomicID AidMeqImag(-1427);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Imag.h:29
const int AidMeqImag_int = -1427;
#endif
#ifndef _defined_id_AidMeqInvert
#define _defined_id_AidMeqInvert 1
const DMI::AtomicID AidMeqInvert(-1507);          // from /home/assendorp/LOFAR/Timba/MeqNodes/src/Invert.h:29
const int AidMeqInvert_int = -1507;
#endif
#ifndef _defined_id_AidMeqLMN
#define _defined_id_AidMeqLMN 1
const DMI::AtomicID AidMeqLMN(-1410);             // from /home/oms/LOFAR/Timba/MeqNodes/src/LMN.h:30
const int AidMeqLMN_int = -1410;
#endif
#ifndef _defined_id_AidMeqLog
#define _defined_id_AidMeqLog 1
const DMI::AtomicID AidMeqLog(-1397);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Log.h:29
const int AidMeqLog_int = -1397;
#endif
#ifndef _defined_id_AidMeqMatrixInvert22
#define _defined_id_AidMeqMatrixInvert22 1
const DMI::AtomicID AidMeqMatrixInvert22(-1522);  // from /home/oms/LOFAR/Timba/MeqNodes/src/MatrixInvert22.h:30
const int AidMeqMatrixInvert22_int = -1522;
#endif
#ifndef _defined_id_AidMeqMatrixMultiply
#define _defined_id_AidMeqMatrixMultiply 1
const DMI::AtomicID AidMeqMatrixMultiply(-1516);  // from /home/oms/LOFAR/Timba/MeqNodes/src/MatrixMultiply.h:30
const int AidMeqMatrixMultiply_int = -1516;
#endif
#ifndef _defined_id_AidMeqMax
#define _defined_id_AidMeqMax 1
const DMI::AtomicID AidMeqMax(-1452);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Max.h:29
const int AidMeqMax_int = -1452;
#endif
#ifndef _defined_id_AidMeqMean
#define _defined_id_AidMeqMean 1
const DMI::AtomicID AidMeqMean(-1416);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Mean.h:29
const int AidMeqMean_int = -1416;
#endif
#ifndef _defined_id_AidMeqMergeFlags
#define _defined_id_AidMeqMergeFlags 1
const DMI::AtomicID AidMeqMergeFlags(-1441);      // from /home/oms/LOFAR/Timba/MeqNodes/src/MergeFlags.h:31
const int AidMeqMergeFlags_int = -1441;
#endif
#ifndef _defined_id_AidMeqMin
#define _defined_id_AidMeqMin 1
const DMI::AtomicID AidMeqMin(-1392);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Min.h:29
const int AidMeqMin_int = -1392;
#endif
#ifndef _defined_id_AidMeqMultiply
#define _defined_id_AidMeqMultiply 1
const DMI::AtomicID AidMeqMultiply(-1391);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Multiply.h:30
const int AidMeqMultiply_int = -1391;
#endif
#ifndef _defined_id_AidMeqNElements
#define _defined_id_AidMeqNElements 1
const DMI::AtomicID AidMeqNElements(-1500);       // from /home/oms/LOFAR/Timba/MeqNodes/src/NElements.h:29
const int AidMeqNElements_int = -1500;
#endif
#ifndef _defined_id_AidMeqNegate
#define _defined_id_AidMeqNegate 1
const DMI::AtomicID AidMeqNegate(-1506);          // from /home/assendorp/LOFAR/Timba/MeqNodes/src/Negate.h:29
const int AidMeqNegate_int = -1506;
#endif
#ifndef _defined_id_AidMeqNorm
#define _defined_id_AidMeqNorm 1
const DMI::AtomicID AidMeqNorm(-1459);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Norm.h:29
const int AidMeqNorm_int = -1459;
#endif
#ifndef _defined_id_AidMeqParm
#define _defined_id_AidMeqParm 1
const DMI::AtomicID AidMeqParm(-1454);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Parm.h:35
const int AidMeqParm_int = -1454;
#endif
#ifndef _defined_id_AidMeqPaster
#define _defined_id_AidMeqPaster 1
const DMI::AtomicID AidMeqPaster(-1519);          // from /home/oms/LOFAR/Timba/MeqNodes/src/Paster.h:31
const int AidMeqPaster_int = -1519;
#endif
#ifndef _defined_id_AidMeqPolar
#define _defined_id_AidMeqPolar 1
const DMI::AtomicID AidMeqPolar(-1383);           // from /home/oms/LOFAR/Timba/MeqNodes/src/Polar.h:30
const int AidMeqPolar_int = -1383;
#endif
#ifndef _defined_id_AidMeqPow
#define _defined_id_AidMeqPow 1
const DMI::AtomicID AidMeqPow(-1386);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow.h:30
const int AidMeqPow_int = -1386;
#endif
#ifndef _defined_id_AidMeqPow2
#define _defined_id_AidMeqPow2 1
const DMI::AtomicID AidMeqPow2(-1439);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow2.h:29
const int AidMeqPow2_int = -1439;
#endif
#ifndef _defined_id_AidMeqPow3
#define _defined_id_AidMeqPow3 1
const DMI::AtomicID AidMeqPow3(-1412);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow3.h:29
const int AidMeqPow3_int = -1412;
#endif
#ifndef _defined_id_AidMeqPow4
#define _defined_id_AidMeqPow4 1
const DMI::AtomicID AidMeqPow4(-1403);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow4.h:29
const int AidMeqPow4_int = -1403;
#endif
#ifndef _defined_id_AidMeqPow5
#define _defined_id_AidMeqPow5 1
const DMI::AtomicID AidMeqPow5(-1422);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow5.h:29
const int AidMeqPow5_int = -1422;
#endif
#ifndef _defined_id_AidMeqPow6
#define _defined_id_AidMeqPow6 1
const DMI::AtomicID AidMeqPow6(-1445);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow6.h:29
const int AidMeqPow6_int = -1445;
#endif
#ifndef _defined_id_AidMeqPow7
#define _defined_id_AidMeqPow7 1
const DMI::AtomicID AidMeqPow7(-1387);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow7.h:29
const int AidMeqPow7_int = -1387;
#endif
#ifndef _defined_id_AidMeqPow8
#define _defined_id_AidMeqPow8 1
const DMI::AtomicID AidMeqPow8(-1395);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Pow8.h:29
const int AidMeqPow8_int = -1395;
#endif
#ifndef _defined_id_AidMeqProduct
#define _defined_id_AidMeqProduct 1
const DMI::AtomicID AidMeqProduct(-1501);         // from /home/oms/LOFAR/Timba/MeqNodes/src/Product.h:29
const int AidMeqProduct_int = -1501;
#endif
#ifndef _defined_id_AidMeqRandomNoise
#define _defined_id_AidMeqRandomNoise 1
const DMI::AtomicID AidMeqRandomNoise(-1384);     // from /home/oms/LOFAR/Timba/MeqNodes/src/RandomNoise.h:31
const int AidMeqRandomNoise_int = -1384;
#endif
#ifndef _defined_id_AidMeqReal
#define _defined_id_AidMeqReal 1
const DMI::AtomicID AidMeqReal(-1404);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Real.h:29
const int AidMeqReal_int = -1404;
#endif
#ifndef _defined_id_AidMeqReqSeq
#define _defined_id_AidMeqReqSeq 1
const DMI::AtomicID AidMeqReqSeq(-1425);          // from /home/oms/LOFAR/Timba/MeqNodes/src/ReqSeq.h:31
const int AidMeqReqSeq_int = -1425;
#endif
#ifndef _defined_id_AidMeqSelector
#define _defined_id_AidMeqSelector 1
const DMI::AtomicID AidMeqSelector(-1447);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Selector.h:30
const int AidMeqSelector_int = -1447;
#endif
#ifndef _defined_id_AidMeqSin
#define _defined_id_AidMeqSin 1
const DMI::AtomicID AidMeqSin(-1430);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Sin.h:30
const int AidMeqSin_int = -1430;
#endif
#ifndef _defined_id_AidMeqSinh
#define _defined_id_AidMeqSinh 1
const DMI::AtomicID AidMeqSinh(-1407);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Sinh.h:29
const int AidMeqSinh_int = -1407;
#endif
#ifndef _defined_id_AidMeqSolver
#define _defined_id_AidMeqSolver 1
const DMI::AtomicID AidMeqSolver(-1401);          // from /home/oms/LOFAR/Timba/MeqNodes/src/Solver.h:30
const int AidMeqSolver_int = -1401;
#endif
#ifndef _defined_id_AidMeqSqr
#define _defined_id_AidMeqSqr 1
const DMI::AtomicID AidMeqSqr(-1458);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Sqr.h:30
const int AidMeqSqr_int = -1458;
#endif
#ifndef _defined_id_AidMeqSqrt
#define _defined_id_AidMeqSqrt 1
const DMI::AtomicID AidMeqSqrt(-1408);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Sqrt.h:30
const int AidMeqSqrt_int = -1408;
#endif
#ifndef _defined_id_AidMeqStdDev
#define _defined_id_AidMeqStdDev 1
const DMI::AtomicID AidMeqStdDev(-1491);          // from /home/oms/LOFAR/Timba/MeqNodes/src/StdDev.h:29
const int AidMeqStdDev_int = -1491;
#endif
#ifndef _defined_id_AidMeqStripper
#define _defined_id_AidMeqStripper 1
const DMI::AtomicID AidMeqStripper(-1409);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Stripper.h:30
const int AidMeqStripper_int = -1409;
#endif
#ifndef _defined_id_AidMeqSubtract
#define _defined_id_AidMeqSubtract 1
const DMI::AtomicID AidMeqSubtract(-1461);        // from /home/oms/LOFAR/Timba/MeqNodes/src/Subtract.h:30
const int AidMeqSubtract_int = -1461;
#endif
#ifndef _defined_id_AidMeqSum
#define _defined_id_AidMeqSum 1
const DMI::AtomicID AidMeqSum(-1499);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Sum.h:29
const int AidMeqSum_int = -1499;
#endif
#ifndef _defined_id_AidMeqTan
#define _defined_id_AidMeqTan 1
const DMI::AtomicID AidMeqTan(-1417);             // from /home/oms/LOFAR/Timba/MeqNodes/src/Tan.h:29
const int AidMeqTan_int = -1417;
#endif
#ifndef _defined_id_AidMeqTanh
#define _defined_id_AidMeqTanh 1
const DMI::AtomicID AidMeqTanh(-1450);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Tanh.h:29
const int AidMeqTanh_int = -1450;
#endif
#ifndef _defined_id_AidMeqTime
#define _defined_id_AidMeqTime 1
const DMI::AtomicID AidMeqTime(-1451);            // from /home/oms/LOFAR/Timba/MeqNodes/src/Time.h:30
const int AidMeqTime_int = -1451;
#endif
#ifndef _defined_id_AidMeqToComplex
#define _defined_id_AidMeqToComplex 1
const DMI::AtomicID AidMeqToComplex(-1413);       // from /home/oms/LOFAR/Timba/MeqNodes/src/ToComplex.h:30
const int AidMeqToComplex_int = -1413;
#endif
#ifndef _defined_id_AidMeqTranspose
#define _defined_id_AidMeqTranspose 1
const DMI::AtomicID AidMeqTranspose(-1521);       // from /home/oms/LOFAR/Timba/MeqNodes/src/Transpose.h:31
const int AidMeqTranspose_int = -1521;
#endif
#ifndef _defined_id_AidMeqUVBrick
#define _defined_id_AidMeqUVBrick 1
const DMI::AtomicID AidMeqUVBrick(-1505);         // from /home/mevius/LOFAR/Timba/MeqNodes/src/UVBrick.h:31
const int AidMeqUVBrick_int = -1505;
#endif
#ifndef _defined_id_AidMeqUVInterpol
#define _defined_id_AidMeqUVInterpol 1
const DMI::AtomicID AidMeqUVInterpol(-1508);      // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:33
const int AidMeqUVInterpol_int = -1508;
#endif
#ifndef _defined_id_AidMeqUVW
#define _defined_id_AidMeqUVW 1
const DMI::AtomicID AidMeqUVW(-1421);             // from /home/oms/LOFAR/Timba/MeqNodes/src/UVW.h:31
const int AidMeqUVW_int = -1421;
#endif
#ifndef _defined_id_AidMeqVisPhaseShift
#define _defined_id_AidMeqVisPhaseShift 1
const DMI::AtomicID AidMeqVisPhaseShift(-1517);   // from /home/brentjens/LOFAR/Timba/MeqNodes/src/VisPhaseShift.h:31
const int AidMeqVisPhaseShift_int = -1517;
#endif
#ifndef _defined_id_AidMeqWMean
#define _defined_id_AidMeqWMean 1
const DMI::AtomicID AidMeqWMean(-1504);           // from /home/mevius/LOFAR/Timba/MeqNodes/src/WMean.h:30
const int AidMeqWMean_int = -1504;
#endif
#ifndef _defined_id_AidMeqWSum
#define _defined_id_AidMeqWSum 1
const DMI::AtomicID AidMeqWSum(-1502);            // from /home/mevius/LOFAR/Timba/MeqNodes/src/WSum.h:30
const int AidMeqWSum_int = -1502;
#endif
#ifndef _defined_id_AidMeqZeroFlagger
#define _defined_id_AidMeqZeroFlagger 1
const DMI::AtomicID AidMeqZeroFlagger(-1434);     // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:32
const int AidMeqZeroFlagger_int = -1434;
#endif
#ifndef _defined_id_AidMethod
#define _defined_id_AidMethod 1
const DMI::AtomicID AidMethod(-1550);             // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidMethod_int = -1550;
#endif
#ifndef _defined_id_AidMulti
#define _defined_id_AidMulti 1
const DMI::AtomicID AidMulti(-1518);              // from /home/oms/LOFAR/Timba/MeqNodes/src/Selector.h:33
const int AidMulti_int = -1518;
#endif
#ifndef _defined_id_AidNE
#define _defined_id_AidNE 1
const DMI::AtomicID AidNE(-1381);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidNE_int = -1381;
#endif
#ifndef _defined_id_AidObservatory
#define _defined_id_AidObservatory 1
const DMI::AtomicID AidObservatory(-1554);        // from /home/twillis/LOFAR/Timba/MeqNodes/src/AzEl.h:33
const int AidObservatory_int = -1554;
#endif
#ifndef _defined_id_AidOnly
#define _defined_id_AidOnly 1
const DMI::AtomicID AidOnly(-1390);               // from /home/oms/LOFAR/Timba/MeqNodes/src/ReqSeq.h:32
const int AidOnly_int = -1390;
#endif
#ifndef _defined_id_AidOper
#define _defined_id_AidOper 1
const DMI::AtomicID AidOper(-1453);               // from /home/oms/LOFAR/Timba/MeqNodes/src/ZeroFlagger.h:33
const int AidOper_int = -1453;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const DMI::AtomicID AidOutput(-1241);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidOutput_int = -1241;
#endif
#ifndef _defined_id_AidPlot
#define _defined_id_AidPlot 1
const DMI::AtomicID AidPlot(-1432);               // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidPlot_int = -1432;
#endif
#ifndef _defined_id_AidProfile
#define _defined_id_AidProfile 1
const DMI::AtomicID AidProfile(-1433);            // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidProfile_int = -1433;
#endif
#ifndef _defined_id_AidRA
#define _defined_id_AidRA 1
const DMI::AtomicID AidRA(-1435);                 // from /home/oms/LOFAR/Timba/MeqNodes/src/UVW.h:32
const int AidRA_int = -1435;
#endif
#ifndef _defined_id_AidRADec
#define _defined_id_AidRADec 1
const DMI::AtomicID AidRADec(-1566);              // from /home/oms/LOFAR/Timba/MeqNodes/src/UVW.h:32
const int AidRADec_int = -1566;
#endif
#ifndef _defined_id_AidResult
#define _defined_id_AidResult 1
const DMI::AtomicID AidResult(-1242);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:21
const int AidResult_int = -1242;
#endif
#ifndef _defined_id_AidSize
#define _defined_id_AidSize 1
const DMI::AtomicID AidSize(-1255);               // from /home/oms/LOFAR/Timba/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidSize_int = -1255;
#endif
#ifndef _defined_id_AidSkeleton
#define _defined_id_AidSkeleton 1
const DMI::AtomicID AidSkeleton(-1389);           // from /home/oms/LOFAR/Timba/MeqNodes/src/DataConcat.h:31
const int AidSkeleton_int = -1389;
#endif
#ifndef _defined_id_AidSolutions
#define _defined_id_AidSolutions 1
const DMI::AtomicID AidSolutions(-1514);          // from /home/oms/LOFAR/Timba/MeqNodes/src/Solver.h:32
const int AidSolutions_int = -1514;
#endif
#ifndef _defined_id_AidSolve
#define _defined_id_AidSolve 1
const DMI::AtomicID AidSolve(-1374);              // from /home/oms/LOFAR/Timba/MEQ/src/MeqVocabulary.h:31
const int AidSolve_int = -1374;
#endif
#ifndef _defined_id_AidStdDev
#define _defined_id_AidStdDev 1
const DMI::AtomicID AidStdDev(-1350);             // from /home/oms/LOFAR/Timba/MEQ/src/MeqVocabulary.h:40
const int AidStdDev_int = -1350;
#endif
#ifndef _defined_id_AidStyle
#define _defined_id_AidStyle 1
const DMI::AtomicID AidStyle(-1406);              // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidStyle_int = -1406;
#endif
#ifndef _defined_id_AidTile
#define _defined_id_AidTile 1
const DMI::AtomicID AidTile(-1232);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:11
const int AidTile_int = -1232;
#endif
#ifndef _defined_id_AidTop
#define _defined_id_AidTop 1
const DMI::AtomicID AidTop(-1400);                // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidTop_int = -1400;
#endif
#ifndef _defined_id_AidUVCurvature
#define _defined_id_AidUVCurvature 1
const DMI::AtomicID AidUVCurvature(-1540);        // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidUVCurvature_int = -1540;
#endif
#ifndef _defined_id_AidUVDelta
#define _defined_id_AidUVDelta 1
const DMI::AtomicID AidUVDelta(-1526);            // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidUVDelta_int = -1526;
#endif
#ifndef _defined_id_AidUVImage
#define _defined_id_AidUVImage 1
const DMI::AtomicID AidUVImage(-1527);            // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidUVImage_int = -1527;
#endif
#ifndef _defined_id_AidUVInterpol
#define _defined_id_AidUVInterpol 1
const DMI::AtomicID AidUVInterpol(-1523);         // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidUVInterpol_int = -1523;
#endif
#ifndef _defined_id_AidUVW
#define _defined_id_AidUVW 1
const DMI::AtomicID AidUVW(-1123);                // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:28
const int AidUVW_int = -1123;
#endif
#ifndef _defined_id_AidUVZ
#define _defined_id_AidUVZ 1
const DMI::AtomicID AidUVZ(-1528);                // from /home/rnijboer/LOFAR/Timba/MeqNodes/src/UVInterpol.h:34
const int AidUVZ_int = -1528;
#endif
#ifndef _defined_id_AidVisu
#define _defined_id_AidVisu 1
const DMI::AtomicID AidVisu(-1440);               // from /home/oms/LOFAR/Timba/MeqNodes/src/DataCollect.h:30
const int AidVisu_int = -1440;
#endif
#ifndef _defined_id_AidWeights
#define _defined_id_AidWeights 1
const DMI::AtomicID AidWeights(-1285);            // from /home/oms/LOFAR/Timba/MEQ/src/MeqVocabulary.h:33
const int AidWeights_int = -1285;
#endif
#ifndef _defined_id_AidXX
#define _defined_id_AidXX 1
const DMI::AtomicID AidXX(-1115);                 // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidXX_int = -1115;
#endif
#ifndef _defined_id_AidXY
#define _defined_id_AidXY 1
const DMI::AtomicID AidXY(-1170);                 // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidXY_int = -1170;
#endif
#ifndef _defined_id_AidXYZ
#define _defined_id_AidXYZ 1
const DMI::AtomicID AidXYZ(-1567);                // from /home/oms/LOFAR/Timba/MeqNodes/src/UVW.h:32
const int AidXYZ_int = -1567;
#endif
#ifndef _defined_id_AidYX
#define _defined_id_AidYX 1
const DMI::AtomicID AidYX(-1175);                 // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidYX_int = -1175;
#endif
#ifndef _defined_id_AidYY
#define _defined_id_AidYY 1
const DMI::AtomicID AidYY(-1118);                 // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidYY_int = -1118;
#endif


#endif
