//# Compounder.h: modifies request resolutions
//#
//# Copyright (C) 2003
//# ASTRON (Netherlands Foundation for Research in Astronomy)
//# P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
//#
//# This program is free software; you can redistribute it and/or modify
//# it under the terms of the GNU General Public License as published by
//# the Free Software Foundation; either version 2 of the License, or
//# (at your option) any later version.
//#
//# This program is distributed in the hope that it will be useful,
//# but WITHOUT ANY WARRANTY; without even the implied warranty of
//# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//# GNU General Public License for more details.
//#
//# You should have received a copy of the GNU General Public License
//# along with this program; if not, write to the Free Software
//# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//#
//# $Id$

#ifndef MEQNODES_COMPOUNDER_H
#define MEQNODES_COMPOUNDER_H
    
#include <MEQ/Node.h>
#include <MEQ/Cells.h>
#include <MEQ/AID-Meq.h>

#include <MeqNodes/TID-MeqNodes.h>
#pragma aidgroup MeqNodes
#pragma types #Meq::Compounder 
#pragma aid Mode Common Axes

// The comments below are used to automatically generate a default
// init-record for the class 

//defrec begin MeqCompounder
//  Child 0: defines the grid for interpolation
//  Child 1: defines the function for interpolation
//  This nodes interpolates the result returned by child 1 according
//  to the gride defined by child 0.
//
//field: mode
//  mode 1 (sequential): passes the original requser to child 0, recreates a requset for child 1 according to the result returned by child 0.
//  mode 2 (parallel): passes the same requset to both children
//field: common_axes []
//  a vector which gives the axes returned by the grid child that is given to the function. Axes names can be characters like 'L','M' etc
//defrec end

namespace Meq {    

//##ModelId=400E530400A3
class Compounder : public Node
{
public:
    //##ModelId=400E5355029C
  Compounder();

    //##ModelId=400E5355029D
  virtual ~Compounder();

	virtual TypeId objectType() const
	{ return TpMeqCompounder; }


protected:
  virtual void setStateImpl (DMI::Record::Ref &rec,bool initializing);

  virtual int pollChildren (Result::Ref &resref,
                            std::vector<Result::Ref> &childres,
                            const Request &req);
    
  virtual int getResult (Result::Ref &resref, 
                         const std::vector<Result::Ref> &childres,
                         const Request &req,bool newreq);
  
private:

  
  std::vector<HIID> comm_axes_;
	int mode_;

  // symdeps generated by Compounder
  vector<HIID>    res_symdeps_;
  int             res_depmask_;
  vector<HIID>    seq_symdeps_;
  int             seq_depmask_;
  
  // if =0, res depmask is incremented
  // if !=0, res depmask is assigned with this index directly
  int   res_index_;

	//for caching result in pollChildren()
	Result::Ref result_;
	int result_code_;
};

} // namespace Meq


#endif
