//
//% $Id$ 
//
//
// Copyright (C) 2002-2007
// The MeqTree Foundation & 
// ASTRON (Netherlands Foundation for Research in Astronomy)
// P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>,
// or write to the Free Software Foundation, Inc., 
// 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

      #ifndef AID_OCTOPUSSY_h
      #define AID_OCTOPUSSY_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_OCTOPUSSY ();

#ifndef _defined_id_AidAdd
#define _defined_id_AidAdd 1
const DMI::AtomicID AidAdd(-1088);                // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidAdd_int = -1088;
#endif
#ifndef _defined_id_AidArgv
#define _defined_id_AidArgv 1
const DMI::AtomicID AidArgv(-1076);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Dispatcher.h:20
const int AidArgv_int = -1076;
#endif
#ifndef _defined_id_AidBind
#define _defined_id_AidBind 1
const DMI::AtomicID AidBind(-1079);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidBind_int = -1079;
#endif
#ifndef _defined_id_AidBound
#define _defined_id_AidBound 1
const DMI::AtomicID AidBound(-1046);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidBound_int = -1046;
#endif
#ifndef _defined_id_AidBroadcast
#define _defined_id_AidBroadcast 1
const DMI::AtomicID AidBroadcast(-1545);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/StatusMonitorWP.h:7
const int AidBroadcast_int = -1545;
#endif
#ifndef _defined_id_AidBye
#define _defined_id_AidBye 1
const DMI::AtomicID AidBye(-1090);                // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:25
const int AidBye_int = -1090;
#endif
#ifndef _defined_id_AidClient
#define _defined_id_AidClient 1
const DMI::AtomicID AidClient(-1097);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidClient_int = -1097;
#endif
#ifndef _defined_id_AidConnected
#define _defined_id_AidConnected 1
const DMI::AtomicID AidConnected(-1094);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidConnected_int = -1094;
#endif
#ifndef _defined_id_AidConnection
#define _defined_id_AidConnection 1
const DMI::AtomicID AidConnection(-1087);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidConnection_int = -1087;
#endif
#ifndef _defined_id_AidConnectionMgrWP
#define _defined_id_AidConnectionMgrWP 1
const DMI::AtomicID AidConnectionMgrWP(-1068);    // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:23
const int AidConnectionMgrWP_int = -1068;
#endif
#ifndef _defined_id_AidDispatcher
#define _defined_id_AidDispatcher 1
const DMI::AtomicID AidDispatcher(-1086);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MsgAddress.h:9
const int AidDispatcher_int = -1086;
#endif
#ifndef _defined_id_AidDown
#define _defined_id_AidDown 1
const DMI::AtomicID AidDown(-1077);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidDown_int = -1077;
#endif
#ifndef _defined_id_AidDuplicate
#define _defined_id_AidDuplicate 1
const DMI::AtomicID AidDuplicate(-1075);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidDuplicate_int = -1075;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const DMI::AtomicID AidError(-1056);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidError_int = -1056;
#endif
#ifndef _defined_id_AidEvent
#define _defined_id_AidEvent 1
const DMI::AtomicID AidEvent(-1080);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidEvent_int = -1080;
#endif
#ifndef _defined_id_AidFailConnect
#define _defined_id_AidFailConnect 1
const DMI::AtomicID AidFailConnect(-1052);        // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidFailConnect_int = -1052;
#endif
#ifndef _defined_id_AidFatal
#define _defined_id_AidFatal 1
const DMI::AtomicID AidFatal(-1062);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidFatal_int = -1062;
#endif
#ifndef _defined_id_AidGW
#define _defined_id_AidGW 1
const DMI::AtomicID AidGW(-1069);                 // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidGW_int = -1069;
#endif
#ifndef _defined_id_AidGWClientWP
#define _defined_id_AidGWClientWP 1
const DMI::AtomicID AidGWClientWP(-1035);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:23
const int AidGWClientWP_int = -1035;
#endif
#ifndef _defined_id_AidGWServerWP
#define _defined_id_AidGWServerWP 1
const DMI::AtomicID AidGWServerWP(-1066);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:23
const int AidGWServerWP_int = -1066;
#endif
#ifndef _defined_id_AidGateway
#define _defined_id_AidGateway 1
const DMI::AtomicID AidGateway(-1089);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWServerWP.h:10
const int AidGateway_int = -1089;
#endif
#ifndef _defined_id_AidGatewayWP
#define _defined_id_AidGatewayWP 1
const DMI::AtomicID AidGatewayWP(-1071);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:23
const int AidGatewayWP_int = -1071;
#endif
#ifndef _defined_id_AidHeartbeat
#define _defined_id_AidHeartbeat 1
const DMI::AtomicID AidHeartbeat(-1063);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MTGatewayWP.h:16
const int AidHeartbeat_int = -1063;
#endif
#ifndef _defined_id_AidHello
#define _defined_id_AidHello 1
const DMI::AtomicID AidHello(-1048);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:25
const int AidHello_int = -1048;
#endif
#ifndef _defined_id_AidHost
#define _defined_id_AidHost 1
const DMI::AtomicID AidHost(-1096);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidHost_int = -1096;
#endif
#ifndef _defined_id_AidHosts
#define _defined_id_AidHosts 1
const DMI::AtomicID AidHosts(-1065);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidHosts_int = -1065;
#endif
#ifndef _defined_id_AidIndex
#define _defined_id_AidIndex 1
const DMI::AtomicID AidIndex(-1061);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Message.h:30
const int AidIndex_int = -1061;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const DMI::AtomicID AidInit(-1038);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MTGatewayWP.h:16
const int AidInit_int = -1038;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const DMI::AtomicID AidInput(-1036);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidInput_int = -1036;
#endif
#ifndef _defined_id_AidLevel
#define _defined_id_AidLevel 1
const DMI::AtomicID AidLevel(-1047);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/LoggerWP.h:9
const int AidLevel_int = -1047;
#endif
#ifndef _defined_id_AidList
#define _defined_id_AidList 1
const DMI::AtomicID AidList(-1040);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidList_int = -1040;
#endif
#ifndef _defined_id_AidListenerWP
#define _defined_id_AidListenerWP 1
const DMI::AtomicID AidListenerWP(-1492);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/ListenerWP.h:9
const int AidListenerWP_int = -1492;
#endif
#ifndef _defined_id_AidLocal
#define _defined_id_AidLocal 1
const DMI::AtomicID AidLocal(-1053);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MsgAddress.h:9
const int AidLocal_int = -1053;
#endif
#ifndef _defined_id_AidLogDebug
#define _defined_id_AidLogDebug 1
const DMI::AtomicID AidLogDebug(-1058);           // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidLogDebug_int = -1058;
#endif
#ifndef _defined_id_AidLogError
#define _defined_id_AidLogError 1
const DMI::AtomicID AidLogError(-1093);           // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidLogError_int = -1093;
#endif
#ifndef _defined_id_AidLogFatal
#define _defined_id_AidLogFatal 1
const DMI::AtomicID AidLogFatal(-1092);           // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidLogFatal_int = -1092;
#endif
#ifndef _defined_id_AidLogNormal
#define _defined_id_AidLogNormal 1
const DMI::AtomicID AidLogNormal(-1095);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidLogNormal_int = -1095;
#endif
#ifndef _defined_id_AidLogWarning
#define _defined_id_AidLogWarning 1
const DMI::AtomicID AidLogWarning(-1050);         // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidLogWarning_int = -1050;
#endif
#ifndef _defined_id_AidLoggerWP
#define _defined_id_AidLoggerWP 1
const DMI::AtomicID AidLoggerWP(-1037);           // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/LoggerWP.h:9
const int AidLoggerWP_int = -1037;
#endif
#ifndef _defined_id_AidMax
#define _defined_id_AidMax 1
const DMI::AtomicID AidMax(-1070);                // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/LoggerWP.h:9
const int AidMax_int = -1070;
#endif
#ifndef _defined_id_AidMsgLog
#define _defined_id_AidMsgLog 1
const DMI::AtomicID AidMsgLog(-1043);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WorkProcess.h:30
const int AidMsgLog_int = -1043;
#endif
#ifndef _defined_id_AidNetwork
#define _defined_id_AidNetwork 1
const DMI::AtomicID AidNetwork(-1067);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidNetwork_int = -1067;
#endif
#ifndef _defined_id_AidOctopussyMessage
#define _defined_id_AidOctopussyMessage 1
const DMI::AtomicID AidOctopussyMessage(-1049);   // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Message.h:29
const int AidOctopussyMessage_int = -1049;
#endif
#ifndef _defined_id_AidOpen
#define _defined_id_AidOpen 1
const DMI::AtomicID AidOpen(-1045);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidOpen_int = -1045;
#endif
#ifndef _defined_id_AidPeers
#define _defined_id_AidPeers 1
const DMI::AtomicID AidPeers(-1051);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidPeers_int = -1051;
#endif
#ifndef _defined_id_AidPeriod
#define _defined_id_AidPeriod 1
const DMI::AtomicID AidPeriod(-1546);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/StatusMonitorWP.h:7
const int AidPeriod_int = -1546;
#endif
#ifndef _defined_id_AidPort
#define _defined_id_AidPort 1
const DMI::AtomicID AidPort(-1081);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidPort_int = -1081;
#endif
#ifndef _defined_id_AidPorts
#define _defined_id_AidPorts 1
const DMI::AtomicID AidPorts(-1083);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidPorts_int = -1083;
#endif
#ifndef _defined_id_AidProcess
#define _defined_id_AidProcess 1
const DMI::AtomicID AidProcess(-1104);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/test/EchoWP.h:11
const int AidProcess_int = -1104;
#endif
#ifndef _defined_id_AidPublish
#define _defined_id_AidPublish 1
const DMI::AtomicID AidPublish(-1060);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MsgAddress.h:9
const int AidPublish_int = -1060;
#endif
#ifndef _defined_id_AidReconnect
#define _defined_id_AidReconnect 1
const DMI::AtomicID AidReconnect(-1044);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidReconnect_int = -1044;
#endif
#ifndef _defined_id_AidReflect
#define _defined_id_AidReflect 1
const DMI::AtomicID AidReflect(-1064);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/ReflectorWP.h:7
const int AidReflect_int = -1064;
#endif
#ifndef _defined_id_AidReflectorWP
#define _defined_id_AidReflectorWP 1
const DMI::AtomicID AidReflectorWP(-1082);        // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/ReflectorWP.h:7
const int AidReflectorWP_int = -1082;
#endif
#ifndef _defined_id_AidRemote
#define _defined_id_AidRemote 1
const DMI::AtomicID AidRemote(-1073);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidRemote_int = -1073;
#endif
#ifndef _defined_id_AidReopen
#define _defined_id_AidReopen 1
const DMI::AtomicID AidReopen(-1057);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/GWClientWP.h:11
const int AidReopen_int = -1057;
#endif
#ifndef _defined_id_AidRequest
#define _defined_id_AidRequest 1
const DMI::AtomicID AidRequest(-1226);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:21
const int AidRequest_int = -1226;
#endif
#ifndef _defined_id_AidScope
#define _defined_id_AidScope 1
const DMI::AtomicID AidScope(-1041);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/LoggerWP.h:9
const int AidScope_int = -1041;
#endif
#ifndef _defined_id_AidServer
#define _defined_id_AidServer 1
const DMI::AtomicID AidServer(-1078);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidServer_int = -1078;
#endif
#ifndef _defined_id_AidSet
#define _defined_id_AidSet 1
const DMI::AtomicID AidSet(-1272);                // from /home/oms/LOFAR/Timba/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidSet_int = -1272;
#endif
#ifndef _defined_id_AidSignal
#define _defined_id_AidSignal 1
const DMI::AtomicID AidSignal(-1059);             // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidSignal_int = -1059;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const DMI::AtomicID AidState(-1072);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:25
const int AidState_int = -1072;
#endif
#ifndef _defined_id_AidStatus
#define _defined_id_AidStatus 1
const DMI::AtomicID AidStatus(-1209);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:21
const int AidStatus_int = -1209;
#endif
#ifndef _defined_id_AidStatusMonitorWP
#define _defined_id_AidStatusMonitorWP 1
const DMI::AtomicID AidStatusMonitorWP(-1547);    // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/StatusMonitorWP.h:7
const int AidStatusMonitorWP_int = -1547;
#endif
#ifndef _defined_id_AidSubscribe
#define _defined_id_AidSubscribe 1
const DMI::AtomicID AidSubscribe(-1042);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidSubscribe_int = -1042;
#endif
#ifndef _defined_id_AidSubscriptions
#define _defined_id_AidSubscriptions 1
const DMI::AtomicID AidSubscriptions(-1074);      // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MTGatewayWP.h:16
const int AidSubscriptions_int = -1074;
#endif
#ifndef _defined_id_AidText
#define _defined_id_AidText 1
const DMI::AtomicID AidText(-1055);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Message.h:30
const int AidText_int = -1055;
#endif
#ifndef _defined_id_AidTimeout
#define _defined_id_AidTimeout 1
const DMI::AtomicID AidTimeout(-1039);            // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidTimeout_int = -1039;
#endif
#ifndef _defined_id_AidTimestamp
#define _defined_id_AidTimestamp 1
const DMI::AtomicID AidTimestamp(-1054);          // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:23
const int AidTimestamp_int = -1054;
#endif
#ifndef _defined_id_AidType
#define _defined_id_AidType 1
const DMI::AtomicID AidType(-1085);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidType_int = -1085;
#endif
#ifndef _defined_id_AidUp
#define _defined_id_AidUp 1
const DMI::AtomicID AidUp(-1091);                 // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidUp_int = -1091;
#endif
#ifndef _defined_id_AidWP
#define _defined_id_AidWP 1
const DMI::AtomicID AidWP(-1084);                 // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidWP_int = -1084;
#endif


#endif
