      #ifndef TID_OCTOPUSSY_h
      #define TID_OCTOPUSSY_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/TypeId.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_OCTOPUSSY ();

#ifndef _defined_id_TpMessage
#define _defined_id_TpMessage 1
const TypeId TpMessage(-446);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:38
const int TpMessage_int = -446;
class Message;
#endif
#ifndef _defined_id_TpTimestamp
#define _defined_id_TpTimestamp 1
const TypeId TpTimestamp(-85);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:54
const int TpTimestamp_int = -85;
class Timestamp;
#endif


#endif
