      #ifndef AID_MeqGen_h
      #define AID_MeqGen_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MeqGen ();

#ifndef _defined_id_AidmeqCompare
#define _defined_id_AidmeqCompare 1
const AtomicID AidmeqCompare(-1370);              // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqCompare.h:14
const int AidmeqCompare_int = -1370;
#endif
#ifndef _defined_id_AidmeqCopy
#define _defined_id_AidmeqCopy 1
const AtomicID AidmeqCopy(-1374);                 // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqCopy.h:14
const int AidmeqCopy_int = -1374;
#endif
#ifndef _defined_id_AidmeqDFT_GVD
#define _defined_id_AidmeqDFT_GVD 1
const AtomicID AidmeqDFT_GVD(-1371);              // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqDFT_GVD.h:14
const int AidmeqDFT_GVD_int = -1371;
#endif
#ifndef _defined_id_AidmeqFlagger
#define _defined_id_AidmeqFlagger 1
const AtomicID AidmeqFlagger(-1372);              // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqFlagger.h:14
const int AidmeqFlagger_int = -1372;
#endif
#ifndef _defined_id_AidmeqShiftPhaseCentre
#define _defined_id_AidmeqShiftPhaseCentre 1
const AtomicID AidmeqShiftPhaseCentre(-1373);     // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqShiftPhaseCentre.h:14
const int AidmeqShiftPhaseCentre_int = -1373;
#endif


#endif
