    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
#include "meqFlagger.h"
BlockableObject * __construct_meqFlagger (int n) { return n>0 ? new meq::Flagger [n] : new meq::Flagger; }
#include "meqCopy.h"
BlockableObject * __construct_meqCopy (int n) { return n>0 ? new meq::Copy [n] : new meq::Copy; }
#include "meqCompare.h"
BlockableObject * __construct_meqCompare (int n) { return n>0 ? new meq::Compare [n] : new meq::Compare; }
#include "meqDFT_GVD.h"
BlockableObject * __construct_meqDFT_GVD (int n) { return n>0 ? new meq::DFT_GVD [n] : new meq::DFT_GVD; }
#include "meqShiftPhaseCentre.h"
BlockableObject * __construct_meqShiftPhaseCentre (int n) { return n>0 ? new meq::ShiftPhaseCentre [n] : new meq::ShiftPhaseCentre; }
  
    int aidRegistry_MeqGen ()
    {
      static int res = 

        AtomicID::registerId(-1372,"meqFlagger")+
        TypeInfoReg::addToRegistry(-1372,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1372,__construct_meqFlagger)+
        AtomicID::registerId(-1374,"meqCopy")+
        TypeInfoReg::addToRegistry(-1374,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1374,__construct_meqCopy)+
        AtomicID::registerId(-1370,"meqCompare")+
        TypeInfoReg::addToRegistry(-1370,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1370,__construct_meqCompare)+
        AtomicID::registerId(-1371,"meqDFT_GVD")+
        TypeInfoReg::addToRegistry(-1371,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1371,__construct_meqDFT_GVD)+
        AtomicID::registerId(-1373,"meqShiftPhaseCentre")+
        TypeInfoReg::addToRegistry(-1373,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1373,__construct_meqShiftPhaseCentre)+
    0;
    return res;
  }
  
  int __dum_call_registries_for_MeqGen = aidRegistry_MeqGen();

