      #ifndef TID_MeqGen_h
      #define TID_MeqGen_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/TypeId.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_MeqGen ();

#ifndef _defined_id_TpmeqCopy
#define _defined_id_TpmeqCopy 1
const TypeId TpmeqCopy(-1257);                    // from /home/oms/LOFAR/CEP/CPA/PSS4/MeqGen/src/meqCopy.h:14
const int TpmeqCopy_int = -1257;
namespace meq { class Copy; };
            template<>
            class DMIBaseTypeTraits<meq::Copy> : public TypeTraits<meq::Copy>
            {
              public:
              enum { isContainable = true };
              enum { typeId = TpmeqCopy_int };
              enum { TypeCategory = TypeCategories::DYNAMIC };
              enum { ParamByRef = true, ReturnByRef = true };
              typedef const meq::Copy & ContainerReturnType;
              typedef const meq::Copy & ContainerParamType;
            };
#endif


#endif
