#!/bin/sh
if test $# != 1; then
  echo usage: bootstrap autoconf_share_dir
fi
set -x
aclocal -I $1 \
&& libtoolize --force --copy \
&& autoheader \
&& automake --foreign --add-missing --copy \
&& autoconf

