#!/bin/sh

# bootstrap: bootstrap of a package build
#
#  Copyright (C) 2002
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$


if test $# != 1; then
  echo usage: bootstrap autoconf_share_dir
  exit 1
fi
set -x

# Make symlinks for ease of use.
\rm -f autoconf_share lofarconf
ln -s $1 autoconf_share
ln -s $1/lofarconf lofarconf

# Initialize auto tools
aclocal -I $1 \
&& libtoolize --force --copy \
&& autoheader \
&& automake --foreign --add-missing --copy \
&& autoconf

