#!/bin/sh

# compiletool: wrapper for CC, CXX and LIBTOOL to log the compile command to file
#
#  Copyright (C) 2002
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$

toolname=$1
shift

case $toolname in
    CC)
    ;;
    CXX)
    ;;
    LIBTOOL)
      # find -o part of command and store next argument as target name
      linkmode=`echo $* | sed -e 's/.*\(--mode=link\).*/\1/'`;
      if [ "$linkmode" = "--mode=link" ]; then
        outputname=`echo $* | sed -e 's/.* \+-o \+\([^ ]\+\).*/\1/'`;
	outputext=`echo $outputname | cut -d. -f2`;

	# exclude .lo objects because we're only interested in libraries and binaries
	if test "$outputext" != "lo"; then
	  # log compiler command
	  echo "$@" > $outputname.compile.log
	fi
      fi
    ;;
    *)
      echo "compiletool: error: first argument should be one of CC, CXX or LIBTOOL"
      exit 1;
    ;;
esac

# execute actual compiler command
"$@"
