#!/bin/sh

if test $# != 1; then
  echo usage: makeshadow ~gvd/sim/LOFAR/BaseSim
  exit 1
fi

# Get basename part from the directory being linked to.
# That directory should be something like .../LOFAR/BaseSim.
bldir=`basename $1`
dldir=`dirname $1`
bdldir=`basename $dldir`
if [ $bdldir != "LOFAR" ]
then
  echo "Directory being linked to must be like something/LOFAR/BaseSim"
  exit 1
fi

dirname="$bldir"

# Check if the user is in a LOFAR directory.
cdir=`pwd`
bcdir=`basename $cdir`
if [ "$bcdir" != "LOFAR" ]
then
  echo "Working directory should be the LOFAR subdirectory"
  exit 1
fi

# Check if (expanded) target and source directory are not the same.
edldir=`cd $dldir && pwd`
if [ "$cdir" = "$edldir" ]
then
  echo "Working and shadowed directory are the same"
  exit 1
fi

# Create autoconf_share if not present yet.
if test ! -d autoconf_share
then
  echo "Creating autoconf_share"
  mkdir autoconf_share
  cd autoconf_share
  for INFIL in $dldir/autoconf_share/*
  do
    case $INFIL in
    */CVS)
      ;;
    *~)
      ;;
    *)
      ln -s $INFIL `basename $INFIL`
      echo "  created symlink to $INFIL"
    esac
  done
  cd ..
fi

# Ask if the directory has to be deleted if it already exists.
update=0
if [ -d $dirname ]
then
  echo "Shadow tree $dirname already exists"
  if [ "`echo -n X`" = "X" ] ; then
    echo -n "Delete it? (y/n) [n]: "
  else
    echo "Delete it? (y/n) [n]: \c"
  fi
  read ANSWER
  if test "$ANSWER" = "y"  -o  "$ANSWER+ = "Y" \
      -o  "$ANSWER" = "yes"  -o  "$ANSWER+ = "YES"
  then
    \rm -rf $dirname
  else
    if [ "`echo -n X`" = "X" ] ; then
      echo -n "Update it? (y/n) [n]: "
    else
      echo "Update it? (y/n) [n]: \c"
    fi
    read ANSWER
    if test "$ANSWER" = "y"  -o  "$ANSWER+ = "Y" \
        -o  "$ANSWER" = "yes"  -o  "$ANSWER+ = "YES"
    then
      update=1
    else
      exit 1
    fi
  fi
fi

# Create the directory (if needed).
# Make symlinks in it for the essential files
if [ $update = 0 ]
then
  echo "Creating $dirname"
  mkdir $dirname
fi
cd $dirname
for INFIL in bootstrap configure.in Makefile.am
do
  if test ! -f $INFIL
  then
    ln -s $1/$INFIL $INFIL
    echo "  created symlink to $1/$INFIL"
  fi
done

# Shadow subdirectories containing sources.
for INFIL in $1/*
do
  if [ -d $INFIL ]
  then
    if [ -f $INFIL/Makefile.am ]
    then
      dirname=`basename $INFIL`
      if test $update = 0  -o  ! -d $dirname
      then
        mkdir $dirname
      fi
      `dirname $0`/makeshadowcopy $update $INFIL $dirname
    fi
  fi
done
