#!/bin/sh

# makeshadowcopy: helper script for makeshadow
#
#  Copyright (C) 2002
#  ASTRON (Netherlands Foundation for Research in Astronomy)
#  P.O.Box 2, 7990 AA Dwingeloo, The Netherlands, seg@astron.nl
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#  $Id$


echo "  shadowing $2"
cd $3
for INFIL in $2/*
do
  if [ -d $INFIL ]
  then
    if [ -f $INFIL/Makefile.am ]
    then
      dirname=`basename $INFIL`
      if test $1 = 0  -o  ! -d $dirname
      then
        mkdir $dirname
      fi
      $0 $1 $INFIL $dirname
    fi
  else
    case $INFIL in
    */CVS)
      ;;
    *~)
      ;;
    */Makefile.in)
      ;;
    *)
      nm=`basename $INFIL`
      if test ! -f $nm
      then
       ln -s $INFIL $nm
      fi
    esac
  fi
done
