#!/bin/sh

#
# Find out where configure script is
#
curdir=`pwd`
top_srcdir=`expr "$curdir" : "\(.*/BaseSim/\).*"`

#
# Choose appropriate compiler for each platform
#
case `uname -s` in
  Linux) $top_srcdir/configure $* ;;
  SunOS) CC=/local/gcc-2.95.3/bin/gcc CXX=/local/gcc-2.95.3/bin/g++ $top_srcdir/configure $* ;;
  HP-UX) CC=/local/gcc-2.95.3/bin/gcc CXX=/local/gcc-2.95.3/bin/g++ $top_srcdir/configure $* ;;
  *)     $top_srcdir/configure $* ;;
esac
