    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
    #ifndef _TypeIter_MeqServer_h
    #define _TypeIter_MeqServer_h 1



#define DoForAllOtherTypes_MeqServer(Do,arg,separator) \
        

#define DoForAllBinaryTypes_MeqServer(Do,arg,separator) \
        

#define DoForAllSpecialTypes_MeqServer(Do,arg,separator) \
        

#define DoForAllIntermediateTypes_MeqServer(Do,arg,separator) \
        

#define DoForAllDynamicTypes_MeqServer(Do,arg,separator) \
        Do(Meq::Sink,arg) separator \
        Do(Meq::Spigot,arg)

#define DoForAllNumericTypes_MeqServer(Do,arg,separator) \
        
#endif
