      #ifndef AID_AppUtils_h
      #define AID_AppUtils_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_AppUtils ();

#ifndef _defined_id_AidAuto
#define _defined_id_AidAuto 1
const AtomicID AidAuto(-1273);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidAuto_int = -1273;
#endif
#ifndef _defined_id_AidClosed
#define _defined_id_AidClosed 1
const AtomicID AidClosed(-1318);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/ApplicationBase.h:17
const int AidClosed_int = -1318;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1116);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/test/EchoWP.h:13
const int AidData_int = -1116;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const AtomicID AidError(-1084);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Gateways.h:19
const int AidError_int = -1084;
#endif
#ifndef _defined_id_AidFail
#define _defined_id_AidFail 1
const AtomicID AidFail(-1036);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:9
const int AidFail_int = -1036;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const AtomicID AidFooter(-1151);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidFooter_int = -1151;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const AtomicID AidHeader(-1175);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidHeader_int = -1175;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const AtomicID AidInit(-1091);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/MTGatewayWP.h:22
const int AidInit_int = -1091;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const AtomicID AidInput(-1092);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/WPInterface.h:19
const int AidInput_int = -1092;
#endif
#ifndef _defined_id_AidInterrupt
#define _defined_id_AidInterrupt 1
const AtomicID AidInterrupt(-1319);               // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidInterrupt_int = -1319;
#endif
#ifndef _defined_id_AidMismatch
#define _defined_id_AidMismatch 1
const AtomicID AidMismatch(-1320);                // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidMismatch_int = -1320;
#endif
#ifndef _defined_id_AidNum
#define _defined_id_AidNum 1
const AtomicID AidNum(-1177);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidNum_int = -1177;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const AtomicID AidOutput(-1282);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/VisAgent/src/VisAgentVocabulary.h:10
const int AidOutput_int = -1282;
#endif
#ifndef _defined_id_AidPause
#define _defined_id_AidPause 1
const AtomicID AidPause(-1274);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:16
const int AidPause_int = -1274;
#endif
#ifndef _defined_id_AidRepeater
#define _defined_id_AidRepeater 1
const AtomicID AidRepeater(-1317);                // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:9
const int AidRepeater_int = -1317;
#endif
#ifndef _defined_id_AidSeq
#define _defined_id_AidSeq 1
const AtomicID AidSeq(-1315);                     // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/ApplicationBase.h:17
const int AidSeq_int = -1315;
#endif
#ifndef _defined_id_AidSet
#define _defined_id_AidSet 1
const AtomicID AidSet(-1316);                     // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidSet_int = -1316;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1060);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/WPInterface.h:21
const int AidState_int = -1060;
#endif
#ifndef _defined_id_AidStream
#define _defined_id_AidStream 1
const AtomicID AidStream(-1322);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidStream_int = -1322;
#endif
#ifndef _defined_id_AidTiles
#define _defined_id_AidTiles 1
const AtomicID AidTiles(-1323);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidTiles_int = -1323;
#endif
#ifndef _defined_id_AidVDSID
#define _defined_id_AidVDSID 1
const AtomicID AidVDSID(-1139);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:36
const int AidVDSID_int = -1139;
#endif
#ifndef _defined_id_AidVisRepeater
#define _defined_id_AidVisRepeater 1
const AtomicID AidVisRepeater(-1321);             // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:9
const int AidVisRepeater_int = -1321;
#endif
#ifndef _defined_id_AidWhen
#define _defined_id_AidWhen 1
const AtomicID AidWhen(-1340);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/ApplicationBase.h:17
const int AidWhen_int = -1340;
#endif


#endif
