      #ifndef AID_AppUtils_h
      #define AID_AppUtils_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../TIMBA/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_AppUtils ();

#ifndef _defined_id_AidAuto
#define _defined_id_AidAuto 1
const DMI::AtomicID AidAuto(-1090);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:39
const int AidAuto_int = -1090;
#endif
#ifndef _defined_id_AidCalibrated
#define _defined_id_AidCalibrated 1
const DMI::AtomicID AidCalibrated(-1374);         // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:39
const int AidCalibrated_int = -1374;
#endif
#ifndef _defined_id_AidClosed
#define _defined_id_AidClosed 1
const DMI::AtomicID AidClosed(-1377);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/ApplicationBase.h:20
const int AidClosed_int = -1377;
#endif
#ifndef _defined_id_AidColumn
#define _defined_id_AidColumn 1
const DMI::AtomicID AidColumn(-1393);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidColumn_int = -1393;
#endif
#ifndef _defined_id_AidDDID
#define _defined_id_AidDDID 1
const DMI::AtomicID AidDDID(-1391);               // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidDDID_int = -1391;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const DMI::AtomicID AidData(-1248);               // from /home/oms/LOFAR/TIMBA/MeqNodes/src/DataCollect.h:30
const int AidData_int = -1248;
#endif
#ifndef _defined_id_AidDomain
#define _defined_id_AidDomain 1
const DMI::AtomicID AidDomain(-1058);             // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:33
const int AidDomain_int = -1058;
#endif
#ifndef _defined_id_AidEnd
#define _defined_id_AidEnd 1
const DMI::AtomicID AidEnd(-1048);                // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int AidEnd_int = -1048;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const DMI::AtomicID AidError(-1350);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/AppAgent.h:10
const int AidError_int = -1350;
#endif
#ifndef _defined_id_AidFail
#define _defined_id_AidFail 1
const DMI::AtomicID AidFail(-1038);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:37
const int AidFail_int = -1038;
#endif
#ifndef _defined_id_AidFlag
#define _defined_id_AidFlag 1
const DMI::AtomicID AidFlag(-1060);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:40
const int AidFlag_int = -1060;
#endif
#ifndef _defined_id_AidFlags
#define _defined_id_AidFlags 1
const DMI::AtomicID AidFlags(-1158);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:33
const int AidFlags_int = -1158;
#endif
#ifndef _defined_id_AidFlip
#define _defined_id_AidFlip 1
const DMI::AtomicID AidFlip(-1373);               // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:37
const int AidFlip_int = -1373;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const DMI::AtomicID AidFooter(-1266);             // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:29
const int AidFooter_int = -1266;
#endif
#ifndef _defined_id_AidFormat
#define _defined_id_AidFormat 1
const DMI::AtomicID AidFormat(-1389);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidFormat_int = -1389;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const DMI::AtomicID AidHeader(-1277);             // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:29
const int AidHeader_int = -1277;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const DMI::AtomicID AidInit(-1085);               // from /home/oms/LOFAR/TIMBA/MEQ/src/Node.h:39
const int AidInit_int = -1085;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const DMI::AtomicID AidInput(-1354);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidInput_int = -1354;
#endif
#ifndef _defined_id_AidInterrupt
#define _defined_id_AidInterrupt 1
const DMI::AtomicID AidInterrupt(-1379);          // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidInterrupt_int = -1379;
#endif
#ifndef _defined_id_AidIteration
#define _defined_id_AidIteration 1
const DMI::AtomicID AidIteration(-1394);          // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:39
const int AidIteration_int = -1394;
#endif
#ifndef _defined_id_AidMS
#define _defined_id_AidMS 1
const DMI::AtomicID AidMS(-1289);                 // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:27
const int AidMS_int = -1289;
#endif
#ifndef _defined_id_AidMask
#define _defined_id_AidMask 1
const DMI::AtomicID AidMask(-1130);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:32
const int AidMask_int = -1130;
#endif
#ifndef _defined_id_AidMessage
#define _defined_id_AidMessage 1
const DMI::AtomicID AidMessage(-1115);            // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:37
const int AidMessage_int = -1115;
#endif
#ifndef _defined_id_AidMismatch
#define _defined_id_AidMismatch 1
const DMI::AtomicID AidMismatch(-1383);           // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:10
const int AidMismatch_int = -1383;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const DMI::AtomicID AidName(-1121);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:30
const int AidName_int = -1121;
#endif
#ifndef _defined_id_AidNon
#define _defined_id_AidNon 1
const DMI::AtomicID AidNon(-1392);                // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:39
const int AidNon_int = -1392;
#endif
#ifndef _defined_id_AidNum
#define _defined_id_AidNum 1
const DMI::AtomicID AidNum(-1110);                // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:35
const int AidNum_int = -1110;
#endif
#ifndef _defined_id_AidOriginal
#define _defined_id_AidOriginal 1
const DMI::AtomicID AidOriginal(-1380);           // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:37
const int AidOriginal_int = -1380;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const DMI::AtomicID AidOutput(-1362);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidOutput_int = -1362;
#endif
#ifndef _defined_id_AidParams
#define _defined_id_AidParams 1
const DMI::AtomicID AidParams(-1390);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:35
const int AidParams_int = -1390;
#endif
#ifndef _defined_id_AidPause
#define _defined_id_AidPause 1
const DMI::AtomicID AidPause(-1361);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/AppControlAgent.h:19
const int AidPause_int = -1361;
#endif
#ifndef _defined_id_AidPredict
#define _defined_id_AidPredict 1
const DMI::AtomicID AidPredict(-1378);            // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:36
const int AidPredict_int = -1378;
#endif
#ifndef _defined_id_AidRaw
#define _defined_id_AidRaw 1
const DMI::AtomicID AidRaw(-1313);                // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:26
const int AidRaw_int = -1313;
#endif
#ifndef _defined_id_AidRepeater
#define _defined_id_AidRepeater 1
const DMI::AtomicID AidRepeater(-1376);           // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:9
const int AidRepeater_int = -1376;
#endif
#ifndef _defined_id_AidResiduals
#define _defined_id_AidResiduals 1
const DMI::AtomicID AidResiduals(-1384);          // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:36
const int AidResiduals_int = -1384;
#endif
#ifndef _defined_id_AidSelection
#define _defined_id_AidSelection 1
const DMI::AtomicID AidSelection(-1381);          // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidSelection_int = -1381;
#endif
#ifndef _defined_id_AidSeq
#define _defined_id_AidSeq 1
const DMI::AtomicID AidSeq(-1375);                // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/ApplicationBase.h:20
const int AidSeq_int = -1375;
#endif
#ifndef _defined_id_AidSet
#define _defined_id_AidSet 1
const DMI::AtomicID AidSet(-1086);                // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:39
const int AidSet_int = -1086;
#endif
#ifndef _defined_id_AidShape
#define _defined_id_AidShape 1
const DMI::AtomicID AidShape(-1100);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int AidShape_int = -1100;
#endif
#ifndef _defined_id_AidSize
#define _defined_id_AidSize 1
const DMI::AtomicID AidSize(-1072);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int AidSize_int = -1072;
#endif
#ifndef _defined_id_AidStart
#define _defined_id_AidStart 1
const DMI::AtomicID AidStart(-1169);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int AidStart_int = -1169;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const DMI::AtomicID AidState(-1059);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:30
const int AidState_int = -1059;
#endif
#ifndef _defined_id_AidStream
#define _defined_id_AidStream 1
const DMI::AtomicID AidStream(-1387);             // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidStream_int = -1387;
#endif
#ifndef _defined_id_AidString
#define _defined_id_AidString 1
const DMI::AtomicID AidString(-48);               // from /home/oms/LOFAR/TIMBA/DMI/src/TypeId.h:109
const int AidString_int = -48;
#endif
#ifndef _defined_id_AidThrow
#define _defined_id_AidThrow 1
const DMI::AtomicID AidThrow(-1338);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/AppAgent.h:10
const int AidThrow_int = -1338;
#endif
#ifndef _defined_id_AidTile
#define _defined_id_AidTile 1
const DMI::AtomicID AidTile(-1337);               // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/VisAgentVocabulary.h:11
const int AidTile_int = -1337;
#endif
#ifndef _defined_id_AidTiles
#define _defined_id_AidTiles 1
const DMI::AtomicID AidTiles(-1388);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidTiles_int = -1388;
#endif
#ifndef _defined_id_AidTime
#define _defined_id_AidTime 1
const DMI::AtomicID AidTime(-1077);               // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:33
const int AidTime_int = -1077;
#endif
#ifndef _defined_id_AidType
#define _defined_id_AidType 1
const DMI::AtomicID AidType(-1287);               // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:30
const int AidType_int = -1287;
#endif
#ifndef _defined_id_AidVDSID
#define _defined_id_AidVDSID 1
const DMI::AtomicID AidVDSID(-1299);              // from /home/oms/LOFAR/TIMBA/VisCube/src/VisVocabulary.h:36
const int AidVDSID_int = -1299;
#endif
#ifndef _defined_id_AidVis
#define _defined_id_AidVis 1
const DMI::AtomicID AidVis(-1332);                // from /home/oms/LOFAR/TIMBA/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidVis_int = -1332;
#endif
#ifndef _defined_id_AidVisRepeater
#define _defined_id_AidVisRepeater 1
const DMI::AtomicID AidVisRepeater(-1385);        // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/VisRepeater.h:9
const int AidVisRepeater_int = -1385;
#endif
#ifndef _defined_id_AidWhen
#define _defined_id_AidWhen 1
const DMI::AtomicID AidWhen(-1386);               // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/ApplicationBase.h:20
const int AidWhen_int = -1386;
#endif
#ifndef _defined_id_AidWrite
#define _defined_id_AidWrite 1
const DMI::AtomicID AidWrite(-1382);              // from /home/oms/LOFAR/TIMBA/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:35
const int AidWrite_int = -1382;
#endif
#ifndef _defined_id_Aidstart
#define _defined_id_Aidstart 1
const DMI::AtomicID Aidstart(-1169);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int Aidstart_int = -1169;
#endif
#ifndef _defined_id_Aidstring
#define _defined_id_Aidstring 1
const DMI::AtomicID Aidstring(-48);               // from /home/oms/LOFAR/TIMBA/DMI/src/TypeId.h:109
const int Aidstring_int = -48;
#endif


#endif
