    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
  
    int aidRegistry_AppUtils ()
    {
      static int res = 

        AtomicID::registerId(-1092,"input")+
        AtomicID::registerId(-1282,"output")+
        AtomicID::registerId(-1315,"seq")+
        AtomicID::registerId(-1084,"error")+
        AtomicID::registerId(-1318,"closed")+
        AtomicID::registerId(-1091,"init")+
        AtomicID::registerId(-1036,"fail")+
        AtomicID::registerId(-1340,"when")+
        AtomicID::registerId(-1321,"visrepeater")+
        AtomicID::registerId(-1317,"repeater")+
        AtomicID::registerId(-1116,"data")+
        AtomicID::registerId(-1316,"set")+
        AtomicID::registerId(-1175,"header")+
        AtomicID::registerId(-1151,"footer")+
        AtomicID::registerId(-1319,"interrupt")+
        AtomicID::registerId(-1320,"mismatch")+
        AtomicID::registerId(-1322,"stream")+
        AtomicID::registerId(-1060,"state")+
        AtomicID::registerId(-1177,"num")+
        AtomicID::registerId(-1323,"tiles")+
        AtomicID::registerId(-1139,"vdsid")+
        AtomicID::registerId(-1273,"auto")+
        AtomicID::registerId(-1274,"pause")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_AppUtils = aidRegistry_AppUtils();

