    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
  
    int aidRegistry_AppUtils ()
    {
      static int res = 

        AtomicID::registerId(-1075,"Input")+
        AtomicID::registerId(-1130,"Output")+
        AtomicID::registerId(-1308,"Seq")+
        AtomicID::registerId(-1071,"Error")+
        AtomicID::registerId(-1307,"Closed")+
        AtomicID::registerId(-1092,"Init")+
        AtomicID::registerId(-1266,"Fail")+
        AtomicID::registerId(-1310,"VisRepeater")+
        AtomicID::registerId(-1306,"Repeater")+
        AtomicID::registerId(-1107,"Data")+
        AtomicID::registerId(-1381,"Set")+
        AtomicID::registerId(-1133,"Header")+
        AtomicID::registerId(-1202,"Footer")+
        AtomicID::registerId(-1382,"Interrupt")+
        AtomicID::registerId(-1383,"Mismatch")+
        AtomicID::registerId(-1391,"Stream")+
        AtomicID::registerId(-1052,"State")+
        AtomicID::registerId(-1140,"Num")+
        AtomicID::registerId(-1392,"Tiles")+
        AtomicID::registerId(-1121,"VDSID")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_AppUtils = aidRegistry_AppUtils();

