    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
  
    int aidRegistry_AppUtils ()
    {
      static int res = 

        AtomicID::registerId(-1072,"Input")+
        AtomicID::registerId(-1242,"Output")+
        AtomicID::registerId(-1245,"Seq")+
        AtomicID::registerId(-1067,"Error")+
        AtomicID::registerId(-1241,"Closed")+
        AtomicID::registerId(-1095,"Init")+
        AtomicID::registerId(-1036,"Fail")+
        AtomicID::registerId(-1240,"VisRepeater")+
        AtomicID::registerId(-1237,"Repeater")+
        AtomicID::registerId(-1118,"Data")+
        AtomicID::registerId(-1236,"Set")+
        AtomicID::registerId(-1200,"Header")+
        AtomicID::registerId(-1188,"Footer")+
        AtomicID::registerId(-1239,"Interrupt")+
        AtomicID::registerId(-1244,"Mismatch")+
        AtomicID::registerId(-1238,"Stream")+
        AtomicID::registerId(-1043,"State")+
        AtomicID::registerId(-1147,"Num")+
        AtomicID::registerId(-1243,"Tiles")+
        AtomicID::registerId(-1166,"VDSID")+
        AtomicID::registerId(-1233,"Auto")+
        AtomicID::registerId(-1229,"Pause")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_AppUtils = aidRegistry_AppUtils();

