      #ifndef AID_AppUtils_h
      #define AID_AppUtils_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_AppUtils ();

#ifndef _defined_id_AidClosed
#define _defined_id_AidClosed 1
const AtomicID AidClosed(-1307);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:1
const int AidClosed_int = -1307;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1107);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/test/Testing.aidlist:2
const int AidData_int = -1107;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const AtomicID AidError(-1071);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:23
const int AidError_int = -1071;
#endif
#ifndef _defined_id_AidFail
#define _defined_id_AidFail 1
const AtomicID AidFail(-1266);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:25
const int AidFail_int = -1266;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const AtomicID AidFooter(-1202);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:27
const int AidFooter_int = -1202;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const AtomicID AidHeader(-1133);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:30
const int AidHeader_int = -1133;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const AtomicID AidInit(-1092);                    // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:41
const int AidInit_int = -1092;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const AtomicID AidInput(-1075);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:42
const int AidInput_int = -1075;
#endif
#ifndef _defined_id_AidInterrupt
#define _defined_id_AidInterrupt 1
const AtomicID AidInterrupt(-1382);               // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:9
const int AidInterrupt_int = -1382;
#endif
#ifndef _defined_id_AidMismatch
#define _defined_id_AidMismatch 1
const AtomicID AidMismatch(-1383);                // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:10
const int AidMismatch_int = -1383;
#endif
#ifndef _defined_id_AidNum
#define _defined_id_AidNum 1
const AtomicID AidNum(-1140);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:46
const int AidNum_int = -1140;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const AtomicID AidOutput(-1130);                  // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/VisAgent/src/VisAgent.aidlist:6
const int AidOutput_int = -1130;
#endif
#ifndef _defined_id_AidRepeater
#define _defined_id_AidRepeater 1
const AtomicID AidRepeater(-1306);                // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:12
const int AidRepeater_int = -1306;
#endif
#ifndef _defined_id_AidSeq
#define _defined_id_AidSeq 1
const AtomicID AidSeq(-1308);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:13
const int AidSeq_int = -1308;
#endif
#ifndef _defined_id_AidSet
#define _defined_id_AidSet 1
const AtomicID AidSet(-1381);                     // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:14
const int AidSet_int = -1381;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1052);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:67
const int AidState_int = -1052;
#endif
#ifndef _defined_id_AidStream
#define _defined_id_AidStream 1
const AtomicID AidStream(-1391);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidStream_int = -1391;
#endif
#ifndef _defined_id_AidTiles
#define _defined_id_AidTiles 1
const AtomicID AidTiles(-1392);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppUtils/src/VisRepeater.h:12
const int AidTiles_int = -1392;
#endif
#ifndef _defined_id_AidVDSID
#define _defined_id_AidVDSID 1
const AtomicID AidVDSID(-1121);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/VisCube/src/VisCube.aidlist:83
const int AidVDSID_int = -1121;
#endif
#ifndef _defined_id_AidVisRepeater
#define _defined_id_AidVisRepeater 1
const AtomicID AidVisRepeater(-1310);             // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/AppAgent/AppUtils/src/AppUtils.aidlist:15
const int AidVisRepeater_int = -1310;
#endif


#endif
