      #ifndef AID_OctoPython_h
      #define AID_OctoPython_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../TIMBA/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_OctoPython ();

#ifndef _defined_id_AidPython
#define _defined_id_AidPython 1
const DMI::AtomicID AidPython(-1257);             // from /home/oms/LOFAR/TIMBA/OCTOPython/src/OctoPython.h:9
const int AidPython_int = -1257;
#endif


#endif
