    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #ifndef _TypeIter_Meq_h
    #define _TypeIter_Meq_h 1



#define DoForAllBinaryTypes_Meq(Do,arg,separator) \
        

#define DoForAllDynamicTypes_Meq(Do,arg,separator) \
        Do(MeqAdd,arg) separator \
        Do(MeqConj,arg) separator \
        Do(MeqCos,arg) separator \
        Do(MeqDivide,arg) separator \
        Do(MeqExp,arg) separator \
        Do(MeqFunction,arg) separator \
        Do(MeqMultiply,arg) separator \
        Do(MeqNode,arg) separator \
        Do(MeqParmPolcStored,arg) separator \
        Do(MeqPow,arg) separator \
        Do(MeqSin,arg) separator \
        Do(MeqSqr,arg) separator \
        Do(MeqSqrt,arg) separator \
        Do(MeqSubtract,arg) separator \
        Do(MeqToComplex,arg)

#define DoForAllNumericTypes_Meq(Do,arg,separator) \
        

#define DoForAllIntermediateTypes_Meq(Do,arg,separator) \
        

#define DoForAllOtherTypes_Meq(Do,arg,separator) \
        

#define DoForAllSpecialTypes_Meq(Do,arg,separator) \
        
#endif
