    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
  
    int aidRegistry_OCTOGlish ()
    {
      static int res = 

        AtomicID::registerId(-1039,"GlishClientWP")+
        AtomicID::registerId(-1045,"Index")+
        AtomicID::registerId(-1043,"start")+
        AtomicID::registerId(-1041,"IMTestWP")+
        AtomicID::registerId(-1040,"HelloWorld")+
        AtomicID::registerId(-1042,"Content")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_OCTOGlish = aidRegistry_OCTOGlish();

