      #ifndef AID_OCTOGlish_h
      #define AID_OCTOGlish_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_OCTOGlish ();

#ifndef _defined_id_AidContent
#define _defined_id_AidContent 1
const AtomicID AidContent(-1123);                 // from /home/oms/LOFAR/CEP/CPA/OCTOGlish/src/GlishClientWP.h:18
const int AidContent_int = -1123;
#endif
#ifndef _defined_id_AidGlishClientWP
#define _defined_id_AidGlishClientWP 1
const AtomicID AidGlishClientWP(-1122);           // from /home/oms/LOFAR/CEP/CPA/OCTOGlish/src/GlishClientWP.h:17
const int AidGlishClientWP_int = -1122;
#endif
#ifndef _defined_id_AidHelloWorld
#define _defined_id_AidHelloWorld 1
const AtomicID AidHelloWorld(-1125);              // from /home/oms/LOFAR/CEP/CPA/OCTOGlish/src/GlishClientWP.h:18
const int AidHelloWorld_int = -1125;
#endif
#ifndef _defined_id_AidIMTestWP
#define _defined_id_AidIMTestWP 1
const AtomicID AidIMTestWP(-1124);                // from /home/oms/LOFAR/CEP/CPA/OCTOGlish/src/GlishClientWP.h:18
const int AidIMTestWP_int = -1124;
#endif
#ifndef _defined_id_AidIndex
#define _defined_id_AidIndex 1
const AtomicID AidIndex(-1035);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Message.h:26
const int AidIndex_int = -1035;
#endif
#ifndef _defined_id_Aidstart
#define _defined_id_Aidstart 1
const AtomicID Aidstart(-1126);                   // from /home/oms/LOFAR/CEP/CPA/OCTOGlish/src/GlishClientWP.h:18
const int Aidstart_int = -1126;
#endif


#endif
