      #ifndef AID_OCTOGlish_h
      #define AID_OCTOGlish_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../TIMBA/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_OCTOGlish ();

#ifndef _defined_id_AidContent
#define _defined_id_AidContent 1
const DMI::AtomicID AidContent(-1256);            // from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishClientWP.h:18
const int AidContent_int = -1256;
#endif
#ifndef _defined_id_AidGlishClientWP
#define _defined_id_AidGlishClientWP 1
const DMI::AtomicID AidGlishClientWP(-1251);      // from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishClientWP.h:17
const int AidGlishClientWP_int = -1251;
#endif
#ifndef _defined_id_AidGlishConnServerWP
#define _defined_id_AidGlishConnServerWP 1
const DMI::AtomicID AidGlishConnServerWP(-1255);  // from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishConnServerWP.h:7
const int AidGlishConnServerWP_int = -1255;
#endif
#ifndef _defined_id_AidGlishThreadedClientWP
#define _defined_id_AidGlishThreadedClientWP 1
const DMI::AtomicID AidGlishThreadedClientWP(-1253);// from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishThreadWP.h:7
const int AidGlishThreadedClientWP_int = -1253;
#endif
#ifndef _defined_id_AidHelloWorld
#define _defined_id_AidHelloWorld 1
const DMI::AtomicID AidHelloWorld(-1252);         // from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishClientWP.h:18
const int AidHelloWorld_int = -1252;
#endif
#ifndef _defined_id_AidIMTestWP
#define _defined_id_AidIMTestWP 1
const DMI::AtomicID AidIMTestWP(-1254);           // from /home/oms/LOFAR/TIMBA/OCTOGlish/src/GlishClientWP.h:18
const int AidIMTestWP_int = -1254;
#endif
#ifndef _defined_id_AidIndex
#define _defined_id_AidIndex 1
const DMI::AtomicID AidIndex(-1055);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:35
const int AidIndex_int = -1055;
#endif
#ifndef _defined_id_Aidstart
#define _defined_id_Aidstart 1
const DMI::AtomicID Aidstart(-1169);              // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:34
const int Aidstart_int = -1169;
#endif


#endif
