      #ifndef AID_OCTOGlish_h
      #define AID_OCTOGlish_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_OCTOGlish ();

#ifndef _defined_id_AidContent
#define _defined_id_AidContent 1
const AtomicID AidContent(-1042);                 // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOGlish/src/OCTOGlish.aidlist:1
const int AidContent_int = -1042;
#endif
#ifndef _defined_id_AidGlishClientWP
#define _defined_id_AidGlishClientWP 1
const AtomicID AidGlishClientWP(-1039);           // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOGlish/src/OCTOGlish.aidlist:2
const int AidGlishClientWP_int = -1039;
#endif
#ifndef _defined_id_AidHelloWorld
#define _defined_id_AidHelloWorld 1
const AtomicID AidHelloWorld(-1040);              // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOGlish/src/OCTOGlish.aidlist:3
const int AidHelloWorld_int = -1040;
#endif
#ifndef _defined_id_AidIMTestWP
#define _defined_id_AidIMTestWP 1
const AtomicID AidIMTestWP(-1041);                // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOGlish/src/OCTOGlish.aidlist:4
const int AidIMTestWP_int = -1041;
#endif
#ifndef _defined_id_AidIndex
#define _defined_id_AidIndex 1
const AtomicID AidIndex(-1045);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOPUSSY/src/OCTOPUSSY.aidlist:40
const int AidIndex_int = -1045;
#endif
#ifndef _defined_id_Aidstart
#define _defined_id_Aidstart 1
const AtomicID Aidstart(-1043);                   // from /home/oms/LOFAR/autoconf_share/../CEP/CPA/OCTOGlish/src/OCTOGlish.aidlist:6
const int Aidstart_int = -1043;
#endif


#endif
