    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    using namespace DMI;
  
    int aidRegistry_OCTOGlish ()
    {
      static int res = 

        AtomicID::registerId(-1109,"GlishClientWP")+
        AtomicID::registerId(-1061,"Index")+
        AtomicID::registerId(-1106,"start")+
        AtomicID::registerId(-1110,"IMTestWP")+
        AtomicID::registerId(-1112,"HelloWorld")+
        AtomicID::registerId(-1111,"Content")+
        AtomicID::registerId(-1107,"GlishThreadedClientWP")+
        AtomicID::registerId(-1108,"GlishConnServerWP")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_OCTOGlish = aidRegistry_OCTOGlish();

