    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_AppAgent ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_AppAgent(-1112,"AppAgent");
static AtomicID::Register aid_reg_Event(-1060,"Event");

