    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    using namespace DMI;
  
    int aidRegistry_AppAgent ()
    {
      static int res = 

        AtomicID::registerId(-1220,"BOIO")+
        AtomicID::registerId(-1224,"File")+
        AtomicID::registerId(-1122,"Name")+
        AtomicID::registerId(-1215,"Mode")+
        AtomicID::registerId(-1080,"Event")+
        AtomicID::registerId(-1103,"Data")+
        AtomicID::registerId(-1205,"Throw")+
        AtomicID::registerId(-1056,"Error")+
        AtomicID::registerId(-1201,"Header")+
        AtomicID::registerId(-1135,"Footer")+
        AtomicID::registerId(-1203,"App")+
        AtomicID::registerId(-1142,"Control")+
        AtomicID::registerId(-1235,"Parameters")+
        AtomicID::registerId(-1038,"Init")+
        AtomicID::registerId(-1106,"Start")+
        AtomicID::registerId(-1247,"Stop")+
        AtomicID::registerId(-1245,"Pause")+
        AtomicID::registerId(-1239,"Resume")+
        AtomicID::registerId(-1227,"Halt")+
        AtomicID::registerId(-1225,"Always")+
        AtomicID::registerId(-1206,"Wait")+
        AtomicID::registerId(-1210,"Notify")+
        AtomicID::registerId(-1213,"Auto")+
        AtomicID::registerId(-1230,"Exit")+
        AtomicID::registerId(-1164,"Delay")+
        AtomicID::registerId(-1072,"State")+
        AtomicID::registerId(-48,"String")+
        AtomicID::registerId(-1209,"Status")+
        AtomicID::registerId(-1226,"Request")+
        AtomicID::registerId(-1183,"Field")+
        AtomicID::registerId(-1233,"Value")+
        AtomicID::registerId(-1208,"ID")+
        AtomicID::registerId(-1234,"Paused")+
        AtomicID::registerId(-1204,"Command")+
        AtomicID::registerId(-1229,"Update")+
        AtomicID::registerId(-1242,"Result")+
        AtomicID::registerId(-1228,"AppAgent")+
        AtomicID::registerId(-1055,"Text")+
        AtomicID::registerId(-1243,"Agent")+
        AtomicID::registerId(-1216,"Map")+
        AtomicID::registerId(-1236,"Receive")+
        AtomicID::registerId(-1231,"Post")+
        AtomicID::registerId(-1207,"In")+
        AtomicID::registerId(-1217,"Out")+
        AtomicID::registerId(-1221,"Default")+
        AtomicID::registerId(-1041,"Scope")+
        AtomicID::registerId(-1212,"Unmapped")+
        AtomicID::registerId(-1214,"Prefix")+
        AtomicID::registerId(-1053,"Local")+
        AtomicID::registerId(-1096,"Host")+
        AtomicID::registerId(-1211,"Global")+
        AtomicID::registerId(-1244,"Priority")+
        AtomicID::registerId(-1237,"Lowest")+
        AtomicID::registerId(-1218,"Lower")+
        AtomicID::registerId(-1238,"Low")+
        AtomicID::registerId(-1223,"Normal")+
        AtomicID::registerId(-1246,"High")+
        AtomicID::registerId(-1222,"Higher")+
        AtomicID::registerId(-1240,"Vis")+
        AtomicID::registerId(-1036,"Input")+
        AtomicID::registerId(-1241,"Output")+
        AtomicID::registerId(-1232,"Tile")+
        AtomicID::registerId(-1219,"Suspend")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_AppAgent = aidRegistry_AppAgent();

