      #ifndef AID_AppAgent_h
      #define AID_AppAgent_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_AppAgent ();

#ifndef _defined_id_AidAlways
#define _defined_id_AidAlways 1
const AtomicID AidAlways(-1228);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidAlways_int = -1228;
#endif
#ifndef _defined_id_AidApp
#define _defined_id_AidApp 1
const AtomicID AidApp(-1107);                     // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:9
const int AidApp_int = -1107;
#endif
#ifndef _defined_id_AidAppAgent
#define _defined_id_AidAppAgent 1
const AtomicID AidAppAgent(-1231);                // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppEventSink.h:30
const int AidAppAgent_int = -1231;
#endif
#ifndef _defined_id_AidAuto
#define _defined_id_AidAuto 1
const AtomicID AidAuto(-1233);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidAuto_int = -1233;
#endif
#ifndef _defined_id_AidBOIO
#define _defined_id_AidBOIO 1
const AtomicID AidBOIO(-1218);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidBOIO_int = -1218;
#endif
#ifndef _defined_id_AidCommand
#define _defined_id_AidCommand 1
const AtomicID AidCommand(-1232);                 // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidCommand_int = -1232;
#endif
#ifndef _defined_id_AidControl
#define _defined_id_AidControl 1
const AtomicID AidControl(-1155);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidControl_int = -1155;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1118);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/test/EchoWP.h:13
const int AidData_int = -1118;
#endif
#ifndef _defined_id_AidDelay
#define _defined_id_AidDelay 1
const AtomicID AidDelay(-1204);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidDelay_int = -1204;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const AtomicID AidError(-1067);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Gateways.h:19
const int AidError_int = -1067;
#endif
#ifndef _defined_id_AidEvent
#define _defined_id_AidEvent 1
const AtomicID AidEvent(-1052);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/WPInterface.h:19
const int AidEvent_int = -1052;
#endif
#ifndef _defined_id_AidExit
#define _defined_id_AidExit 1
const AtomicID AidExit(-1227);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidExit_int = -1227;
#endif
#ifndef _defined_id_AidField
#define _defined_id_AidField 1
const AtomicID AidField(-1144);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidField_int = -1144;
#endif
#ifndef _defined_id_AidFile
#define _defined_id_AidFile 1
const AtomicID AidFile(-1235);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidFile_int = -1235;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const AtomicID AidFooter(-1188);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidFooter_int = -1188;
#endif
#ifndef _defined_id_AidHalt
#define _defined_id_AidHalt 1
const AtomicID AidHalt(-1106);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:9
const int AidHalt_int = -1106;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const AtomicID AidHeader(-1200);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidHeader_int = -1200;
#endif
#ifndef _defined_id_AidID
#define _defined_id_AidID 1
const AtomicID AidID(-1105);                      // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:10
const int AidID_int = -1105;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const AtomicID AidInit(-1095);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/MTGatewayWP.h:22
const int AidInit_int = -1095;
#endif
#ifndef _defined_id_AidMode
#define _defined_id_AidMode 1
const AtomicID AidMode(-1225);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidMode_int = -1225;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const AtomicID AidName(-1145);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidName_int = -1145;
#endif
#ifndef _defined_id_AidNotify
#define _defined_id_AidNotify 1
const AtomicID AidNotify(-1223);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidNotify_int = -1223;
#endif
#ifndef _defined_id_AidParameters
#define _defined_id_AidParameters 1
const AtomicID AidParameters(-1050);              // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:10
const int AidParameters_int = -1050;
#endif
#ifndef _defined_id_AidPause
#define _defined_id_AidPause 1
const AtomicID AidPause(-1229);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:16
const int AidPause_int = -1229;
#endif
#ifndef _defined_id_AidPaused
#define _defined_id_AidPaused 1
const AtomicID AidPaused(-1234);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidPaused_int = -1234;
#endif
#ifndef _defined_id_AidRequest
#define _defined_id_AidRequest 1
const AtomicID AidRequest(-1220);                 // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidRequest_int = -1220;
#endif
#ifndef _defined_id_AidResult
#define _defined_id_AidResult 1
const AtomicID AidResult(-1217);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidResult_int = -1217;
#endif
#ifndef _defined_id_AidResume
#define _defined_id_AidResume 1
const AtomicID AidResume(-1219);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:16
const int AidResume_int = -1219;
#endif
#ifndef _defined_id_AidStart
#define _defined_id_AidStart 1
const AtomicID AidStart(-1091);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:9
const int AidStart_int = -1091;
#endif
#ifndef _defined_id_AidState
#define _defined_id_AidState 1
const AtomicID AidState(-1043);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/WPInterface.h:21
const int AidState_int = -1043;
#endif
#ifndef _defined_id_AidStatus
#define _defined_id_AidStatus 1
const AtomicID AidStatus(-1216);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidStatus_int = -1216;
#endif
#ifndef _defined_id_AidStop
#define _defined_id_AidStop 1
const AtomicID AidStop(-1053);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/AppManagerWP.h:9
const int AidStop_int = -1053;
#endif
#ifndef _defined_id_AidString
#define _defined_id_AidString 1
const AtomicID AidString(-1230);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidString_int = -1230;
#endif
#ifndef _defined_id_AidText
#define _defined_id_AidText 1
const AtomicID AidText(-1079);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Message.h:26
const int AidText_int = -1079;
#endif
#ifndef _defined_id_AidThrow
#define _defined_id_AidThrow 1
const AtomicID AidThrow(-1226);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppAgent.h:11
const int AidThrow_int = -1226;
#endif
#ifndef _defined_id_AidUpdate
#define _defined_id_AidUpdate 1
const AtomicID AidUpdate(-1222);                  // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidUpdate_int = -1222;
#endif
#ifndef _defined_id_AidValue
#define _defined_id_AidValue 1
const AtomicID AidValue(-1221);                   // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:18
const int AidValue_int = -1221;
#endif
#ifndef _defined_id_AidWait
#define _defined_id_AidWait 1
const AtomicID AidWait(-1224);                    // from /home/oms/LOFAR/CEP/CPA/AppAgent/AppAgent/src/AppControlAgent.h:17
const int AidWait_int = -1224;
#endif


#endif
