//
//% $Id$ 
//
//
// Copyright (C) 2002-2007
// The MeqTree Foundation & 
// ASTRON (Netherlands Foundation for Research in Astronomy)
// P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>,
// or write to the Free Software Foundation, Inc., 
// 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

      #ifndef AID_AppAgent_h
      #define AID_AppAgent_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_AppAgent ();

#ifndef _defined_id_AidAbort
#define _defined_id_AidAbort 1
const DMI::AtomicID AidAbort(-1642);              // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/EventChannel.h:34
const int AidAbort_int = -1642;
#endif
#ifndef _defined_id_AidAddress
#define _defined_id_AidAddress 1
const DMI::AtomicID AidAddress(-1543);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:31
const int AidAddress_int = -1543;
#endif
#ifndef _defined_id_AidAgent
#define _defined_id_AidAgent 1
const DMI::AtomicID AidAgent(-1243);              // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidAgent_int = -1243;
#endif
#ifndef _defined_id_AidAppAgent
#define _defined_id_AidAppAgent 1
const DMI::AtomicID AidAppAgent(-1228);           // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:30
const int AidAppAgent_int = -1228;
#endif
#ifndef _defined_id_AidBOIO
#define _defined_id_AidBOIO 1
const DMI::AtomicID AidBOIO(-1220);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidBOIO_int = -1220;
#endif
#ifndef _defined_id_AidCategory
#define _defined_id_AidCategory 1
const DMI::AtomicID AidCategory(-1496);           // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:30
const int AidCategory_int = -1496;
#endif
#ifndef _defined_id_AidChannel
#define _defined_id_AidChannel 1
const DMI::AtomicID AidChannel(-1165);            // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:26
const int AidChannel_int = -1165;
#endif
#ifndef _defined_id_AidCritical
#define _defined_id_AidCritical 1
const DMI::AtomicID AidCritical(-1497);           // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:31
const int AidCritical_int = -1497;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const DMI::AtomicID AidData(-1103);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/test/EchoWP.h:11
const int AidData_int = -1103;
#endif
#ifndef _defined_id_AidDebug
#define _defined_id_AidDebug 1
const DMI::AtomicID AidDebug(-1482);              // from /home/oms/LOFAR/Timba/MeqServer/src/MeqServer.h:16
const int AidDebug_int = -1482;
#endif
#ifndef _defined_id_AidDefault
#define _defined_id_AidDefault 1
const DMI::AtomicID AidDefault(-1221);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:13
const int AidDefault_int = -1221;
#endif
#ifndef _defined_id_AidDelete
#define _defined_id_AidDelete 1
const DMI::AtomicID AidDelete(-1336);             // from /home/oms/LOFAR/Timba/MEQ/src/Forest.h:31
const int AidDelete_int = -1336;
#endif
#ifndef _defined_id_AidDestination
#define _defined_id_AidDestination 1
const DMI::AtomicID AidDestination(-1495);        // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:30
const int AidDestination_int = -1495;
#endif
#ifndef _defined_id_AidError
#define _defined_id_AidError 1
const DMI::AtomicID AidError(-1056);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidError_int = -1056;
#endif
#ifndef _defined_id_AidEvent
#define _defined_id_AidEvent 1
const DMI::AtomicID AidEvent(-1080);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidEvent_int = -1080;
#endif
#ifndef _defined_id_AidFile
#define _defined_id_AidFile 1
const DMI::AtomicID AidFile(-1224);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidFile_int = -1224;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const DMI::AtomicID AidFooter(-1135);             // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidFooter_int = -1135;
#endif
#ifndef _defined_id_AidGlobal
#define _defined_id_AidGlobal 1
const DMI::AtomicID AidGlobal(-1211);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:13
const int AidGlobal_int = -1211;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const DMI::AtomicID AidHeader(-1201);             // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:29
const int AidHeader_int = -1201;
#endif
#ifndef _defined_id_AidHigh
#define _defined_id_AidHigh 1
const DMI::AtomicID AidHigh(-1246);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidHigh_int = -1246;
#endif
#ifndef _defined_id_AidHigher
#define _defined_id_AidHigher 1
const DMI::AtomicID AidHigher(-1222);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidHigher_int = -1222;
#endif
#ifndef _defined_id_AidHost
#define _defined_id_AidHost 1
const DMI::AtomicID AidHost(-1096);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:25
const int AidHost_int = -1096;
#endif
#ifndef _defined_id_AidIn
#define _defined_id_AidIn 1
const DMI::AtomicID AidIn(-1207);                 // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidIn_int = -1207;
#endif
#ifndef _defined_id_AidInfo
#define _defined_id_AidInfo 1
const DMI::AtomicID AidInfo(-1494);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:31
const int AidInfo_int = -1494;
#endif
#ifndef _defined_id_AidInit
#define _defined_id_AidInit 1
const DMI::AtomicID AidInit(-1038);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MTGatewayWP.h:16
const int AidInit_int = -1038;
#endif
#ifndef _defined_id_AidInput
#define _defined_id_AidInput 1
const DMI::AtomicID AidInput(-1036);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/WPInterface.h:23
const int AidInput_int = -1036;
#endif
#ifndef _defined_id_AidLocal
#define _defined_id_AidLocal 1
const DMI::AtomicID AidLocal(-1053);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/MsgAddress.h:9
const int AidLocal_int = -1053;
#endif
#ifndef _defined_id_AidLow
#define _defined_id_AidLow 1
const DMI::AtomicID AidLow(-1238);                // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidLow_int = -1238;
#endif
#ifndef _defined_id_AidLower
#define _defined_id_AidLower 1
const DMI::AtomicID AidLower(-1218);              // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidLower_int = -1218;
#endif
#ifndef _defined_id_AidLowest
#define _defined_id_AidLowest 1
const DMI::AtomicID AidLowest(-1237);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidLowest_int = -1237;
#endif
#ifndef _defined_id_AidMT
#define _defined_id_AidMT 1
const DMI::AtomicID AidMT(-1604);                 // from /home/oms/LOFAR/Timba/MEQ/src/Node.h:45
const int AidMT_int = -1604;
#endif
#ifndef _defined_id_AidMap
#define _defined_id_AidMap 1
const DMI::AtomicID AidMap(-1216);                // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidMap_int = -1216;
#endif
#ifndef _defined_id_AidMode
#define _defined_id_AidMode 1
const DMI::AtomicID AidMode(-1215);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/BOIOSink.h:9
const int AidMode_int = -1215;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const DMI::AtomicID AidName(-1122);               // from /home/oms/LOFAR/Timba/VisCube/src/VisVocabulary.h:28
const int AidName_int = -1122;
#endif
#ifndef _defined_id_AidNormal
#define _defined_id_AidNormal 1
const DMI::AtomicID AidNormal(-1223);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidNormal_int = -1223;
#endif
#ifndef _defined_id_AidNotify
#define _defined_id_AidNotify 1
const DMI::AtomicID AidNotify(-1210);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:20
const int AidNotify_int = -1210;
#endif
#ifndef _defined_id_AidOn
#define _defined_id_AidOn 1
const DMI::AtomicID AidOn(-1641);                 // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/EventChannel.h:34
const int AidOn_int = -1641;
#endif
#ifndef _defined_id_AidOut
#define _defined_id_AidOut 1
const DMI::AtomicID AidOut(-1217);                // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidOut_int = -1217;
#endif
#ifndef _defined_id_AidOutput
#define _defined_id_AidOutput 1
const DMI::AtomicID AidOutput(-1241);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidOutput_int = -1241;
#endif
#ifndef _defined_id_AidParameters
#define _defined_id_AidParameters 1
const DMI::AtomicID AidParameters(-1235);         // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:19
const int AidParameters_int = -1235;
#endif
#ifndef _defined_id_AidPost
#define _defined_id_AidPost 1
const DMI::AtomicID AidPost(-1231);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidPost_int = -1231;
#endif
#ifndef _defined_id_AidPrefix
#define _defined_id_AidPrefix 1
const DMI::AtomicID AidPrefix(-1214);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:13
const int AidPrefix_int = -1214;
#endif
#ifndef _defined_id_AidPriority
#define _defined_id_AidPriority 1
const DMI::AtomicID AidPriority(-1244);           // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:14
const int AidPriority_int = -1244;
#endif
#ifndef _defined_id_AidQueue
#define _defined_id_AidQueue 1
const DMI::AtomicID AidQueue(-1469);              // from /home/oms/LOFAR/Timba/MeqServer/src/Spigot.h:8
const int AidQueue_int = -1469;
#endif
#ifndef _defined_id_AidReceive
#define _defined_id_AidReceive 1
const DMI::AtomicID AidReceive(-1236);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:12
const int AidReceive_int = -1236;
#endif
#ifndef _defined_id_AidRecord
#define _defined_id_AidRecord 1
const DMI::AtomicID AidRecord(-1541);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:33
const int AidRecord_int = -1541;
#endif
#ifndef _defined_id_AidResume
#define _defined_id_AidResume 1
const DMI::AtomicID AidResume(-1239);             // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppControlAgent.h:19
const int AidResume_int = -1239;
#endif
#ifndef _defined_id_AidScope
#define _defined_id_AidScope 1
const DMI::AtomicID AidScope(-1041);              // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/LoggerWP.h:9
const int AidScope_int = -1041;
#endif
#ifndef _defined_id_AidSize
#define _defined_id_AidSize 1
const DMI::AtomicID AidSize(-1255);               // from /home/oms/LOFAR/Timba/AppAgent/AppUtils/src/MSVisAgentVocabulary.h:34
const int AidSize_int = -1255;
#endif
#ifndef _defined_id_AidSuspend
#define _defined_id_AidSuspend 1
const DMI::AtomicID AidSuspend(-1219);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:11
const int AidSuspend_int = -1219;
#endif
#ifndef _defined_id_AidText
#define _defined_id_AidText 1
const DMI::AtomicID AidText(-1055);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Message.h:30
const int AidText_int = -1055;
#endif
#ifndef _defined_id_AidTile
#define _defined_id_AidTile 1
const DMI::AtomicID AidTile(-1232);               // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:11
const int AidTile_int = -1232;
#endif
#ifndef _defined_id_AidType
#define _defined_id_AidType 1
const DMI::AtomicID AidType(-1085);               // from /home/oms/LOFAR/Timba/OCTOPUSSY/src/Gateways.h:24
const int AidType_int = -1085;
#endif
#ifndef _defined_id_AidUnmapped
#define _defined_id_AidUnmapped 1
const DMI::AtomicID AidUnmapped(-1212);           // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/OctoEventSink.h:13
const int AidUnmapped_int = -1212;
#endif
#ifndef _defined_id_AidVis
#define _defined_id_AidVis 1
const DMI::AtomicID AidVis(-1240);                // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/VisAgentVocabulary.h:10
const int AidVis_int = -1240;
#endif
#ifndef _defined_id_AidWarning
#define _defined_id_AidWarning 1
const DMI::AtomicID AidWarning(-1493);            // from /home/oms/LOFAR/Timba/AppAgent/AppAgent/src/AppEventSink.h:31
const int AidWarning_int = -1493;
#endif


#endif
