//
//% $Id$ 
//
//
// Copyright (C) 2002-2007
// The MeqTree Foundation & 
// ASTRON (Netherlands Foundation for Research in Astronomy)
// P.O.Box 2, 7990 AA Dwingeloo, The Netherlands
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, see <http://www.gnu.org/licenses/>,
// or write to the Free Software Foundation, Inc., 
// 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
    #ifndef _TypeIter_AppAgent_h
    #define _TypeIter_AppAgent_h 1



#define DoForAllOtherTypes_AppAgent(Do,arg,separator) \
        

#define DoForAllBinaryTypes_AppAgent(Do,arg,separator) \
        

#define DoForAllSpecialTypes_AppAgent(Do,arg,separator) \
        

#define DoForAllIntermediateTypes_AppAgent(Do,arg,separator) \
        

#define DoForAllDynamicTypes_AppAgent(Do,arg,separator) \
        

#define DoForAllNumericTypes_AppAgent(Do,arg,separator) \
        
#endif
