      #ifndef AID_Testing_h
      #define AID_Testing_h 1
      
      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../TIMBA/DMI/aid/build_aid_maps.pl
      #include <DMI/AtomicID.h>

      // should be called somewhere in order to link in the registry
      int aidRegistry_Testing ();

#ifndef _defined_id_AidCount
#define _defined_id_AidCount 1
const DMI::AtomicID AidCount(-1477);              // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:11
const int AidCount_int = -1477;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const DMI::AtomicID AidData(-1248);               // from /home/oms/LOFAR/TIMBA/MeqNodes/src/DataCollect.h:30
const int AidData_int = -1248;
#endif
#ifndef _defined_id_AidEchoWP
#define _defined_id_AidEchoWP 1
const DMI::AtomicID AidEchoWP(-1476);             // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:10
const int AidEchoWP_int = -1476;
#endif
#ifndef _defined_id_AidInvert
#define _defined_id_AidInvert 1
const DMI::AtomicID AidInvert(-1042);             // from /home/oms/LOFAR/TIMBA/MEQ/src/MeqVocabulary.h:39
const int AidInvert_int = -1042;
#endif
#ifndef _defined_id_AidPing
#define _defined_id_AidPing 1
const DMI::AtomicID AidPing(-1479);               // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:10
const int AidPing_int = -1479;
#endif
#ifndef _defined_id_AidPong
#define _defined_id_AidPong 1
const DMI::AtomicID AidPong(-1480);               // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:10
const int AidPong_int = -1480;
#endif
#ifndef _defined_id_AidProcess
#define _defined_id_AidProcess 1
const DMI::AtomicID AidProcess(-1478);            // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:11
const int AidProcess_int = -1478;
#endif
#ifndef _defined_id_AidReply
#define _defined_id_AidReply 1
const DMI::AtomicID AidReply(-1475);              // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/test/EchoWP.h:11
const int AidReply_int = -1475;
#endif
#ifndef _defined_id_AidTimestamp
#define _defined_id_AidTimestamp 1
const DMI::AtomicID AidTimestamp(-1450);          // from /home/oms/LOFAR/TIMBA/OCTOPUSSY/src/Gateways.h:23
const int AidTimestamp_int = -1450;
#endif


#endif
