    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../Timba/DMI/aid/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    using namespace DMI;
  
    int aidRegistry_Testing ()
    {
      static int res = 

        AtomicID::registerId(-1101,"EchoWP")+
        AtomicID::registerId(-1100,"Ping")+
        AtomicID::registerId(-1098,"Pong")+
        AtomicID::registerId(-1105,"Reply")+
        AtomicID::registerId(-1054,"Timestamp")+
        AtomicID::registerId(-1102,"Invert")+
        AtomicID::registerId(-1103,"Data")+
        AtomicID::registerId(-1099,"Count")+
        AtomicID::registerId(-1104,"Process")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_Testing = aidRegistry_Testing();

