    // This file is generated automatically -- do not edit
    // Generated by /home/wierenga/cvs/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include "DMI/AtomicID.h"
    #include "DMI/TypeInfo.h"
    #include "DMI/DynamicTypeManager.h"
    #include "DMI/Packer.h"

    int aidRegistry_Testing ()
    {
      return 1;
    }

static AtomicID::Register aid_reg_EchoWP(-787,"EchoWP");
static AtomicID::Register aid_reg_Ping(-795,"Ping");
static AtomicID::Register aid_reg_Pong(-789,"Pong");
static AtomicID::Register aid_reg_Reply(-793,"Reply");
static AtomicID::Register aid_reg_Timestamp(-85,"Timestamp");
static AtomicID::Register aid_reg_Invert(-790,"Invert");
static AtomicID::Register aid_reg_Data(-81,"Data");
static AtomicID::Register aid_reg_Count(-791,"Count");
static AtomicID::Register aid_reg_Process(-788,"Process");
static AtomicID::Register aid_reg_start(-797,"start");
static AtomicID::Register aid_reg_IMTestWP(-792,"IMTestWP");
static AtomicID::Register aid_reg_HelloWorld(-794,"HelloWorld");
static AtomicID::Register aid_reg_Content(-796,"Content");

