    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
    #ifndef _TypeIter_Testing_h
    #define _TypeIter_Testing_h 1



#define DoForAllBinaryTypes_Testing(Do,arg,separator) \
        

#define DoForAllDynamicTypes_Testing(Do,arg,separator) \
        

#define DoForAllNumericTypes_Testing(Do,arg,separator) \
        

#define DoForAllIntermediateTypes_Testing(Do,arg,separator) \
        

#define DoForAllOtherTypes_Testing(Do,arg,separator) \
        

#define DoForAllSpecialTypes_Testing(Do,arg,separator) \
        
#endif
