      #ifndef AID_VisCube_h
      #define AID_VisCube_h 1

      // This file is generated automatically -- do not edit
      // Generated by /home/oms/LOFAR/autoconf_share/../DMI/aid/build_aid_maps.pl
      #include "DMI/AtomicID.h"

      // should be called somewhere in order to link in the registry
      int aidRegistry_VisCube ();

#ifndef _defined_id_AidAIPSPP
#define _defined_id_AidAIPSPP 1
const AtomicID AidAIPSPP(-1125);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:36
const int AidAIPSPP_int = -1125;
#endif
#ifndef _defined_id_AidAngle
#define _defined_id_AidAngle 1
const AtomicID AidAngle(-1209);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidAngle_int = -1209;
#endif
#ifndef _defined_id_AidAntenna
#define _defined_id_AidAntenna 1
const AtomicID AidAntenna(-1147);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidAntenna_int = -1147;
#endif
#ifndef _defined_id_AidBandwidth
#define _defined_id_AidBandwidth 1
const AtomicID AidBandwidth(-1186);               // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidBandwidth_int = -1186;
#endif
#ifndef _defined_id_AidBeam
#define _defined_id_AidBeam 1
const AtomicID AidBeam(-1163);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidBeam_int = -1163;
#endif
#ifndef _defined_id_AidCalibration
#define _defined_id_AidCalibration 1
const AtomicID AidCalibration(-1129);             // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidCalibration_int = -1129;
#endif
#ifndef _defined_id_AidCentroid
#define _defined_id_AidCentroid 1
const AtomicID AidCentroid(-1138);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidCentroid_int = -1138;
#endif
#ifndef _defined_id_AidChain
#define _defined_id_AidChain 1
const AtomicID AidChain(-1141);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidChain_int = -1141;
#endif
#ifndef _defined_id_AidChannel
#define _defined_id_AidChannel 1
const AtomicID AidChannel(-1196);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidChannel_int = -1196;
#endif
#ifndef _defined_id_AidChunk
#define _defined_id_AidChunk 1
const AtomicID AidChunk(-1187);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidChunk_int = -1187;
#endif
#ifndef _defined_id_AidCode
#define _defined_id_AidCode 1
const AtomicID AidCode(-1164);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidCode_int = -1164;
#endif
#ifndef _defined_id_AidColumnarTableTile
#define _defined_id_AidColumnarTableTile 1
const AtomicID AidColumnarTableTile(-1168);       // from /home/oms/LOFAR/CEP/CPA/VisCube/src/ColumnarTableTile.h:9
const int AidColumnarTableTile_int = -1168;
#endif
#ifndef _defined_id_AidControl
#define _defined_id_AidControl 1
const AtomicID AidControl(-1131);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidControl_int = -1131;
#endif
#ifndef _defined_id_AidConv
#define _defined_id_AidConv 1
const AtomicID AidConv(-1195);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidConv_int = -1195;
#endif
#ifndef _defined_id_AidCorr
#define _defined_id_AidCorr 1
const AtomicID AidCorr(-1153);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidCorr_int = -1153;
#endif
#ifndef _defined_id_AidData
#define _defined_id_AidData 1
const AtomicID AidData(-1116);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/test/EchoWP.h:13
const int AidData_int = -1116;
#endif
#ifndef _defined_id_AidDelay
#define _defined_id_AidDelay 1
const AtomicID AidDelay(-1167);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidDelay_int = -1167;
#endif
#ifndef _defined_id_AidDesc
#define _defined_id_AidDesc 1
const AtomicID AidDesc(-1148);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidDesc_int = -1148;
#endif
#ifndef _defined_id_AidDiameter
#define _defined_id_AidDiameter 1
const AtomicID AidDiameter(-1145);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidDiameter_int = -1145;
#endif
#ifndef _defined_id_AidDir
#define _defined_id_AidDir 1
const AtomicID AidDir(-1130);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidDir_int = -1130;
#endif
#ifndef _defined_id_AidDish
#define _defined_id_AidDish 1
const AtomicID AidDish(-1202);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidDish_int = -1202;
#endif
#ifndef _defined_id_AidEffective
#define _defined_id_AidEffective 1
const AtomicID AidEffective(-1194);               // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidEffective_int = -1194;
#endif
#ifndef _defined_id_AidExposure
#define _defined_id_AidExposure 1
const AtomicID AidExposure(-1156);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidExposure_int = -1156;
#endif
#ifndef _defined_id_AidFeed
#define _defined_id_AidFeed 1
const AtomicID AidFeed(-1121);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidFeed_int = -1121;
#endif
#ifndef _defined_id_AidField
#define _defined_id_AidField 1
const AtomicID AidField(-1193);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidField_int = -1193;
#endif
#ifndef _defined_id_AidFlag
#define _defined_id_AidFlag 1
const AtomicID AidFlag(-1135);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidFlag_int = -1135;
#endif
#ifndef _defined_id_AidFooter
#define _defined_id_AidFooter 1
const AtomicID AidFooter(-1151);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidFooter_int = -1151;
#endif
#ifndef _defined_id_AidFreq
#define _defined_id_AidFreq 1
const AtomicID AidFreq(-1128);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidFreq_int = -1128;
#endif
#ifndef _defined_id_AidGroup
#define _defined_id_AidGroup 1
const AtomicID AidGroup(-1122);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidGroup_int = -1122;
#endif
#ifndef _defined_id_AidHeader
#define _defined_id_AidHeader 1
const AtomicID AidHeader(-1175);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidHeader_int = -1175;
#endif
#ifndef _defined_id_AidIF
#define _defined_id_AidIF 1
const AtomicID AidIF(-1154);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidIF_int = -1154;
#endif
#ifndef _defined_id_AidIFR
#define _defined_id_AidIFR 1
const AtomicID AidIFR(-1185);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidIFR_int = -1185;
#endif
#ifndef _defined_id_AidIgnore
#define _defined_id_AidIgnore 1
const AtomicID AidIgnore(-1199);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:36
const int AidIgnore_int = -1199;
#endif
#ifndef _defined_id_AidIndex
#define _defined_id_AidIndex 1
const AtomicID AidIndex(-1051);                   // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Message.h:26
const int AidIndex_int = -1051;
#endif
#ifndef _defined_id_AidIndexing
#define _defined_id_AidIndexing 1
const AtomicID AidIndexing(-1136);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidIndexing_int = -1136;
#endif
#ifndef _defined_id_AidIntegrate
#define _defined_id_AidIntegrate 1
const AtomicID AidIntegrate(-1172);               // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidIntegrate_int = -1172;
#endif
#ifndef _defined_id_AidIntegrated
#define _defined_id_AidIntegrated 1
const AtomicID AidIntegrated(-1160);              // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidIntegrated_int = -1160;
#endif
#ifndef _defined_id_AidInterval
#define _defined_id_AidInterval 1
const AtomicID AidInterval(-1146);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidInterval_int = -1146;
#endif
#ifndef _defined_id_AidLines
#define _defined_id_AidLines 1
const AtomicID AidLines(-1208);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidLines_int = -1208;
#endif
#ifndef _defined_id_AidMS
#define _defined_id_AidMS 1
const AtomicID AidMS(-1207);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidMS_int = -1207;
#endif
#ifndef _defined_id_AidMeas
#define _defined_id_AidMeas 1
const AtomicID AidMeas(-1201);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidMeas_int = -1201;
#endif
#ifndef _defined_id_AidMotion
#define _defined_id_AidMotion 1
const AtomicID AidMotion(-1171);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidMotion_int = -1171;
#endif
#ifndef _defined_id_AidMount
#define _defined_id_AidMount 1
const AtomicID AidMount(-1192);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidMount_int = -1192;
#endif
#ifndef _defined_id_AidName
#define _defined_id_AidName 1
const AtomicID AidName(-1188);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidName_int = -1188;
#endif
#ifndef _defined_id_AidNet
#define _defined_id_AidNet 1
const AtomicID AidNet(-1165);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidNet_int = -1165;
#endif
#ifndef _defined_id_AidNum
#define _defined_id_AidNum 1
const AtomicID AidNum(-1177);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidNum_int = -1177;
#endif
#ifndef _defined_id_AidOffset
#define _defined_id_AidOffset 1
const AtomicID AidOffset(-1190);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidOffset_int = -1190;
#endif
#ifndef _defined_id_AidOrigin
#define _defined_id_AidOrigin 1
const AtomicID AidOrigin(-1132);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidOrigin_int = -1132;
#endif
#ifndef _defined_id_AidPatch
#define _defined_id_AidPatch 1
const AtomicID AidPatch(-1205);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidPatch_int = -1205;
#endif
#ifndef _defined_id_AidPhase
#define _defined_id_AidPhase 1
const AtomicID AidPhase(-1124);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidPhase_int = -1124;
#endif
#ifndef _defined_id_AidPoint
#define _defined_id_AidPoint 1
const AtomicID AidPoint(-1204);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidPoint_int = -1204;
#endif
#ifndef _defined_id_AidPointing
#define _defined_id_AidPointing 1
const AtomicID AidPointing(-1159);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidPointing_int = -1159;
#endif
#ifndef _defined_id_AidPolarization
#define _defined_id_AidPolarization 1
const AtomicID AidPolarization(-1149);            // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidPolarization_int = -1149;
#endif
#ifndef _defined_id_AidPoly
#define _defined_id_AidPoly 1
const AtomicID AidPoly(-1178);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:33
const int AidPoly_int = -1178;
#endif
#ifndef _defined_id_AidPos
#define _defined_id_AidPos 1
const AtomicID AidPos(-1176);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidPos_int = -1176;
#endif
#ifndef _defined_id_AidProduct
#define _defined_id_AidProduct 1
const AtomicID AidProduct(-1203);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidProduct_int = -1203;
#endif
#ifndef _defined_id_AidProper
#define _defined_id_AidProper 1
const AtomicID AidProper(-1184);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidProper_int = -1184;
#endif
#ifndef _defined_id_AidRaw
#define _defined_id_AidRaw 1
const AtomicID AidRaw(-1169);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidRaw_int = -1169;
#endif
#ifndef _defined_id_AidReceptor
#define _defined_id_AidReceptor 1
const AtomicID AidReceptor(-1173);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:27
const int AidReceptor_int = -1173;
#endif
#ifndef _defined_id_AidRef
#define _defined_id_AidRef 1
const AtomicID AidRef(-1206);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidRef_int = -1206;
#endif
#ifndef _defined_id_AidResolution
#define _defined_id_AidResolution 1
const AtomicID AidResolution(-1179);              // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidResolution_int = -1179;
#endif
#ifndef _defined_id_AidResponse
#define _defined_id_AidResponse 1
const AtomicID AidResponse(-1140);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidResponse_int = -1140;
#endif
#ifndef _defined_id_AidRow
#define _defined_id_AidRow 1
const AtomicID AidRow(-1150);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidRow_int = -1150;
#endif
#ifndef _defined_id_AidSPW
#define _defined_id_AidSPW 1
const AtomicID AidSPW(-1198);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidSPW_int = -1198;
#endif
#ifndef _defined_id_AidSegment
#define _defined_id_AidSegment 1
const AtomicID AidSegment(-1134);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidSegment_int = -1134;
#endif
#ifndef _defined_id_AidSideband
#define _defined_id_AidSideband 1
const AtomicID AidSideband(-1144);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidSideband_int = -1144;
#endif
#ifndef _defined_id_AidSigma
#define _defined_id_AidSigma 1
const AtomicID AidSigma(-1133);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidSigma_int = -1133;
#endif
#ifndef _defined_id_AidSorted
#define _defined_id_AidSorted 1
const AtomicID AidSorted(-1142);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidSorted_int = -1142;
#endif
#ifndef _defined_id_AidSource
#define _defined_id_AidSource 1
const AtomicID AidSource(-1174);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidSource_int = -1174;
#endif
#ifndef _defined_id_AidStation
#define _defined_id_AidStation 1
const AtomicID AidStation(-1126);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidStation_int = -1126;
#endif
#ifndef _defined_id_AidSubtable
#define _defined_id_AidSubtable 1
const AtomicID AidSubtable(-1191);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:30
const int AidSubtable_int = -1191;
#endif
#ifndef _defined_id_AidTableFormat
#define _defined_id_AidTableFormat 1
const AtomicID AidTableFormat(-1127);             // from /home/oms/LOFAR/CEP/CPA/VisCube/src/TableFormat.h:9
const int AidTableFormat_int = -1127;
#endif
#ifndef _defined_id_AidTarget
#define _defined_id_AidTarget 1
const AtomicID AidTarget(-1157);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidTarget_int = -1157;
#endif
#ifndef _defined_id_AidTime
#define _defined_id_AidTime 1
const AtomicID AidTime(-1152);                    // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidTime_int = -1152;
#endif
#ifndef _defined_id_AidTimeslot
#define _defined_id_AidTimeslot 1
const AtomicID AidTimeslot(-1155);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidTimeslot_int = -1155;
#endif
#ifndef _defined_id_AidTotal
#define _defined_id_AidTotal 1
const AtomicID AidTotal(-1170);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:32
const int AidTotal_int = -1170;
#endif
#ifndef _defined_id_AidTracking
#define _defined_id_AidTracking 1
const AtomicID AidTracking(-1166);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:35
const int AidTracking_int = -1166;
#endif
#ifndef _defined_id_AidType
#define _defined_id_AidType 1
const AtomicID AidType(-1100);                    // from /home/oms/LOFAR/CEP/CPA/OCTOPUSSY/src/Gateways.h:19
const int AidType_int = -1100;
#endif
#ifndef _defined_id_AidUVData
#define _defined_id_AidUVData 1
const AtomicID AidUVData(-1200);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidUVData_int = -1200;
#endif
#ifndef _defined_id_AidUVSet
#define _defined_id_AidUVSet 1
const AtomicID AidUVSet(-1143);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidUVSet_int = -1143;
#endif
#ifndef _defined_id_AidUVW
#define _defined_id_AidUVW 1
const AtomicID AidUVW(-1158);                     // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:28
const int AidUVW_int = -1158;
#endif
#ifndef _defined_id_AidUnsorted
#define _defined_id_AidUnsorted 1
const AtomicID AidUnsorted(-1137);                // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:26
const int AidUnsorted_int = -1137;
#endif
#ifndef _defined_id_AidVDSID
#define _defined_id_AidVDSID 1
const AtomicID AidVDSID(-1139);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:36
const int AidVDSID_int = -1139;
#endif
#ifndef _defined_id_AidVisCube
#define _defined_id_AidVisCube 1
const AtomicID AidVisCube(-1197);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisCube.h:33
const int AidVisCube_int = -1197;
#endif
#ifndef _defined_id_AidVisCubeSet
#define _defined_id_AidVisCubeSet 1
const AtomicID AidVisCubeSet(-1180);              // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisCubeSet.h:12
const int AidVisCubeSet_int = -1180;
#endif
#ifndef _defined_id_AidVisTile
#define _defined_id_AidVisTile 1
const AtomicID AidVisTile(-1181);                 // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisTile.h:47
const int AidVisTile_int = -1181;
#endif
#ifndef _defined_id_AidWeight
#define _defined_id_AidWeight 1
const AtomicID AidWeight(-1189);                  // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:34
const int AidWeight_int = -1189;
#endif
#ifndef _defined_id_AidWidth
#define _defined_id_AidWidth 1
const AtomicID AidWidth(-1123);                   // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:31
const int AidWidth_int = -1123;
#endif
#ifndef _defined_id_AidXX
#define _defined_id_AidXX 1
const AtomicID AidXX(-1161);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidXX_int = -1161;
#endif
#ifndef _defined_id_AidXY
#define _defined_id_AidXY 1
const AtomicID AidXY(-1162);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidXY_int = -1162;
#endif
#ifndef _defined_id_AidYX
#define _defined_id_AidYX 1
const AtomicID AidYX(-1182);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidYX_int = -1182;
#endif
#ifndef _defined_id_AidYY
#define _defined_id_AidYY 1
const AtomicID AidYY(-1183);                      // from /home/oms/LOFAR/CEP/CPA/VisCube/src/VisVocabulary.h:29
const int AidYY_int = -1183;
#endif


#endif
