    // This file is generated automatically -- do not edit
    // Generated by /home/oms/LOFAR/autoconf_share/../DMI/src/build_aid_maps.pl
    #include <DMI/AtomicID.h>
    #include <DMI/TypeInfo.h>
    #include <DMI/DynamicTypeManager.h>
    #include <DMI/Packer.h>
    
#include "ColumnarTableTile.h"
BlockableObject * __construct_ColumnarTableTile (int n) { return n>0 ? new ColumnarTableTile [n] : new ColumnarTableTile; }
#include "TableFormat.h"
BlockableObject * __construct_TableFormat (int n) { return n>0 ? new TableFormat [n] : new TableFormat; }
#include "VisCube.h"
BlockableObject * __construct_VisCube (int n) { return n>0 ? new VisCube [n] : new VisCube; }
#include "VisCubeSet.h"
BlockableObject * __construct_VisCubeSet (int n) { return n>0 ? new VisCubeSet [n] : new VisCubeSet; }
#include "VisTile.h"
BlockableObject * __construct_VisTile (int n) { return n>0 ? new VisTile [n] : new VisTile; }
  
    int aidRegistry_VisCube ()
    {
      static int res = 

        AtomicID::registerId(-1037,"ColumnarTableTile")+
        TypeInfoReg::addToRegistry(-1037,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1037,__construct_ColumnarTableTile)+
        AtomicID::registerId(-1036,"TableFormat")+
        TypeInfoReg::addToRegistry(-1036,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1036,__construct_TableFormat)+
        AtomicID::registerId(-1038,"VisCube")+
        TypeInfoReg::addToRegistry(-1038,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1038,__construct_VisCube)+
        AtomicID::registerId(-1111,"Corr")+
        AtomicID::registerId(-1110,"Freq")+
        AtomicID::registerId(-1034,"VisCubeSet")+
        TypeInfoReg::addToRegistry(-1034,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1034,__construct_VisCubeSet)+
        AtomicID::registerId(-1035,"VisTile")+
        TypeInfoReg::addToRegistry(-1035,TypeInfo(TypeInfo::DYNAMIC,0))+
        DynamicTypeManager::addToRegistry(-1035,__construct_VisTile)+
        AtomicID::registerId(-1226,"UVData")+
        AtomicID::registerId(-1213,"UVSet")+
        AtomicID::registerId(-1224,"Row")+
        AtomicID::registerId(-1159,"Raw")+
        AtomicID::registerId(-1198,"Sorted")+
        AtomicID::registerId(-1170,"Unsorted")+
        AtomicID::registerId(-1218,"Time")+
        AtomicID::registerId(-1185,"Timeslot")+
        AtomicID::registerId(-1225,"Channel")+
        AtomicID::registerId(-1140,"Num")+
        AtomicID::registerId(-1141,"Control")+
        AtomicID::registerId(-1120,"MS")+
        AtomicID::registerId(-1187,"Integrate")+
        AtomicID::registerId(-1207,"Flag")+
        AtomicID::registerId(-1190,"Exposure")+
        AtomicID::registerId(-1200,"Receptor")+
        AtomicID::registerId(-1194,"Antenna")+
        AtomicID::registerId(-1220,"IFR")+
        AtomicID::registerId(-1158,"SPW")+
        AtomicID::registerId(-1162,"Field")+
        AtomicID::registerId(-1204,"UVW")+
        AtomicID::registerId(-1107,"Data")+
        AtomicID::registerId(-1165,"Integrated")+
        AtomicID::registerId(-1173,"Point")+
        AtomicID::registerId(-1212,"Source")+
        AtomicID::registerId(-1179,"Segment")+
        AtomicID::registerId(-1163,"Name")+
        AtomicID::registerId(-1133,"Header")+
        AtomicID::registerId(-1202,"Footer")+
        AtomicID::registerId(-1178,"Patch")+
        AtomicID::registerId(-1155,"XX")+
        AtomicID::registerId(-1168,"YY")+
        AtomicID::registerId(-1156,"XY")+
        AtomicID::registerId(-1166,"YX")+
        AtomicID::registerId(-1152,"Chunk")+
        AtomicID::registerId(-1169,"Indexing")+
        AtomicID::registerId(-1045,"Index")+
        AtomicID::registerId(-1210,"Subtable")+
        AtomicID::registerId(-1098,"Type")+
        AtomicID::registerId(-1167,"Station")+
        AtomicID::registerId(-1161,"Mount")+
        AtomicID::registerId(-1164,"Pos")+
        AtomicID::registerId(-1227,"Offset")+
        AtomicID::registerId(-1189,"Dish")+
        AtomicID::registerId(-1176,"Diameter")+
        AtomicID::registerId(-1196,"Feed")+
        AtomicID::registerId(-1177,"Interval")+
        AtomicID::registerId(-1215,"Polarization")+
        AtomicID::registerId(-1172,"Response")+
        AtomicID::registerId(-1182,"Angle")+
        AtomicID::registerId(-1201,"Ref")+
        AtomicID::registerId(-1186,"Width")+
        AtomicID::registerId(-1199,"Bandwidth")+
        AtomicID::registerId(-1206,"Effective")+
        AtomicID::registerId(-1175,"Resolution")+
        AtomicID::registerId(-1219,"Total")+
        AtomicID::registerId(-1157,"Net")+
        AtomicID::registerId(-1174,"Sideband")+
        AtomicID::registerId(-1228,"IF")+
        AtomicID::registerId(-1181,"Conv")+
        AtomicID::registerId(-1203,"Chain")+
        AtomicID::registerId(-1184,"Group")+
        AtomicID::registerId(-1214,"Desc")+
        AtomicID::registerId(-1222,"Code")+
        AtomicID::registerId(-1154,"Poly")+
        AtomicID::registerId(-1217,"Delay")+
        AtomicID::registerId(-1209,"Dir")+
        AtomicID::registerId(-1193,"Phase")+
        AtomicID::registerId(-1192,"Pointing")+
        AtomicID::registerId(-1180,"Lines")+
        AtomicID::registerId(-1208,"Calibration")+
        AtomicID::registerId(-1216,"Proper")+
        AtomicID::registerId(-1211,"Motion")+
        AtomicID::registerId(-1197,"Sigma")+
        AtomicID::registerId(-1223,"Weight")+
        AtomicID::registerId(-1183,"Origin")+
        AtomicID::registerId(-1205,"Target")+
        AtomicID::registerId(-1195,"Tracking")+
        AtomicID::registerId(-1221,"Beam")+
        AtomicID::registerId(-1153,"Product")+
        AtomicID::registerId(-1188,"Meas")+
        AtomicID::registerId(-1171,"Centroid")+
        AtomicID::registerId(-1191,"AIPSPP")+
        AtomicID::registerId(-1160,"Ignore")+
        AtomicID::registerId(-1121,"VDSID")+
    0;
    return res;
  }
  
  int __dum_call_registries_for_VisCube = aidRegistry_VisCube();

