# - Find wcslib
# Find the native PYTHON_NUMPY includes and library
#
#  PYTHON_NUMPY_INCLUDE_DIR - where to find numpy headers
#  PYTHON_NUMPY_LIBRARIES   - List of libraries when using wcslib.
#  PYTHON_NUMPY_FOUND       - True if wcslib found.

IF (PYTHON_NUMPY_INCLUDE_DIR)
    # Already in cache, be silent
    SET(PYTHON_NUMPY_FIND_QUIETLY TRUE)
ENDIF (PYTHON_NUMPY_INCLUDE_DIR)

FIND_PACKAGE(PythonInterp)

EXECUTE_PROCESS(COMMAND ${PYTHON_EXECUTABLE} -c "import numpy;print numpy.get_include()"
  OUTPUT_VARIABLE PYTHON_NUMPY_INCLUDE_DIR RESULT_VARIABLE NUMPY_FIND_RESULT
  OUTPUT_STRIP_TRAILING_WHITESPACE)

IF ( ${NUMPY_FIND_RESULT} )
  MESSAGE( "python -c 'import numpy' appears to fail. Is numpy installed?" )
  SET(PYTHON_NUMPY_INCLUDE_DIR) 
  FIND_PATH(PYTHON_NUMPY_INCLUDE_DIR numpy)
ENDIF ( ${NUMPY_FIND_RESULT} )

#SET(PYTHON_NUMPY_NAMES
#    )
#FOREACH( lib ${PYTHON_NUMPY_NAMES} )
#FIND_LIBRARY(PYTHON_NUMPY_LIBRARY_${lib} NAMES ${lib} )
#    LIST(APPEND PYTHON_NUMPY_LIBRARIES ${PYTHON_NUMPY_LIBRARY_${lib}})
#ENDFOREACH(lib)

# handle the QUIETLY and REQUIRED arguments and set PYTHON_NUMPY_FOUND to TRUE if.
# all listed variables are TRUE
INCLUDE(FindPackageHandleCompat)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(PYTHON_NUMPY DEFAULT_MSG PYTHON_NUMPY_LIBRARIES PYTHON_NUMPY_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PYTHON_NUMPY DEFAULT_MSG PYTHON_NUMPY_INCLUDE_DIR)

#IF(NOT PYTHON_NUMPY_FOUND)
#    SET( PYTHON_NUMPY_LIBRARIES )
#ENDIF(NOT PYTHON_NUMPY_FOUND)

MARK_AS_ADVANCED( PYTHON_NUMPY_LIBRARIES PYTHON_NUMPY_INCLUDE_DIR )

