#!/usr/bin/python

from qt import QPixmap

# A QPixMap wrapper defers initialization of a pixmap until the pixmap
# is actually retrieved with the pm() method for the first time.
class QPixmapWrapper(object):
  def __init__(self,xpmstr):
    self._xpmstr = xpmstr;
    self._pm = None;
  def pm (self):
    if self._pm is None:
      self._pm = QPixmap(self._xpmstr);
    return self._pm;

exclaim = QPixmapWrapper([ "14 14 3 1",
          "       c None",
          ".      c red",
          "X      c yellow",
          "              ",
          "     ....     ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "     ....     ",
          "     ....     ",
          "      ..      ",
          "              ",
          "      ..      ",
          "     ....     ",
          "      ..      " ]);
          
cancel = QPixmapWrapper(["16 16 5 1",
                         "p c #800000",
                         ". c #400000",
                         "X c #FF0000",
                         "o c #C00000",
                         "  c None",
                         "                ",
                         "                ",
                         "            X   ",
                         "    XX     Xoo  ",
                         "   XooXX  Xoo.  ",
                         "     pooXooo.   ",
                         "      poooo.    ",
                         "       XooX     ",
                         "      XoooX     ",
                         "     Xo. poX    ",
                         "     X.   po    ",
                         "    Xo     po   ",
                         "    X.      o   ",
                         "    X           ",
                         "                ",
                         "                " ])

check = QPixmapWrapper(["16 14 8 1",
                        "  c #000000",
                        ". c #400000",
                        "X c None",
                        "o c #00C000",
                        "O c #008000",
                        "+ c #C0FFC0",
                        "@ c #004000",
                        "# c None",
                        "XXXXXXXXXXXXXXX+",
                        "XXXXXXXXXXXXXX+o",
                        "XXXXXXXXXXXXX+oO",
                        "XXXXXXXXXXXX+oO@",
                        "XXXXXXXXXXX+oO@ ",
                        "XX+OXXXXXX+oO@ X",
                        "X+ooOXXXX+oO@.XX",
                        " @OooOXX+oO@ XXX",
                        "X @OooO+oO@.XXXX",
                        "XX.@OoooO@.XXXXX",
                        "XXX @OoO@ XXXXXX",
                        "XXXX @O@ XXXXXXX",
                        "XXXXX . XXXXXXXX",
                        "XXXXXXXXXXXXXXXX" ]);
          
pause_green = QPixmapWrapper(["22 15 4 1",
                       "  c None",
                       ". c #303030",
                       "X c #00FF00",
                       "o c None",
                       "                      ",
                       "      XXX.   XXX.     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX.   XXX.      ",
                       "                      ",
                       "                      " ]);
pause_normal = QPixmapWrapper(["22 15 4 1",
                       "  c None",
                       ". c #303030",
                       "X c #0000FF",
                       "o c None",
                       "                      ",
                       "      XXX.   XXX.     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX..  XXX..     ",
                       "     XXX.   XXX.      ",
                       "                      ",
                       "                      " ]);


refresh = QPixmapWrapper([ "16 16 7 1",
                   "  c #000000",
                   ". c #00FF00",
                   "X c None",
                   "o c #00C000",
                   "O c #008000",
                   "+ c #004000",
                   "@ c None",
                   "XXXXXX     XXXXX",
                   "XXXX  .oo  + XXX",
                   "XXX .ooO XX   XX",
                   "XXX ooO XXXXX XX",
                   "XX .oO XXXXXXX X",
                   "XX ooO XXXXXXXXX",
                   " ..ooooO XX  XXX",
                   "X .oooO XX    XX",
                   "XX .oO XX      X",
                   "XXX O XX        ",
                   "XXXX XXXXX    XX",
                   "X XXXXXXXX    XX",
                   "XX XXXXXX    XXX",
                   "XX   XX      XXX",
                   "XXX         XXXX",
                   "XXXXX     XXXXXX"  ]);


pin_up = QPixmapWrapper([ "16 16 5 1",
                          "  c None",
                          ". c #A0A0A0",
                          "X c #707070",
                          "o c #FFFFFF",
                          "O c None",
                          "                ",
                          "                ",
                          "                ",
                          "      XX     X  ",
                          "      XoX   XX  ",
                          "      XooXXXoX  ",
                          "ooooooX.o.o.oX  ",
                          "......X.o.o.oX  ",
                          "XXXXXXX..X.X.X  ",
                          "      X.XXXXXX  ",
                          "      XXX   XX  ",
                          "      XX     X  ",
                          "                ",
                          "                ",
                          "                ",
                          "                "]);

pin_down = QPixmapWrapper([ "16 16 5 1",
                            "  c None",
                            ". c #A0A0A0",
                            "X c #707070",
                            "o c #FFFFFF",
                            "O c None",
                            "                ",
                            "                ",
                            "        XXXX    ",
                            "      XXooooX   ",
                            "    XXXooooooX  ",
                            "    XoXooo...X  ",
                            "   XooXoo...XX  ",
                            "   XooXXo..XXX  ",
                            "   XooooXXXXX   ",
                            "   Xooo....XX   ",
                            "    Xo....XXX   ",
                            "    X....XXX    ",
                            "     XXXXXX     ",
                            "                ",
                            "                ",
                            "                "]);

matrix = QPixmapWrapper(["16 16 4 1",
                         "  c None",
                         ". c None",
                         "X c #800080",
                         "o c None",
                         "... ... ....... ",
                         ".XXXX XXXX.XXXX ",
                         ".X. X.X .X.X..X ",
                         " X  X X  X X  X ",
                         ".XXXX.XXXX.XXXX ",
                         ". . . . . . . . ",
                         ".XXXX.XXXX.XXXX ",
                         " X  X X  X.X  X ",
                         ".X..X.X..X.X..X ",
                         ".XXXX XXXX.XXXX.",
                         "... ... ... ... ",
                         " XXXX XXXX XXXX ",
                         ".X. X.X .X.X..X ",
                         ".X. X.X .X.X. X ",
                         ".XXXX.XXXX.XXXX ",
                         "                "
                         ]);

