#!/usr/bin/python

from qt import QPixmap,QIconSet

# A QPixMap wrapper defers initialization of a pixmap until the pixmap
# is actually retrieved with the pm() method for the first time.
class QPixmapWrapper(object):
  def __init__(self,xpmstr):
    self._xpmstr = xpmstr;
    self._pm = None;
    self._iconset = None;
  def pm (self):
    if self._pm is None:
      self._pm = QPixmap(self._xpmstr);
    return self._pm;
  def iconset (self):
    if self._iconset is None:
      self._iconset = QIconSet(self.pm());
    return self._iconset;

exclaim = QPixmapWrapper([ "14 14 3 1",
          "       c None",
          ".      c red",
          "X      c yellow",
          "              ",
          "     ....     ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "    ......    ",
          "     ....     ",
          "     ....     ",
          "      ..      ",
          "              ",
          "      ..      ",
          "     ....     ",
          "      ..      " ]);
          
cancel = QPixmapWrapper(["16 16 5 1",
                         "p c #800000",
                         ". c #400000",
                         "X c #FF0000",
                         "o c #C00000",
                         "  c None",
                         "                ",
                         "                ",
                         "            X   ",
                         "    XX     Xoo  ",
                         "   XooXX  Xoo.  ",
                         "     pooXooo.   ",
                         "      poooo.    ",
                         "       XooX     ",
                         "      XoooX     ",
                         "     Xo. poX    ",
                         "     X.   po    ",
                         "    Xo     po   ",
                         "    X.      o   ",
                         "    X           ",
                         "                ",
                         "                " ])

check = QPixmapWrapper(["16 14 8 1",
                        "  c #000000",
                        ". c #400000",
                        "X c None",
                        "o c #00C000",
                        "O c #008000",
                        "+ c #C0FFC0",
                        "@ c #004000",
                        "# c None",
                        "XXXXXXXXXXXXXXX+",
                        "XXXXXXXXXXXXXX+o",
                        "XXXXXXXXXXXXX+oO",
                        "XXXXXXXXXXXX+oO@",
                        "XXXXXXXXXXX+oO@ ",
                        "XX+OXXXXXX+oO@ X",
                        "X+ooOXXXX+oO@.XX",
                        " @OooOXX+oO@ XXX",
                        "X @OooO+oO@.XXXX",
                        "XX.@OoooO@.XXXXX",
                        "XXX @OoO@ XXXXXX",
                        "XXXX @O@ XXXXXXX",
                        "XXXXX . XXXXXXXX",
                        "XXXXXXXXXXXXXXXX" ]);

pause_normal = QPixmapWrapper(["16 16 95 2",
                       "   c None",
                       " . c #CDDAF4",
                       " X c #3A64B3",
                       " o c #4887FC",
                       " O c #3B66B7",
                       " + c #3269CF",
                       " @ c #6696EE",
                       " # c #5183E0",
                       " $ c #6494EC",
                       " % c #C4D4F1",
                       " & c #6C94E0",
                       " * c #3269D2",
                       " = c #3B80FF",
                       " - c #90B1EC",
                       " ; c #3B65B3",
                       " : c #3472E4",
                       " > c #656565",
                       " , c #5E88D5",
                       " < c #4686FC",
                       " 1 c #4A7FE2",
                       " 2 c #A3BCEA",
                       " 3 c #3569CA",
                       " 4 c #4987F8",
                       " 5 c #4E6286",
                       " 6 c #B8CCEE",
                       " 7 c #3C81FF",
                       " 8 c #3471E3",
                       " 9 c #3C66B6",
                       " 0 c #A8C2F5",
                       " q c #3E70CF",
                       " w c #326CD7",
                       " e c #486190",
                       " r c #7EA3E6",
                       " t c #5789E4",
                       " y c #3665BD",
                       " u c #8FADE6",
                       " i c #3269D0",
                       " p c #DCE6F6",
                       " a c #4D648E",
                       " s c #3D82FF",
                       " d c #8EADE8",
                       " f c #4A80E4",
                       " g c #356ACC",
                       " h c #3368CA",
                       " j c #5A8AE3",
                       " k c #3D64AC",
                       " l c #4980E6",
                       " z c #6E95DC",
                       " x c #3268CC",
                       " c c #4888FC",
                       " v c #4686FA",
                       " b c #3467C4",
                       " n c #D4E0F4",
                       " m c #3472E5",
                       " M c #EBF0FA",
                       " N c #3776EB",
                       " B c #8CACE5",
                       " V c #326AD2",
                       " C c #A1BAE9",
                       " Z c #B9CCF0",
                       " A c #B7CAEE",
                       " S c #3765B9",
                       " D c #3B66B6",
                       " F c #5B88DC",
                       " G c #6E99E8",
                       " H c #3E62A5",
                       " J c #3269CE",
                       " K c #4687FC",
                       " L c #4F6184",
                       " P c #202020",
                       " I c #3269D1",
                       " U c #799FE5",
                       " Y c #E4EBF8",
                       " T c #326BD4",
                       " R c #346ACC",
                       " E c #3268CA",
                       " W c #658EDB",
                       " Q c #3572E4",
                       " ! c #CBD9F3",
                       " ~ c #3E71CF",
                       " ^ c #E1E9F8",
                       " / c #3268CD",
                       " ( c #4083FF",
                       " ) c #3766BE",
                       " _ c #3873E0",
                       " ` c #97B3E4",
                       " ' c #8EACE5",
                       " ] c #447CE5",
                       " [ c #3676EB",
                       " { c #F2F5FB",
                       " } c #749DE9",
                       " | c #8DACE7",
                       ".  c #326AD3",
                       ".. c #3469CB",
                       ".X c None",
                       "           I + / x E y          ",
                       "       I * w m # F : T h S      ",
                       "     I.  l 0 Y { { M Z t J D    ",
                       "   i V $ n ^ ^ ^ ^ ^ ^ p U J H  ",
                       "   + l % u u u . . u u u ! j b >",
                       " x T - 6 P P P 6 6 P P P A `.  e",
                       " x _ C 2 P P P 2 2 P P P 4 = 8 X",
                       " x 1 B u P P P ' ' P P P 7 = [ O",
                       " x ] G } P P P 7 v P P P 7 7 N 9",
                       " E Q < < P P P 7 7 P P P s ( : k",
                       " y T o c P P P 7 7 P P P K o.  L",
                       "   h f @ P P P @ @ P P P @ f ) >",
                       "   S R & r r r r r r r r &.. 5 >",
                       "     ; g W | d d d d | W 3 a >  ",
                       "       H b ~ , z z , q ) 5 >    ",
                       "         > e X O 9 k L > >      " ]);

pause_green = QPixmapWrapper(["16 16 94 2",
                         "Qt c None",
                         ".P c #ffff00",
                         ".d c #3268ca",
                         ".c c #3268cc",
                         ".b c #3268cd",
                         ".w c #3269ce",
                         ".a c #3269cf",
                         ".y c #3269d0",
                         ".# c #3269d1",
                         ".f c #3269d2",
                         ".z c #326ad2",
                         ".o c #326ad3",
                         ".l c #326bd4",
                         ".g c #326cd7",
                         ".m c #3368ca",
                         ".L c #3467c4",
                         "#p c #3469cb",
                         "#m c #346acc",
                         ".Y c #3471e3",
                         ".k c #3472e4",
                         ".h c #3472e5",
                         "#w c #3569ca",
                         "#s c #356acc",
                         "#a c #3572e4",
                         ".e c #3665bd",
                         ".4 c #3676eb",
                         ".n c #3765b9",
                         "#l c #3766be",
                         "#. c #3776eb",
                         ".T c #3873e0",
                         ".Z c #3a64b3",
                         "#r c #3b65b3",
                         ".x c #3b66b6",
                         ".5 c #3b66b7",
                         ".X c #3b80ff",
                         "## c #3c66b6",
                         ".3 c #3c81ff",
                         "#e c #3d64ac",
                         "#c c #3d82ff",
                         ".F c #3e62a5",
                         "#B c #3e70cf",
                         "#y c #3e71cf",
                         "#d c #4083ff",
                         ".6 c #447ce5",
                         ".9 c #4686fa",
                         "#b c #4686fc",
                         "#h c #4687fc",
                         ".S c #486190",
                         "#f c #4887fc",
                         "#g c #4888fc",
                         ".p c #4980e6",
                         ".W c #4987f8",
                         ".0 c #4a7fe2",
                         "#j c #4a80e4",
                         "#x c #4d648e",
                         "#q c #4e6286",
                         "#i c #4f6184",
                         ".i c #5183e0",
                         ".v c #5789e4",
                         ".K c #5a8ae3",
                         ".j c #5b88dc",
                         "#z c #5e88d5",
                         ".A c #6494ec",
                         ".M c #656565",
                         "#t c #658edb",
                         "#k c #6696ee",
                         "#n c #6c94e0",
                         "#A c #6e95dc",
                         ".7 c #6e99e8",
                         ".8 c #749de9",
                         ".E c #799fe5",
                         "#o c #7ea3e6",
                         ".1 c #8cace5",
                         "#u c #8dace7",
                         ".2 c #8eace5",
                         "#v c #8eade8",
                         ".H c #8fade6",
                         ".N c #90b1ec",
                         ".R c #97b3e4",
                         ".U c #a1bae9",
                         ".V c #a3bcea",
                         ".q c #a8c2f5",
                         ".Q c #b7caee",
                         ".O c #b8ccee",
                         ".u c #b9ccf0",
                         ".G c #c4d4f1",
                         ".J c #cbd9f3",
                         ".I c #cddaf4",
                         ".B c #d4e0f4",
                         ".D c #dce6f6",
                         ".C c #e1e9f8",
                         ".r c #e4ebf8",
                         ".t c #ebf0fa",
                         ".s c #f2f5fb",
                         "QtQtQtQtQt.#.a.b.c.d.eQtQtQtQtQt",
                         "QtQtQt.#.f.g.h.i.j.k.l.m.nQtQtQt",
                         "QtQt.#.o.p.q.r.s.s.t.u.v.w.xQtQt",
                         "Qt.y.z.A.B.C.C.C.C.C.C.D.E.w.FQt",
                         "Qt.a.p.G.H.H.H.I.I.H.H.H.J.K.L.M",
                         ".c.l.N.O.P.P.P.O.O.P.P.P.Q.R.o.S",
                         ".c.T.U.V.P.P.P.V.V.P.P.P.W.X.Y.Z",
                         ".c.0.1.H.P.P.P.2.2.P.P.P.3.X.4.5",
                         ".c.6.7.8.P.P.P.3.9.P.P.P.3.3#.##",
                         ".d#a#b#b.P.P.P.3.3.P.P.P#c#d.k#e",
                         ".e.l#f#g.P.P.P.3.3.P.P.P#h#f.o#i",
                         "Qt.m#j#k.P.P.P#k#k.P.P.P#k#j#l.M",
                         "Qt.n#m#n#o#o#o#o#o#o#o#o#n#p#q.M",
                         "QtQt#r#s#t#u#v#v#v#v#u#t#w#x.MQt",
                         "QtQtQt.F.L#y#z#A#A#z#B#l#q.MQtQt",
                         "QtQtQtQt.M.S.Z.5###e#i.M.MQtQtQt" ]);
          
##pause_green = QPixmapWrapper(["22 15 4 1",
##                       "  c None",
##                       ". c #303030",
##                       "X c #00FF00",
##                       "o c None",
##                       "                      ",
##                       "      XXX.   XXX.     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX.   XXX.      ",
##                       "                      ",
##                       "                      " ]);
##pause_normal = QPixmapWrapper(["22 15 4 1",
##                       "  c None",
##                       ". c #303030",
##                       "X c #0000FF",
##                       "o c None",
##                       "                      ",
##                       "      XXX.   XXX.     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX..  XXX..     ",
##                       "     XXX.   XXX.      ",
##                       "                      ",
##                       "                      " ]);
##

refresh = QPixmapWrapper([ "16 16 7 1",
                   "  c #000000",
                   ". c #00FF00",
                   "X c None",
                   "o c #00C000",
                   "O c #008000",
                   "+ c #004000",
                   "@ c None",
                   "XXXXXX     XXXXX",
                   "XXXX  .oo  + XXX",
                   "XXX .ooO XX   XX",
                   "XXX ooO XXXXX XX",
                   "XX .oO XXXXXXX X",
                   "XX ooO XXXXXXXXX",
                   " ..ooooO XX  XXX",
                   "X .oooO XX    XX",
                   "XX .oO XX      X",
                   "XXX O XX        ",
                   "XXXX XXXXX    XX",
                   "X XXXXXXXX    XX",
                   "XX XXXXXX    XXX",
                   "XX   XX      XXX",
                   "XXX         XXXX",
                   "XXXXX     XXXXXX"  ]);


pin_up = QPixmapWrapper([ "16 16 5 1",
                          "  c None",
                          ". c #A0A0A0",
                          "X c #707070",
                          "o c #FFFFFF",
                          "O c None",
                          "                ",
                          "                ",
                          "                ",
                          "      XX     X  ",
                          "      XoX   XX  ",
                          "      XooXXXoX  ",
                          "ooooooX.o.o.oX  ",
                          "......X.o.o.oX  ",
                          "XXXXXXX..X.X.X  ",
                          "      X.XXXXXX  ",
                          "      XXX   XX  ",
                          "      XX     X  ",
                          "                ",
                          "                ",
                          "                ",
                          "                "]);

pin_down = QPixmapWrapper([ "16 16 5 1",
                            "  c None",
                            ". c #A0A0A0",
                            "X c #707070",
                            "o c #FFFFFF",
                            "O c None",
                            "                ",
                            "                ",
                            "        XXXX    ",
                            "      XXooooX   ",
                            "    XXXooooooX  ",
                            "    XoXooo...X  ",
                            "   XooXoo...XX  ",
                            "   XooXXo..XXX  ",
                            "   XooooXXXXX   ",
                            "   Xooo....XX   ",
                            "    Xo....XXX   ",
                            "    X....XXX    ",
                            "     XXXXXX     ",
                            "                ",
                            "                ",
                            "                "]);

matrix = QPixmapWrapper(["16 16 4 1",
                         "  c None",
                         ". c None",
                         "X c #800080",
                         "o c None",
                         "... ... ....... ",
                         ".XXXX XXXX.XXXX ",
                         ".X. X.X .X.X..X ",
                         " X  X X  X X  X ",
                         ".XXXX.XXXX.XXXX ",
                         ". . . . . . . . ",
                         ".XXXX.XXXX.XXXX ",
                         " X  X X  X.X  X ",
                         ".X..X.X..X.X..X ",
                         ".XXXX XXXX.XXXX.",
                         "... ... ... ... ",
                         " XXXX XXXX XXXX ",
                         ".X. X.X .X.X..X ",
                         ".X. X.X .X.X. X ",
                         ".XXXX.XXXX.XXXX ",
                         "                "
                         ]);

view_right = QPixmapWrapper(["16 16 48 1",
                             "  c None",
                             ". c #ADADAD",
                             "X c #A5A5A5",
                             "o c #A1A1A1",
                             "O c #C1C10A",
                             "+ c #FFFF85",
                             "@ c #494949",
                             "# c #FAFAFA",
                             "$ c #F6F6F6",
                             "% c #F2F2F2",
                             "& c #F0F0F0",
                             "* c #EEEEEE",
                             "= c #ECECEC",
                             "- c #EAEAEA",
                             "; c #E8E8E8",
                             ": c #E6E6E6",
                             "> c #E4E4E4",
                             ", c #E2E2E2",
                             "< c #E0E0E0",
                             "1 c #DADADA",
                             "2 c #D6D6D6",
                             "3 c #CCCCCC",
                             "4 c #C8C8C8",
                             "5 c #C6C6C6",
                             "6 c #C0C000",
                             "7 c #AEAEAE",
                             "8 c #ACACAC",
                             "9 c #A0A0A0",
                             "0 c #585858",
                             "q c #FFFFFF",
                             "w c #FFFF00",
                             "e c #FFFFC0",
                             "r c #F9F9F9",
                             "t c #F5F5F5",
                             "y c #F3F3F3",
                             "u c #F1F1F1",
                             "i c #EDEDED",
                             "p c #E9E9E9",
                             "a c #E5E5E5",
                             "s c #303030",
                             "d c #E1E1E1",
                             "f c #DFDFDF",
                             "g c #D9D9D9",
                             "h c #D3D3D3",
                             "j c #CFCFCF",
                             "k c #C9C9C9",
                             "l c #C7C7C7",
                             "z c None",
                             "                ",
                             " 0000000000000@ ",
                             " 02gg1q0ohj3k5s ",
                             " 0gyt$q08=;><5s ",
                             " 0gtr#q0.ipadls ",
                             " 01$#qq07*-:,4s ",
                             " 0gtr#q0.ipadls ",
                             " 0gyt$q08= +<5s ",
                             " 02&u%q +- wf + ",
                             " 0h=i*q0 w6w6ws ",
                             " 0j;p-q0XOe+e6s ",
                             " 03>a: +ww+q+ww+",
                             " 0k<d,q096e+e6s ",
                             " 055l4q0 w6w6ws ",
                             " @sssss +s ws + ",
                             "           +    "]);

view_split = QPixmapWrapper(["16 16 40 1",
                             "  c None",
                             ". c #A1A1A1",
                             "X c #979797",
                             "o c #494949",
                             "O c #FAFAFA",
                             "+ c #F6F6F6",
                             "@ c #EEEEEE",
                             "# c #ECECEC",
                             "$ c #EAEAEA",
                             "% c #E8E8E8",
                             "& c #E6E6E6",
                             "* c #E4E4E4",
                             "= c #E2E2E2",
                             "- c #E0E0E0",
                             "; c #DEDEDE",
                             ": c #DCDCDC",
                             "> c #DADADA",
                             ", c #D6D6D6",
                             "< c #CCCCCC",
                             "1 c #C8C8C8",
                             "2 c #C6C6C6",
                             "3 c #ACACAC",
                             "4 c #585858",
                             "5 c #FFFFFF",
                             "6 c #F9F9F9",
                             "7 c #F5F5F5",
                             "8 c #F3F3F3",
                             "9 c #EDEDED",
                             "0 c #E9E9E9",
                             "q c #E7E7E7",
                             "w c #E5E5E5",
                             "e c #303030",
                             "r c #E1E1E1",
                             "t c #DDDDDD",
                             "y c #D9D9D9",
                             "u c #D3D3D3",
                             "i c #CFCFCF",
                             "p c #C9C9C9",
                             "a c #C7C7C7",
                             "s c None",
                             "                ",
                             " 4444444444444o ",
                             " 4,yy>543ui<p2e ",
                             " 4y87+54.#%*-2e ",
                             " 4y76O54.90wrae ",
                             " 4>+O554.@$&=1e ",
                             " 4555554.55555e ",
                             " 4444444444444e ",
                             " 43....4.....3e ",
                             " 4u#9@54.q*rt2e ",
                             " 4i%0$54.*r;:2e ",
                             " 4<*w&54.r;::2e ",
                             " 4p-r=54.t:::2e ",
                             " 422a154X22222e ",
                             " oeeeeeeeeeeeee ",
                             "                "]);                             
                             
remove = QPixmapWrapper(["16 16 15 1",
                         "  c #000000",
                         ". c #E4E4E4",
                         "X c #DEDEDE",
                         "o c #D4D4D4",
                         "O c #CECECE",
                         "+ c #BEBEBE",
                         "@ c #6E6E6E",
                         "# c #FFFFFF",
                         "$ c #E9E9E9",
                         "% c #D9D9D9",
                         "& c #C9C9C9",
                         "* c #C3C3C3",
                         "= c #B9B9B9",
                         "- c #B7B7B7",
                         "; c None",
                         "---------------#",
                         "-@@@@@@@@@@@@@@#",
                         "-@###########-@#",
                         "-@#$$$$$$$$$$-@#",
                         "-@#.. .... ..-@#",
                         "-@#X   XX   X-@#",
                         "-@#%%      %%-@#",
                         "-@#ooo    ooo-@#",
                         "-@#OOO    OOO-@#",
                         "-@#&&      &&-@#",
                         "-@#*   **   *-@#",
                         "-@#++ ++++ ++-@#",
                         "-@#==========-@#",
                         "-@------------@#",
                         "-@@@@@@@@@@@@@@#",
                         "################" ]);
                             
                             
tab_remove = QPixmapWrapper(["16 16 15 1",
                             "  c None",
                             ". c #CD4135",
                             "X c #999999",
                             "o c #820202",
                             "O c #800000",
                             "+ c #E8786C",
                             "@ c #FFC0C0",
                             "# c #D6D6D6",
                             "$ c #C8C8C8",
                             "% c #9E9E9E",
                             "& c #8C8C8C",
                             "* c #FFFFFF",
                             "= c #F1F1F1",
                             "- c #E3E3E3",
                             "; c None",
                             "                ",
                             "                ",
                             "     +@  @+     ",
                             "     o.@@.o     ",
                             "      o..o      ",
                             "      @..@      ",
                             "     @.oO.@     ",
                             "    @+o  o.     ",
                             "     o    o     ",
                             "                ",
                             "  *===X   %%%%% ",
                             "  ****$   %%%%% ",
                             " *=====X %%%%%%%",
                             "$&&&&&&&&&&&&&&&",
                             "$&**************",
                             "$&**************"  ]);
                             
tab_new = QPixmapWrapper(["16 16 16 1",
                          "  c None",
                          ". c #999999",
                          "X c #C1C10A",
                          "o c #FFFF85",
                          "O c #494600",
                          "+ c #D6D6D6",
                          "@ c #C8C8C8",
                          "# c #C0C000",
                          "$ c #9E9E9E",
                          "% c #8C8C8C",
                          "& c #FFFFFF",
                          "* c #FFFF00",
                          "= c #FFFFC0",
                          "- c #F1F1F1",
                          "; c #E3E3E3",
                          ": c None",
                          "        O       ",
                          "     O OoO O    ",
                          "    OoOO*OOoO   ",
                          "     O*#*#*O    ",
                          "    OOX=o=#OO   ",
                          "   Oo**o&o**oO  ",
                          "    OO#=o=#OO   ",
                          "     O*#*#*O    ",
                          "    OoOO*OOoO   ",
                          "     O OoO O    ",
                          "  $$$$$ O &---. ",
                          "  $$$$$   &&&&@ ",
                          " $$$$$$$ &-----.",
                          "@%%%%%%%%%%%%%%%",
                          "@%&&&&&&&&&&&&&&",
                          "@%&&&&&&&&&&&&&&" ]);

magnify = QPixmapWrapper(["16 16 9 1",
                         "  c #000000",
                         ". c #800000",
                         "X c #DCDCDC",
                         "o c #FF8000",
                         "O c #A0A0A0",
                         "+ c #C05800",
                         "@ c None",
                         "# c #C3C3C3",
                         "$ c None",
                         "@@@@@   @@@@@@@@",
                         "@@@  O#O  @@@@@@",
                         "@@ O##X##O @@@@@",
                         "@ O#X@@XX#O @@@@",
                         "@ #X@XXXXX# @@@@",
                         " O#@XXXXXX#O @@@",
                         " #X@XXXXX#X# @@@",
                         " O#XXXXXX##O @@@",
                         "@ #XXXXX#X# @@@@",
                         "@ O#XX##X#O @@@@",
                         "@@ O##X##O . @@@",
                         "@@@  O#O  .o. @@",
                         "@@@@@   @@ .o. @",
                         "@@@@@@@@@@@ .+. ",
                         "@@@@@@@@@@@@ . @",
                         "@@@@@@@@@@@@@ @@" ]);


eventnew = QPixmapWrapper(["16 16 7 1",
                           "  c None",
                           ". c #87852B",
                           "X c #918F2E",
                           "o c #FFFFFF",
                           "O c #FFFF00",
                           "+ c #FFFFC0",
                           "@ c None",
                           "                ",
                           "                ",
                           "        O       ",
                           "   O    O.   O  ",
                           "    O. +O. OO   ",
                           "    OO.XOX+O.   ",
                           "     +OOOOO.    ",
                           "   ..XOo+oOX+   ",
                           "  OOOOO+o+OOOOO ",
                           "    +XOo+oOX..  ",
                           "     .OOOOO+    ",
                           "    .O+XOX.OO   ",
                           "    OO .O+ .O   ",
                           "   O   .O    O  ",
                           "        O       ",
                           "                " ]);


view_tree = QPixmapWrapper(["16 16 5 1",
                            "  c #000000",
                            ". c None",
                            "X c #303030",
                            "o c #FFDCA8",
                            "O c None",
                            " ...............",
                            " ...............",
                            " ...XXX ........",
                            " ...X.. ........",
                            "   .X.o ..  .   ",
                            " ...    ........",
                            " ...............",
                            " ...............",
                            " ...............",
                            " ...XXX ........",
                            " ...X.. ........",
                            "   .X.o ..  .   ",
                            "....    ........",
                            "................",
                            "................",
                            "................"]);


precplus = QPixmapWrapper(["16 16 3 1",
                           "# c #000000",
                           ". c None",
                           "a c #ffffff",
                           "........##...##.",
                           "..#....##.#.##.#",
                           ".##....##.#.##.#",
                           "#####..##.#.##.#",
                           ".##....##.#.##.#",
                           "..#....##.#.##.#",
                           "....##..##...##.",
                           "....##..........",
                           ".....#..########",
                           "........#aaaaaaa",
                           "........#aaa#aaa",
                           "........#aaa#aaa",
                           "........#a#####a",
                           "........#aaa#aaa",
                           "........#aaa#aaa",
                           "........#aaaaaaa"]);
                           
precminus = QPixmapWrapper(["16 16 3 1",
                            "# c #000000",
                            ". c None",
                            "a c #ffffff",
                            ".........##.....",
                            "...#....##.#....",
                            "...##...##.#....",
                            "######..##.#....",
                            "...##...##.#....",
                            "...#....##.#....",
                            ".....##..##.....",
                            ".....##.........",
                            "......#.########",
                            "........#aaaaaaa",
                            "........#aaaaaaa",
                            "........#aaaaaaa",
                            "........#a#####a",
                            "........#aaaaaaa",
                            "........#aaaaaaa",
                            "........#aaaaaaa" ]);



bars3d = QPixmapWrapper(["16 16 6 1",
                         "# c #000000",
                         "b c #00d300",
                         "a c #00ff00",
                         "d c #9595d6",
                         "c c #c0c0ff",
                         ". c None",
                         "................",
                         ".......###......",
                         "......#aa#.###..",
                         ".....#aa###aa#..",
                         ".....###b#aa##..",
                         ".....#a#####b#..",
                         ".....##cc#a#b###",
                         ".....#cc##a##aa#",
                         "...#####d#a#aa##",
                         "..#cc#c#d#a###b#",
                         ".#cc##c#d##cc#b#",
                         ".###d#c#d#cc##b#",
                         ".#c#d#c#d###d##.",
                         ".#c#d#c#d#c#d#..",
                         ".#c#d#c#d#c##...",
                         ".###########...." ]);

areas3d = QPixmapWrapper(["16 16 6 1",
                          "# c #000000",
                          "a c #00d300",
                          "b c #00ff00",
                          "c c #9595d6",
                          "d c #c0c0ff",
                          ". c None",
                          "......#.........",
                          ".....#a#........",
                          "....#aaa#.......",
                          "...#b#aaa###....",
                          "...#bb#aaaaa##..",
                          "..#c#bb###aaaa#.",
                          ".#ccc#bbbb##aa#.",
                          "#d#ccc#bbbbb#a#.",
                          "#dd#ccc#bbbb#aa#",
                          "#ddd#ccc###b#aaa",
                          "#dddd#ccccc###aa",
                          "#ddddd###cccc##a",
                          "#dddddddd##ccc##",
                          "#dddddddddd#ccc#",
                          "#ddddddddddd#c#.",
                          "##############.." ]);

treeviewoblique = QPixmapWrapper(["16 16 44 1",
                          "h c #000000",
                          ". c #FAF7F2",
                          "X c #E8D4BC",
                          "o c #FDFBF8",
                          "O c #F0E3D4",
                          "+ c #F7F0E8",
                          "@ c #EBDAC5",
                          "# c #F3E9DD",
                          "$ c #FAF6F1",
                          "% c #EAD7C0",
                          "& c #FDFCFA",
                          "* c #EDDDC9",
                          "= c #F3E8DC",
                          "- c #F9F5EF",
                          "; c #E7D2B9",
                          ": c #DCDCDC",
                          "> c #F6EEE5",
                          ", c #EAD8C2",
                          "< c #E6CFB4",
                          "1 c #F5EBE0",
                          "2 c #E9D5BD",
                          "3 c #FCFAF7",
                          "4 c #A0A0A0",
                          "5 c #F2E6D9",
                          "6 c #F8F3EC",
                          "7 c #808080",
                          "8 c #EFE1CF",
                          "9 c #F5ECE2",
                          "0 c #E5CDB1",
                          "q c #FEFDFB",
                          "w c #585858",
                          "e c #F1E5D7",
                          "r c #F8F2EB",
                          "t c #FFFFFF",
                          "y c #EFE0CE",
                          "u c #FBF8F4",
                          "i c #303030",
                          "p c #EFE2D1",
                          "a c #F1E4D6",
                          "s c #F7F1E9",
                          "d c #FEFEFD",
                          "f c #C3C3C3",
                          "g c #EEDFCC",
                          "  c None",
                          "         ii     ",
                          "       iw.ri    ",
                          "     iwt3-+w    ",
                          "   iwttqu6>#i   ",
                          " iw:tttous7hw   ",
                          "itthtowsshfe8i  ",
                          "itt7:hhw1==Ogw  ",
                          " wtthhhf+15p*,i ",
                          " itt7:u6>#yy7 w ",
                          "  wtth$ow#*h4X<i",
                          "  itd7:hhwg%%;0i",
                          "   w&.hhhfg@2wi ",
                          "   i3-+15p*wi   ",
                          "    w6>#awi     ",
                          "    is9wi       ",
                          "     ii         " ]);



reload_slick = QPixmapWrapper(["16 16 143 2",
                               "   c None",
                               " . c #CDDAF4",
                               " X c #3A64B3",
                               " o c #E4ECFA",
                               " O c #4887FC",
                               " + c #9CB6E8",
                               " @ c #3B66B7",
                               " # c #8AACEA",
                               " $ c #BAD0F8",
                               " % c #3269CF",
                               " & c #B4CAF2",
                               " * c #6696EE",
                               " = c #5183E0",
                               " - c #6494EC",
                               " ; c #E9ECF1",
                               " : c #C4D4F1",
                               " > c #6C94E0",
                               " , c #3269D2",
                               " < c #D6E0F2",
                               " 1 c #3B80FF",
                               " 2 c #90B1EC",
                               " 3 c #3B65B3",
                               " 4 c #C6D3EC",
                               " 5 c #FAFBFE",
                               " 6 c #CAD4E6",
                               " 7 c #3472E4",
                               " 8 c #6C9BF0",
                               " 9 c #656565",
                               " 0 c #5E88D5",
                               " q c #636363",
                               " w c #5F5F5F",
                               " e c #C2D4F5",
                               " r c #4686FC",
                               " t c #B1CAF8",
                               " y c #699CFA",
                               " u c #A3B7DD",
                               " i c #4A7FE2",
                               " p c #A3BCEA",
                               " a c #3569CA",
                               " s c #4E6286",
                               " d c #B8CCEE",
                               " f c #3C81FF",
                               " g c #3765B8",
                               " h c #3663B7",
                               " j c #81A5E6",
                               " k c #3471E3",
                               " l c #3C66B6",
                               " z c #3B66B5",
                               " x c #A8C2F5",
                               " c c #92AFE6",
                               " v c #3E70CF",
                               " b c #326CD7",
                               " n c #CBD5E9",
                               " m c #F6F8FC",
                               " M c #486190",
                               " N c #7EA3E6",
                               " B c #5789E4",
                               " V c #83ACF8",
                               " C c #EEF0F4",
                               " Z c #9ABEFE",
                               " A c #3269D0",
                               " S c #DCE6F6",
                               " D c #4D648E",
                               " F c #D8E2F2",
                               " G c #8EADE8",
                               " H c #4A80E4",
                               " J c #356ACC",
                               " K c #D9E4F6",
                               " L c #3368CA",
                               " P c #719FF3",
                               " I c #5A8AE3",
                               " U c #B5C9ED",
                               " Y c #3D64AC",
                               " T c #4980E6",
                               " R c #3E61A3",
                               " E c #6E95DC",
                               " W c #3268CC",
                               " Q c #4888FC",
                               " ! c #3467C4",
                               " ~ c #D4E0F4",
                               " ^ c #3472E5",
                               " / c #EBF0FA",
                               " ( c #7AA6F8",
                               " ) c #DEE7F7",
                               " _ c #A4BCE9",
                               " ` c #3776EB",
                               " ' c #465D86",
                               " ] c #8CACE5",
                               " [ c #FDFEFE",
                               " { c #A5BEED",
                               " } c #326AD2",
                               " | c #3A5FA5",
                               ".  c #A1BAE9",
                               ".. c #B9CCF0",
                               ".X c #A3B9E1",
                               ".o c #B7CAEE",
                               ".O c #3765B9",
                               ".+ c #CEDCF4",
                               ".@ c #C9D3E5",
                               ".# c #5B88DC",
                               ".$ c #6E99E8",
                               ".% c #9DC0FF",
                               ".& c #5891FA",
                               ".* c #3E62A5",
                               ".= c #3269CE",
                               ".- c #585858",
                               ".; c #4F6184",
                               ".: c #7CA1E5",
                               ".> c #525252",
                               "., c #3B63AF",
                               ".< c #FFFFFF",
                               ".1 c #3269D1",
                               ".2 c #84A6E6",
                               ".3 c #799FE5",
                               ".4 c #EDF0F7",
                               ".5 c #B2C5E8",
                               ".6 c #E4EBF8",
                               ".7 c #326BD4",
                               ".8 c #E5E8EF",
                               ".9 c #346ACC",
                               ".0 c #3268CA",
                               ".q c #658EDB",
                               ".w c #3572E4",
                               ".e c #D4DEF2",
                               ".r c #CBD9F3",
                               ".t c #3E71CF",
                               ".y c #E1E9F8",
                               ".u c #F7F9FD",
                               ".i c #3268CD",
                               ".p c #4083FF",
                               ".a c #3766BE",
                               ".s c #9AB5E7",
                               ".d c #3873E0",
                               ".f c #97B3E4",
                               ".g c #447CE5",
                               ".h c #3676EB",
                               ".j c #F2F5FB",
                               ".k c #6C98EB",
                               ".l c #8DACE7",
                               ".z c #326AD3",
                               ".x c #3469CB",
                               ".c c #4F8AF6",
                               ".v c None",
                               "          .1 %.i W.0 h 9        ",
                               "      .1 , b ^ =.# 7.7 L g.-    ",
                               "    .1.z T x.6.j.j /.. B.= z.>  ",
                               "   A } - ~.y F n < ).y S.3.= R.>",
                               "   % T : . 6.8.< C.e . ..r I ! 9",
                               " W.7 2 d.@.<.<.<.< K d d.o.f.z M",
                               " W.d. .X.< [.o.s _ + p U ( 1 k X",
                               " W i ].5.<.+ c c u 4.<.<.% 1.h @",
                               " W.g.$ {.< t.c #.<.<.<.< Z f ` l",
                               ".0.w r 8.< m y.&.4.<.<.< V.p 7 Y",
                               " h.7 O Q $.<.< ;.<.<.<.< P O.z.;",
                               " 9 L H * * &.u.< 5 e o.u.k H.a 9",
                               "  .O.9 > N N N.2 N N.: j >.x s 9",
                               "   9 3 J.q.l G G G G.l.q a D 9 9",
                               "     9.* !.t 0 E E 0 v.a s 9 9  ",
                               "      .> q ' |., l Y.; w.>.>    " ]);


publish = QPixmapWrapper(["16 16 13 1",
                          "j c #000000",
                          "# c #000000",
                          "k c #303030",
                          "a c #404000",
                          "c c #585858",
                          "e c #800000",
                          "h c #808080",
                          "i c #a0a0a0",
                          "f c #c00000",
                          "g c #c3c3c3",
                          "d c #dcdcdc",
                          ". c None",
                          "b c #ffffff",
                          ".....##.........",
                          ".....abc#.......",
                          "....#dbbdc#.....",
                          "....cbbebbdc#...",
                          "...#dbbbfebbdc#.",
                          "..#db##bbbfebbg#",
                          ".#db#bb##bbbbdh#",
                          ".cbbb##bb##bbai#",
                          "#bb##bb##bbbdc#h",
                          "#dbbb##bb#bbhic#",
                          "#hgdbbb##bbdcc#j",
                          ".#cigdbbbbbhhhc#",
                          "...#cigdbbdcca#.",
                          ".....#cigdacc#..",
                          ".......#chk##...",
                          ".........##....."]);


publish_active = QPixmapWrapper(["16 16 13 1",
                                 "j c #000000",
                                 "# c #000000",
                                 "k c #303030",
                                 "a c #404000",
                                 "c c #585858",
                                 "e c #800000",
                                 "h c #808080",
                                 "i c #a0a0a0",
                                 "f c #c00000",
                                 "g c #c3c3c3",
                                 "d c #dcdc00",
                                 ". c None",
                                 "b c #ffff00",
                                 ".....##.........",
                                 ".....abc#.......",
                                 "....#dbbdc#.....",
                                 "....cbbebbdc#...",
                                 "...#dbbbfebbdc#.",
                                 "..#db##bbbfebbg#",
                                 ".#db#bb##bbbbdh#",
                                 ".cbbb##bb##bbai#",
                                 "#bb##bb##bbbdc#h",
                                 "#dbbb##bb#bbhic#",
                                 "#hgdbbb##bbdcc#j",
                                 ".#cigdbbbbbhhhc#",
                                 "...#cigdbbdcca#.",
                                 ".....#cigdacc#..",
                                 ".......#chk##...",
                                 ".........##....."]);

node_any = QPixmapWrapper(["16 16 5 1",
                           "  c None",
                           ". c #808080",
                           "X c #FFFF00",
                           "o c #0000FF",
                           "O c None",
                           "                ",
                           " o         o    ",
                           "  o       o .   ",
                           "   o     o .    ",
                           "    o   o .     ",
                           "   ooooooo      ",
                           "   oXXXXXo.     ",
                           "   oXXXXXo.     ",
                           "   oXXXXXo.     ",
                           "   ooooooo.     ",
                           "    ..o....     ",
                           "      o.        ",
                           "      o.        ",
                           "      o.        ",
                           "       .        ",
                           "                " ]);
                           
node_command = QPixmapWrapper(["16 16 7 1",
                               "  c None",
                               ". c #00FF00",
                               "X c #000040",
                               "o c #808080",
                               "O c #A8DCFF",
                               "+ c #0000FF",
                               "@ c #000000",
                               "                ",
                               " +         +    ",
                               "  +       + o   ",
                               "   +     + o    ",
                               "    +   + o     ",
                               "   +++++++      ",
                               "   +OOOOO+o     ",
                               "   +OOOOO+....  ",
                               "   +OOOOO..@@.. ",
                               "   ++++++.@@.@.o",
                               "    oo+oo.@@...o",
                               "      +o .@@...o",
                               "      +o .@@.@.o",
                               "      +o ..@@..o",
                               "      +o  ....oo",
                               "       o   oooo "]);
                               
node_eval = QPixmapWrapper(["16 16 7 1",
                           "  c None",
                           ". c #00FF00",
                           "X c #000040",
                           "o c #808080",
                           "O c #A8DCFF",
                           "+ c #0000FF",
                           "@ c None",
                           "                ",
                           " +         +    ",
                           "  +       + o   ",
                           "   +     + o    ",
                           "    + XXXXX     ",
                           "   +++X...Xo    ",
                           "   +OOX...Xo    ",
                           "   +OXX...XX    ",
                           "   +OX.....Xo   ",
                           "   +++X...Xoo   ",
                           "    oo+X.Xoo    ",
                           "      +oXoo     ",
                           "      +o o      ",
                           "      +o        ",
                           "       o        ",
                           "                "]);
                           
node_idle = QPixmapWrapper(["16 16 4 1",
                           "  c None",
                           ". c #000040",
                           "X c #808080",
                           "o c None",
                           "                ",
                           " .         .    ",
                           "  .       . X   ",
                           "   .     . X    ",
                           "    .   . X     ",
                           "   .......      ",
                           "   .XXXXX.X     ",
                           "   .X    .X     ",
                           "   .X    .X     ",
                           "   .......X     ",
                           "    XX.XXXX     ",
                           "      .X        ",
                           "      .X        ",
                           "      .X        ",
                           "       X        ",
                           "                "]);

node_poll = QPixmapWrapper(["16 16 7 1",
                           "  c None",
                           ". c #00FF00",
                           "X c #000040",
                           "o c #808080",
                           "O c #A8DCFF",
                           "+ c #0000FF",
                           "@ c None",
                           "                ",
                           "XXXXX   XXXXX   ",
                           "X..Xoo   X..Xo  ",
                           "X...X   X...Xo  ",
                           "XX...X X...XXo  ",
                           "XoX.XX+XX.XoXo  ",
                           " o XXOOOXXo  o  ",
                           "   +OOOOO+o     ",
                           "   +OOOOO+o     ",
                           "   +++++++o     ",
                           "    oo+oooo     ",
                           "      +o        ",
                           "      +o        ",
                           "      +o        ",
                           "       o        ",
                           "                "]);
                           
                           
node_request = QPixmapWrapper(["16 16 7 1",
                           "  c None",
                           ". c #00FF00",
                           "X c #000040",
                           "o c #808080",
                           "O c #A8DCFF",
                           "+ c #0000FF",
                           "@ c None",
                           "                ",
                           " +         +    ",
                           "  +       + o   ",
                           "   +     + o    ",
                           "    +   + o     ",
                           "   +++++++      ",
                           "   +OOOOO+o     ",
                           "   +OOXOO+o     ",
                           "   +OX.XO+o     ",
                           "   +X...X+o     ",
                           "   X.....Xo     ",
                           "   XX...XXo     ",
                           "    X...Xoo     ",
                           "    X...Xo      ",
                           "    XXXXXo      ",
                           "     ooooo      "]);


breakpoint = QPixmapWrapper(["16 16 69 1",
                             "  c None",
                             ". c #D77570",
                             "X c #DF7F7B",
                             "o c #D27E78",
                             "O c #911414",
                             "+ c #6A3936",
                             "@ c #7D1414",
                             "# c #8E1414",
                             "$ c #411414",
                             "% c #7A1414",
                             "& c #B51616",
                             "* c #CA7169",
                             "= c #541A16",
                             "- c #C2271F",
                             "; c #D9A8A2",
                             ": c #642722",
                             "> c #3B1414",
                             ", c #B81515",
                             "< c #5C1F1A",
                             "1 c #EABEB9",
                             "2 c #C56460",
                             "3 c #961414",
                             "4 c #D97570",
                             "5 c #F1C8C6",
                             "6 c #F3D7D5",
                             "7 c #A71414",
                             "8 c #DB7975",
                             "9 c #D98680",
                             "0 c #BE2727",
                             "q c #6B1414",
                             "w c #1E1414",
                             "e c #901414",
                             "r c #612621",
                             "t c #D46C67",
                             "y c #B51414",
                             "u c #2F1414",
                             "i c #F6ECEB",
                             "p c #DA7D7A",
                             "a c #EABFBB",
                             "s c #AE7269",
                             "d c #C56058",
                             "f c #CB6661",
                             "g c #BB4744",
                             "h c #761414",
                             "j c #F3D8D7",
                             "k c #5C1D18",
                             "l c #291414",
                             "z c #F6E7E7",
                             "x c #E7B8B4",
                             "c c #F3DADA",
                             "v c #DD7772",
                             "b c #DA807C",
                             "n c #341414",
                             "m c #A61414",
                             "M c #A15C54",
                             "N c #B71414",
                             "B c #6A1414",
                             "V c #FFFFFF",
                             "C c #E6B9B5",
                             "Z c #DF8580",
                             "A c #B41414",
                             "S c #671414",
                             "D c #1A1414",
                             "F c #D7A29C",
                             "G c #C0231F",
                             "H c #672F2A",
                             "J c #CA655D",
                             "K c #703B36",
                             "L c None",
                             "    +HKr<k=     ",
                             "  V+zc61CFM>    ",
                             " V+V8b9o*2gen   ",
                             " +V4XvZ----7#l  ",
                             "+ip&&&&&&&&&&SD ",
                             "+j.VVVVVVVVVV%w ",
                             "+5tV--V&V-V&V@w ",
                             ":afVV-VAV&VVV@w ",
                             "<xJ&V-VAV-V,m@w ",
                             "k;dVV-VAOVV-m%w ",
                             "=s-&&-&A&&&m3BD ",
                             " $e7G-0-NAm3hu  ",
                             "  n#7y&ymmOhu   ",
                             "   nq%@@@%Bu    ",
                             "    DwwwwwD     ",
                             "                "]);

breakpoint_ss = QPixmapWrapper(["16 16 64 1",
                                "  c None",
                                ". c #D77570",
                                "X c #DF7F7B",
                                "o c #911414",
                                "O c #6A3936",
                                "+ c #7D1414",
                                "@ c #8E1414",
                                "# c #411414",
                                "$ c #7A1414",
                                "% c #B51616",
                                "& c #541A16",
                                "* c #C2271F",
                                "= c #D9A8A2",
                                "- c #642722",
                                "; c #3B1414",
                                ": c #5C1F1A",
                                "> c #EABEB9",
                                ", c #C56460",
                                "< c #961414",
                                "1 c #D97570",
                                "2 c #F1C8C6",
                                "3 c #F3D7D5",
                                "4 c #A71414",
                                "5 c #DB7975",
                                "6 c #D98680",
                                "7 c #BE2727",
                                "8 c #6B1414",
                                "9 c #1E1414",
                                "0 c #901414",
                                "q c #612621",
                                "w c #D46C67",
                                "e c #B51414",
                                "r c #2F1414",
                                "t c #F6ECEB",
                                "y c #DA7D7A",
                                "u c #EABFBB",
                                "i c #AE7269",
                                "p c #C56058",
                                "a c #CB6661",
                                "s c #BB4744",
                                "d c #761414",
                                "f c #F3D8D7",
                                "g c #5C1D18",
                                "h c #291414",
                                "j c #F6E7E7",
                                "k c #E7B8B4",
                                "l c #F3DADA",
                                "z c #DA807C",
                                "x c #341414",
                                "c c #A61414",
                                "v c #A15C54",
                                "b c #B71414",
                                "n c #6A1414",
                                "m c #FFFFFF",
                                "M c #E6B9B5",
                                "N c #B41414",
                                "B c #671414",
                                "V c #1A1414",
                                "C c #D7A29C",
                                "Z c #C0231F",
                                "A c #672F2A",
                                "S c #CA655D",
                                "D c #703B36",
                                "F c None",
                                "    OADq:g&     ",
                                "  mOjl3>MCv;    ",
                                " mOm5z6pp,s0x   ",
                                " Om1Xppp***4@h  ",
                                "Otyppp%m%%%%%BV ",
                                "Of.ppemmeeeee$9 ",
                                "O2wp*eemeee%e+9 ",
                                "-uape*emeeeee+9 ",
                                ":kS%e*emeZeec+9 ",
                                "g=peeemmmZe*c$9 ",
                                "&ip%%*%N%%%c<nV ",
                                " #04Z*7*bNc<dr  ",
                                "  x@4e%eccodr   ",
                                "   x8$+++$nr    ",
                                "    V99999V     ",
                                "                "]);

breakpoint_delete = QPixmapWrapper(["16 16 68 1",
                                    "  c None",
                                    ". c #D77570",
                                    "X c #DF7F7B",
                                    "o c #D27E78",
                                    "O c #911414",
                                    "+ c #6A3936",
                                    "@ c #7D1414",
                                    "# c #8E1414",
                                    "$ c #411414",
                                    "% c #7A1414",
                                    "& c #B51616",
                                    "* c #CA7169",
                                    "= c #541A16",
                                    "- c #C2271F",
                                    "; c #D9A8A2",
                                    ": c #642722",
                                    "> c #3B1414",
                                    ", c #B81515",
                                    "< c #5C1F1A",
                                    "1 c #EABEB9",
                                    "2 c #C56460",
                                    "3 c #961414",
                                    "4 c #F1C8C6",
                                    "5 c #F3D7D5",
                                    "6 c #A71414",
                                    "7 c #DB7975",
                                    "8 c #D98680",
                                    "9 c #BE2727",
                                    "0 c #6B1414",
                                    "q c #1E1414",
                                    "w c #901414",
                                    "e c #612621",
                                    "r c #D46C67",
                                    "t c #B51414",
                                    "y c #2F1414",
                                    "u c #F6ECEB",
                                    "i c #DA7D7A",
                                    "p c #EABFBB",
                                    "a c #AE7269",
                                    "s c #C56058",
                                    "d c #CB6661",
                                    "f c #BB4744",
                                    "g c #761414",
                                    "h c #F3D8D7",
                                    "j c #5C1D18",
                                    "k c #291414",
                                    "l c #F6E7E7",
                                    "z c #E7B8B4",
                                    "x c #F3DADA",
                                    "c c #DD7772",
                                    "v c #DA807C",
                                    "b c #341414",
                                    "n c #A61414",
                                    "m c #A15C54",
                                    "M c #B71414",
                                    "N c #6A1414",
                                    "B c #FFFFFF",
                                    "V c #E6B9B5",
                                    "C c #DF8580",
                                    "Z c #B41414",
                                    "A c #671414",
                                    "S c #1A1414",
                                    "D c #D7A29C",
                                    "F c #C0231F",
                                    "G c #672F2A",
                                    "H c #CA655D",
                                    "J c #703B36",
                                    "K c #000000",
                                    "K   +GJe<j=   K ",
                                    " KB+lx51VDm> K  ",
                                    " BKB7v8o*2fwK   ",
                                    " +BKXcC----K#k  ",
                                    "+ui&K&&&&&K&&AS ",
                                    "+h.BBKBBBKBBB%q ",
                                    "+4rB--K&K-B&B@q ",
                                    ":pdBB-BKB&BBB@q ",
                                    "<zH&B-KZK-B,n@q ",
                                    "j;sBBKBZOKB-n%q ",
                                    "=a-&K-&Z&&Kn3NS ",
                                    " $wKF-9-MZnKgy  ",
                                    "  K#6t&tnnOgK   ",
                                    " K b0%@@@%Ny K  ",
                                    "K   SqqqqqS   K ",
                                    "                "]);
